In [1]:
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(fgsea)

Warning message:
“package ‘dplyr’ was built under R version 4.3.2”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“package ‘stringr’ was built under R version 4.3.2”
Warning message:
“package ‘fgsea’ was built under R version 4.3.3”

In [2]:
spec.links <- read.table('/nfs/lab/tscc/welison/FNIH.Liver/03_ABC/celltype_specific_links.txt', header=T)
dim(spec.links)
head(spec.links)

[1] 19929     6

  chrom start     end       Region                   Gene     celltype
1 chr1  112618977 112619277 chr1:112618977-112619277 ST7L     T
2 chr1  113783532 113783832 chr1:113783532-113783832 PHTF1    T
3 chr1   12177938  12178238 chr1:12177938-12178238   TNFRSF1B T
4 chr1  202162067 202162367 chr1:202162067-202162367 ELF3     T
5 chr1  202164591 202164891 chr1:202164591-202164891 ELF3     T
6 chr1  206612366 206612666 chr1:206612366-206612666 MAPKAPK2 T

In [3]:
table(spec.links$celltype)

            B Cholangiocyte   Endothelial   Hepatocytes           HSC
          954          1898          2342          7794           863
         Mast       Myeloid            NK       Schwann             T
           38          4958           548           198           336

In [5]:
select(spec.links, Gene, celltype) %>% distinct() %>% select(celltype) %>% table()

celltype
            B Cholangiocyte   Endothelial   Hepatocytes           HSC
          796          1464          1488          4063           723
         Mast       Myeloid            NK       Schwann             T
           38          2486           483           191           321

In [4]:
all.links <- read.table('/nfs/lab/tscc/welison/FNIH.Liver/03_ABC/FNIH_liver_celltype_abc_links.txt', header=T)
dim(all.links)
head(all.links)

[1] 50156    11

  chrom1 start1    end1      chrom2 start2    end2
1 chr1   100352254 100352554 chr1   101236527 101236528
2 chr1   101237928 101238228 chr1   101236527 101236528
3 chr1   101238744 101239044 chr1   101236527 101236528
4 chr1   101247912 101248212 chr1   101236527 101236528
5 chr1   101258017 101258317 chr1   101236527 101236528
6 chr1     1032988   1033288 chr1     3857213   3857214
  peak                     gene       pair
1 chr1:100352254-100352554 AL109741.1 genic|chr1:100352254-100352554
2 chr1:101237928-101238228 AL109741.1 genic|chr1:101237928-101238228
3 chr1:101238744-101239044 AL109741.1 genic|chr1:101238744-101239044
4 chr1:101247912-101248212 AL109741.1 intergenic|chr1:101247912-101248212
5 chr1:101258017-101258317 AL109741.1 intergenic|chr1:101258017-101258317
6 chr1:1032988-1033288     CEP104     genic|chr1:1032988-1033288
  celltype abc_score
1 B        0.020619
2 B        0.057743
3 B        0.044911
4 B        0.030475
5 B        0.020040
6 B        0.026496

### fGSEA

In [9]:
#read in Ruth's preferred pathways
go <- gmtPathways('/nfs/lab/relgamal/MAGMA/c5.go.v2023.1.Hs.symbols.gmt')
kegg <- gmtPathways('/nfs/lab/relgamal/MAGMA/c2.cp.kegg.v2023.1.Hs.symbols.gmt')
reactome <- gmtPathways('/nfs/lab/relgamal/MAGMA/c2.cp.reactome.v2023.1.Hs.symbols.gmt')
pathways <- c(go, kegg, reactome)

go_mf <- gmtPathways('/nfs/lab/relgamal/MAGMA/c5.go.mf.v2023.1.Hs.symbols.gmt.txt')
go_bp <- gmtPathways('/nfs/lab/relgamal/MAGMA/c5.go.bp.v2023.1.Hs.symbols.gmt.txt')
pathways2 <- c(kegg,reactome,go_mf,go_bp)

#read in Hallmarks pathways (Jackie's preferred pathways)
hallmarks <- gmtPathways('/nfs/lab/relgamal/MAGMA/h.all.v2023.1.Hs.symbols.gmt.txt')

#make combined pathways list so can run all at once
all_pathways <- c(pathways2, hallmarks)

In [14]:
rps <- read.table('/nfs/lab/tscc/ref/HGNC.ribosomal.genes.list.tsv', sep=',', header=TRUE)
rps

    HGNC.ID..gene. Approved.symbol
1   HGNC:14275     MRPL1
2   HGNC:14056     MRPL2
3   HGNC:10379     MRPL3
4   HGNC:14276     MRPL4
5   HGNC:14055     MRPL10
6   HGNC:14042     MRPL11
7   HGNC:10378     MRPL12
8   HGNC:14278     MRPL13
9   HGNC:14279     MRPL14
10  HGNC:14054     MRPL15
11  HGNC:14476     MRPL16
12  HGNC:14053     MRPL17
13  HGNC:14477     MRPL18
14  HGNC:14052     MRPL19
15  HGNC:14478     MRPL20
16  HGNC:14479     MRPL21
17  HGNC:14480     MRPL22
18  HGNC:10322     MRPL23
19  HGNC:14037     MRPL24
20  HGNC:14483     MRPL27
21  HGNC:14484     MRPL28
22  HGNC:14036     MRPL30
23  HGNC:14035     MRPL32
24  HGNC:14487     MRPL33
25  HGNC:14488     MRPL34
26  HGNC:14489     MRPL35
27  HGNC:14490     MRPL36
28  HGNC:14034     MRPL37
29  HGNC:14033     MRPL38
30  HGNC:14027     MRPL39
⋮   ⋮              ⋮
218 HGNC:10425     RPS4Y1
219 HGNC:18501     RPS4Y2
220 HGNC:10426     RPS5
221 HGNC:10429     RPS6
222 HGNC:10440     RPS7
223 HGNC:10441     RPS8
224 HGNC:10442     RPS9
225 HGNC:10383     RPS10
226 HGNC:10384     RPS11
227 HGNC:10385     RPS12
228 HGNC:10386     RPS13
229 HGNC:10387     RPS14
230 HGNC:10388     RPS15
231 HGNC:10389     RPS15A
232 HGNC:10396     RPS16
233 HGNC:10397     RPS17
234 HGNC:10401     RPS18
235 HGNC:10402     RPS19
236 HGNC:10405     RPS20
237 HGNC:10409     RPS21
238 HGNC:10410     RPS23
239 HGNC:10411     RPS24
240 HGNC:10413     RPS25
241 HGNC:10414     RPS26
242 HGNC:10416     RPS27
243 HGNC:10417     RPS27A
244 HGNC:18476     RPS27L
245 HGNC:10418     RPS28
246 HGNC:10419     RPS29
247 HGNC:3597      FAU
    Approved.name                                       Previous.symbols
1   mitochondrial ribosomal protein L1
2   mitochondrial ribosomal protein L2
3   mitochondrial ribosomal protein L3                  RPML3
4   mitochondrial ribosomal protein L4
5   mitochondrial ribosomal protein L10
6   mitochondrial ribosomal protein L11
7   mitochondrial ribosomal protein L12                 RPML12
8   mitochondrial ribosomal protein L13
9   mitochondrial ribosomal protein L14
10  mitochondrial ribosomal protein L15
11  mitochondrial ribosomal protein L16
12  mitochondrial ribosomal protein L17
13  mitochondrial ribosomal protein L18
14  mitochondrial ribosomal protein L19
15  mitochondrial ribosomal protein L20
16  mitochondrial ribosomal protein L21
17  mitochondrial ribosomal protein L22
18  mitochondrial ribosomal protein L23                 RPL23L
19  mitochondrial ribosomal protein L24
20  mitochondrial ribosomal protein L27
21  mitochondrial ribosomal protein L28                 MAAT1
22  mitochondrial ribosomal protein L30
23  mitochondrial ribosomal protein L32
24  mitochondrial ribosomal protein L33                 C2orf1
25  mitochondrial ribosomal protein L34
26  mitochondrial ribosomal protein L35
27  mitochondrial ribosomal protein L36
28  mitochondrial ribosomal protein L37
29  mitochondrial ribosomal protein L38
30  mitochondrial ribosomal protein L39
⋮   ⋮                                                   ⋮
218 ribosomal protein S4 Y-linked 1                     RPS4Y
219 ribosomal protein S4 Y-linked 2                     RPS4Y2P
220 ribosomal protein S5
221 ribosomal protein S6
222 ribosomal protein S7
223 ribosomal protein S8
224 ribosomal protein S9
225 ribosomal protein S10
226 ribosomal protein S11
227 ribosomal protein S12
228 ribosomal protein S13
229 ribosomal protein S14
230 ribosomal protein S15
231 ribosomal protein S15a
232 ribosomal protein S16
233 ribosomal protein S17                               RPS17L
234 ribosomal protein S18                               D6S218E
235 ribosomal protein S19                               LOH19CR1
236 ribosomal protein S20
237 ribosomal protein S21
238 ribosomal protein S23
239 ribosomal protein S24
240 ribosomal protein S25
241 ribosomal protein S26
242 ribosomal protein S27
243 ribosomal protein S27a
244 ribosomal protein S27 like
245 ribosomal protein S28
246 ribosomal protein S29
247 FAU ubiquitin like and ribosomal protein S30 fusion
    Aliases
1   BM022,uL1m
2   MRP-L14,RPML14,CGI-22,uL2m
3   MRL3,uL3m
4   CGI-28,uL4m
5   RPML8,MRP-L8,L10MT,MRP-L10,MRPL8,MGC17973,uL10m
6   uL11m
7   MRPL7/L12,MRPL7,bL12m
8   L13,RPL13,L13mt,RPML13,L13A,uL13m
9   RPML32,MRP-L32,uL14m
10  RPML7,MRP-L7,HSPC145,L15mt,MRP-L15,uL15m
11  FLJ20484,PNAS-111,uL16m
12  RPML26,MRP-L26,bL17m
13  HSPC071,uL18m
14  MRP-L15,RPML15,KIAA0104,RLX1,bL19m
15  FLJ10024,bL20m
16  bL21m
17  MRP-L25,RPML25,HSPC158,uL22m
18  L23MRP,uL23m
19  MRP-L18,uL24m
20  bL27m
21  p15,bL28m
22  MRP-L28,RPML28,uL30m
23  HSPC283,L32mt,MRP-L32,bMRP-59b,bL32m
24  RPL33L,bL33m
25  L34mt,MGC2633,MGC24974,bL34m
26  bL35m
27  RPMJ,L36mt,PRPL36,MRP-L36,bL36m
28  RPML2,MRP-L2,mL37
29  RPML3,MRP-L3,HSPC262,MGC4810,mL38
30  RPML5,MRP-L5,MGC104174,PRED66,PRED22,C21orf92,L39mt,MSTP003,MGC3400,FLJ20451,mL39
⋮   ⋮
218 MGC5070,MGC119100,S4
219
220 S5,uS7
221 S6,eS6
222 S7,eS7
223 S8,eS8
224 S9,uS4
225 MGC88819,S10,eS10
226 S11,uS17
227 S12,eS12
228 S13,uS15
229 EMTB,S14,uS11
230 RIG,MGC111130,S15,uS19
231 S15A,uS8
232 S16,uS9
233 RPS17L1,RPS17L2,MGC72007,S17,eS17
234 KE3,KE-3,HKE3,S18,uS13
235 S19,eS19,DBA
236 S20,uS10
237 S21,eS21
238 S23,uS12
239 S24,eS24
240 S25,eS25
241 S26,eS26
242 MPS-1,MPS1,S27,eS27
243 UBCEP80,Uba80,S27A,eS31
244
245 S28,eS28
246 S29,uS14
247 RPS30,FLJ22986,Fub1,Fubi,MNSFbeta,asr1,S30,eS30
    Chromosome Group
1   4q21.1     Large subunit mitochondrial ribosomal proteins
2   6p21.1     Large subunit mitochondrial ribosomal proteins
3   3q22.1     Large subunit mitochondrial ribosomal proteins
4   19p13.2    Large subunit mitochondrial ribosomal proteins
5   17q21.32   Large subunit mitochondrial ribosomal proteins
6   11q13.2    Large subunit mitochondrial ribosomal proteins
7   17q25.3    Large subunit mitochondrial ribosomal proteins
8   8q24.12    Large subunit mitochondrial ribosomal proteins
9   6p21.1     Large subunit mitochondrial ribosomal proteins
10  8q11.23    Large subunit mitochondrial ribosomal proteins
11  11q12.1    Large subunit mitochondrial ribosomal proteins
12  11p15.4    Large subunit mitochondrial ribosomal proteins
13  6q25.3     Large subunit mitochondrial ribosomal proteins
14  2p12       Large subunit mitochondrial ribosomal proteins
15  1p36.33    Large subunit mitochondrial ribosomal proteins
16  11q13.3    Large subunit mitochondrial ribosomal proteins
17  5q33.2     Large subunit mitochondrial ribosomal proteins
18  11p15.5    Large subunit mitochondrial ribosomal proteins
19  1q23.1     Large subunit mitochondrial ribosomal proteins
20  17q21.33   Large subunit mitochondrial ribosomal proteins
21  16p13.3    Large subunit mitochondrial ribosomal proteins
22  2q11.2     Large subunit mitochondrial ribosomal proteins
23  7p14.1     Large subunit mitochondrial ribosomal proteins
24  2p23.2     Large subunit mitochondrial ribosomal proteins
25  19p13.11   Large subunit mitochondrial ribosomal proteins
26  2p11.2     Large subunit mitochondrial ribosomal proteins
27  5p15.33    Large subunit mitochondrial ribosomal proteins
28  1p32.3     Large subunit mitochondrial ribosomal proteins
29  17q25.1    Large subunit mitochondrial ribosomal proteins
30  21q21.3    Large subunit mitochondrial ribosomal proteins
⋮   ⋮          ⋮
218 Yp11.2     S ribosomal proteins
219 Yq11.223   S ribosomal proteins
220 19q13.43   S ribosomal proteins
221 9p22.1     S ribosomal proteins
222 2p25.3     S ribosomal proteins
223 1p34.1     S ribosomal proteins
224 19q13.42   S ribosomal proteins
225 6p21.31    S ribosomal proteins
226 19q13.3    S ribosomal proteins
227 6q23.2     S ribosomal proteins
228 11p15.1    S ribosomal proteins
229 5q33.1     S ribosomal proteins
230 19p13.3    S ribosomal proteins
231 16p12.3    S ribosomal proteins
232 19q13.2    S ribosomal proteins
233 15q25.2    S ribosomal proteins
234 6p21.32    S ribosomal proteins
235 19q13.2    S ribosomal proteins
236 8q12.1     S ribosomal proteins
237 20q13.33   S ribosomal proteins
238 5q14.2     S ribosomal proteins
239 10q22.3    S ribosomal proteins
240 11q23.3    S ribosomal proteins
241 12q13.2    S ribosomal proteins
242 1q21.3     S ribosomal proteins
243 2p16.1     S ribosomal proteins
244 15q22.2    S ribosomal proteins
245 19p13.2    S ribosomal proteins
246 14q21.3    S ribosomal proteins
247 11q13.1    S ribosomal proteins

In [27]:
spec.genes <- unique(filter(spec.links, celltype==cell)$Gene)
all.genes <- unique(all.links$gene)
    
    spec.genes <- spec.genes[!spec.genes %in% rps$Approved.symbol]
    all.genes <- all.genes[!all.genes %in% rps$Approved.symbol]

In [23]:
length(spec.genes)
length(all.genes)

[1] 789

[1] 6883

In [24]:
fora(pathways=all_pathways, genes=spec.genes, universe=all.genes, minSize = 1, maxSize = Inf)

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”

      pathway
1     GOBP_CELLULAR_RESPONSE_TO_STRESS
2     GOBP_REGULATION_OF_INTRACELLULAR_SIGNAL_TRANSDUCTION
3     GOBP_REGULATION_OF_GTPASE_ACTIVITY
4     REACTOME_CYTOKINE_SIGNALING_IN_IMMUNE_SYSTEM
5     GOBP_SMALL_GTPASE_MEDIATED_SIGNAL_TRANSDUCTION
6     GOBP_POSITIVE_REGULATION_OF_MOLECULAR_FUNCTION
7     GOMF_NUCLEOSIDE_TRIPHOSPHATASE_REGULATOR_ACTIVITY
8     GOBP_POSITIVE_REGULATION_OF_PROTEIN_METABOLIC_PROCESS
9     GOBP_REGULATION_OF_CELL_ADHESION
10    GOBP_POSITIVE_REGULATION_OF_GENE_EXPRESSION
11    GOBP_DNA_METABOLIC_PROCESS
12    GOBP_POSITIVE_REGULATION_OF_GTPASE_ACTIVITY
13    GOBP_REGULATION_OF_CELL_SUBSTRATE_ADHESION
14    GOBP_PROTEIN_K63_LINKED_UBIQUITINATION
15    GOBP_LYMPHOCYTE_ACTIVATION
16    GOMF_ENZYME_REGULATOR_ACTIVITY
17    GOBP_LEUKOCYTE_DIFFERENTIATION
18    GOBP_REGULATION_OF_PROTEIN_MODIFICATION_PROCESS
19    GOBP_POSITIVE_REGULATION_OF_PEPTIDYL_TYROSINE_PHOSPHORYLATION
20    GOBP_POSITIVE_REGULATION_OF_PROTEIN_MODIFICATION_PROCESS
21    REACTOME_ADAPTIVE_IMMUNE_SYSTEM
22    GOBP_DNA_REPLICATION
23    GOMF_MODIFICATION_DEPENDENT_PROTEIN_BINDING
24    GOBP_CYTOSKELETON_ORGANIZATION
25    GOBP_ACTIN_FILAMENT_BASED_PROCESS
26    GOBP_NEGATIVE_REGULATION_OF_NUCLEOBASE_CONTAINING_COMPOUND_METABOLIC_PROCESS
27    GOBP_CELL_ACTIVATION
28    REACTOME_MEMBRANE_TRAFFICKING
29    GOBP_B_CELL_ACTIVATION
30    GOMF_MOLECULAR_FUNCTION_ACTIVATOR_ACTIVITY
⋮     ⋮
11007 GOBP_POSITIVE_REGULATION_OF_INTEGRIN_MEDIATED_SIGNALING_PATHWAY
11008 GOBP_NEGATIVE_REGULATION_OF_MESENCHYMAL_CELL_APOPTOTIC_PROCESS
11009 GOBP_REGULATION_OF_ENDOCYTIC_RECYCLING
11010 GOBP_POSITIVE_REGULATION_OF_ENDOCYTIC_RECYCLING
11011 GOBP_NEGATIVE_REGULATION_OF_ATP_BIOSYNTHETIC_PROCESS
11012 GOBP_POSITIVE_REGULATION_OF_CD8_POSITIVE_ALPHA_BETA_T_CELL_ACTIVATION
11013 GOBP_REGULATION_OF_T_CELL_ACTIVATION_VIA_T_CELL_RECEPTOR_CONTACT_WITH_ANTIGEN_BOUND_TO_MHC_MOLECULE_ON_ANTIGEN_PRESENTING_CELL
11014 GOBP_REGULATION_OF_DENDRITIC_CELL_DIFFERENTIATION
11015 GOBP_NEGATIVE_REGULATION_OF_DENDRITIC_CELL_DIFFERENTIATION
11016 GOBP_POSITIVE_REGULATION_OF_DENDRITIC_CELL_DIFFERENTIATION
11017 GOBP_REGULATION_OF_VASCULOGENESIS
11018 GOBP_POSITIVE_REGULATION_OF_VASCULOGENESIS
11019 GOBP_REGULATION_OF_NEURON_MIGRATION
11020 GOBP_NEGATIVE_REGULATION_OF_NEURON_MIGRATION
11021 GOBP_POSITIVE_REGULATION_OF_NEURON_MIGRATION
11022 GOBP_REGULATION_OF_CHLORIDE_TRANSPORT
11023 GOBP_REGULATION_OF_PHOSPHATIDYLCHOLINE_BIOSYNTHETIC_PROCESS
11024 GOBP_REGULATION_OF_STORE_OPERATED_CALCIUM_ENTRY
11025 GOBP_REGULATION_OF_CYSTEINE_TYPE_ENDOPEPTIDASE_ACTIVITY_INVOLVED_IN_APOPTOTIC_SIGNALING_PATHWAY
11026 GOBP_NEGATIVE_REGULATION_OF_CYSTEINE_TYPE_ENDOPEPTIDASE_ACTIVITY_INVOLVED_IN_APOPTOTIC_SIGNALING_PATHWAY
11027 GOBP_POSITIVE_REGULATION_OF_CYSTEINE_TYPE_ENDOPEPTIDASE_ACTIVITY_INVOLVED_IN_APOPTOTIC_SIGNALING_PATHWAY
11028 GOBP_REGULATION_OF_CYSTEINE_TYPE_ENDOPEPTIDASE_ACTIVITY_INVOLVED_IN_EXECUTION_PHASE_OF_APOPTOSIS
11029 GOBP_REGULATION_OF_UNSATURATED_FATTY_ACID_BIOSYNTHETIC_PROCESS
11030 GOBP_POSITIVE_REGULATION_OF_UNSATURATED_FATTY_ACID_BIOSYNTHETIC_PROCESS
11031 GOBP_REGULATION_OF_BMP_SECRETION
11032 GOBP_REGULATION_OF_CAVEOLIN_MEDIATED_ENDOCYTOSIS
11033 GOBP_MALONYL_COA_METABOLIC_PROCESS
11034 GOBP_LIPOXIN_METABOLIC_PROCESS
11035 HALLMARK_NOTCH_SIGNALING
11036 HALLMARK_SPERMATOGENESIS
      pval         padj        overlap size
1     1.634993e-07 0.001804378 75      709
2     9.648580e-07 0.003851055 72      701
3     1.139698e-06 0.003851055 25      147
4     1.669072e-06 0.003851055 42      334
5     2.208264e-06 0.003851055 31      214
6     2.211667e-06 0.003851055 62      585
7     2.442677e-06 0.003851055 31      215
8     4.117101e-06 0.005679541 59      557
9     5.250586e-06 0.006438385 42      349
10    6.437394e-06 0.006878460 48      425
11    6.856022e-06 0.006878460 39      317
12    8.901899e-06 0.007788730 19      105
13    9.174836e-06 0.007788730 18       96
14    1.358815e-05 0.009682881  8       21
15    1.363123e-05 0.009682881 44      387
16    1.403825e-05 0.009682881 53      501
17    1.502825e-05 0.009755984 36      292
18    2.051265e-05 0.012451191 57      560
19    2.143645e-05 0.012451191 14       66
20    2.802910e-05 0.015227340 41      361
21    2.897555e-05 0.015227340 39      337
22    3.199927e-05 0.015954779 15       77
23    3.325117e-05 0.015954779 13       60
24    3.730790e-05 0.017104136 47      441
25    3.874623e-05 0.017104136 34      281
26    4.624729e-05 0.019095002 54      536
27    4.671666e-05 0.019095002 53      523
28    5.075420e-05 0.020004405 32      261
29    5.289286e-05 0.020128469 21      139
30    5.557304e-05 0.020443471 47      448
⋮     ⋮            ⋮           ⋮       ⋮
11007 1            1           0        7
11008 1            1           0        2
11009 1            1           0        4
11010 1            1           0        3
11011 1            1           0        3
11012 1            1           0        3
11013 1            1           0        4
11014 1            1           0        7
11015 1            1           0        2
11016 1            1           0        5
11017 1            1           0        6
11018 1            1           0        5
11019 1            1           0        9
11020 1            1           0        3
11021 1            1           0        3
11022 1            1           0        5
11023 1            1           0        3
11024 1            1           0        7
11025 1            1           0        9
11026 1            1           0        4
11027 1            1           0        5
11028 1            1           0        2
11029 1            1           0        5
11030 1            1           0        3
11031 1            1           0        1
11032 1            1           0        3
11033 1            1           0        2
11034 1            1           0        1
11035 1            1           0       14
11036 1            1           0       23
      overlapGenes
1     TANK     , SH2D3C   , RAD50    , CDK6     , CDK9     , ERLIN1   , RGS14    , CBX3     , CYBB     , BMT2     , SDE2     , PTK2B    , ERP44    , PSME4    , ZMYND8   , ZBTB38   , FOXP1    , SESN1    , PDCD4    , HIPK2    , NPC1L1   , STOML2   , HNRNPA1  , SCIMP    , LYN      , MAN1A1   , CCDC88C  , NF1      , NFATC2   , PRDX1    , ZBTB7B   , ZBTB7A   , UCHL5    , UBE2J1   , PDK1     , SERPINB6 , SLC38A2  , FBXW7    , RNF126   , SLF2     , PRKCD    , WRNIP1   , BACH1    , ZMIZ1    , ARID1B   , PTPN1    , BCL2     , BCL2L1   , BCL3     , BID      , CREB3L2  , SIPA1    , TRAF3    , TRAF5    , DNAJC7   , UBE2B    , VCP      , VDAC1    , XBP1     , YY1      , DERL1    , RNASEH2B , CASP3    , CCM2     , PARP9    , LRRC8C   , TNFRSF10B, KAT2B    , MBD4     , HELB     , CD27     , EIF2AK3  , NFE2L3   , HERPUD1  , SUSD6
2     TANK     , TNIP1    , SEMA4D   , RGS14    , PIM2     , AKAP13   , ARHGAP42 , CSK      , BMT2     , ENG      , PTK2B    , FGD2     , FGA      , FGG      , RASA3    , DENND3   , CARD8    , RAP1GAP2 , SGMS1    , CYTH4    , SESN1    , PDCD4    , HIPK2    , HCLS1    , HINT1    , TICAM2   , KRAS     , SCIMP    , ARHGAP4  , LYN      , MYO9B    , NF1      , PRDX1    , PIK3CG   , PLCG2    , ZFAND6   , NDFIP2   , RASIP1   , FBXW7    , PRR5     , PRKCD    , CDC42SE2 , PELI1    , RALGAPA2 , PTBP1    , ARRDC3   , PREX1    , PTPN1    , PTPRJ    , RAP1B    , BCL2     , BCL2L1   , BCL3     , BID      , SIPA1    , TRAF3    , TRAF5    , TRIP6    , UBE2B    , XBP1     , RNASEH2B , LRRK1    , TNFRSF10B, LIMD1    , ARHGEF1  , CYTH1    , CD27     , EIF2AK3  , CD40     , HERPUD1  , RIPOR2   , CDC34
3     PLXNC1  , SEMA4D  , RGS14   , ARHGAP42, PTK2B   , FGD2    , RASA3   , TBC1D9B , RAP1GAP2, TBC1D9  , CORO1C  , RABGAP1 , NEDD9   , NF1     , RASIP1  , DOCK10  , RALGAPA2, PREX1   , RALGDS  , RGS1    , SIPA1   , CD40    , USP6NL  , RIPOR2  , RAPGEF5
4     PSME4    , PTPN18   , CSF2RB   , RPS6KA5  , CD40     , RAE1     , CSK      , PIK3CG   , KPNB1    , PTK2B    , PLCG1    , IRF1     , PSMF1    , RAP1B    , TRAF3    , NUP210   , KRAS     , FLNB     , IRF4     , CD27     , POU2F1   , GSTO1    , PTPRJ    , PDCD4    , MX1      , GAB3     , PRKCD    , CASP3    , IRF2     , INPP5D   , BCL2L1   , BCL2     , ISG20    , SAA1     , PITPNA   , MX2      , IFITM2   , PTPN1    , PELI1    , PLCG2    , TNFRSF13B, LYN
5     SH2D3C  , AKAP13  , CHML    , ARHGAP42, FGD2    , RASA3   , DENND3  , RAP1GAP2, CYTH4   , RND1    , RAB30   , KPNB1   , KRAS    , ARHGAP4 , CCDC88C , MYO9B   , NF1     , PIK3CG  , RASIP1  , DOCK10  , CDC42SE2, RALGAPA2, PREX1   , RALGDS  , RAP1B   , SIPA1   , ARHGEF1 , CYTH1   , RIPOR2  , RAPGEF5 , ELMO1
6     TANK     , RAD50    , CDK9     , SEMA4D   , CCT4     , RGS14    , AKAP13   , ARHGAP42 , CSK      , PTK2B    , FGD2     , CARD8    , TBC1D9B  , RAP1GAP2 , GRAMD4   , TBC1D9   , CORO1C   , GNA15    , ANK3     , HIPK2    , HCLS1    , TICAM2   , IRF4     , LYN      , NAB2     , NEDD9    , NF1      , ZBTB7A   , PIK3CG   , PLCG2    , FBXW7    , DOCK10   , PRKCD    , CAMK1D   , RALGAPA2 , ARRDC3   , PREX1    , PTPN1    , RALGDS   , BCL2     , RGS1     , BID      , SDC4     , VSIR     , SIPA1    , TCF3     , TRAF5    , VCP      , DERL1    , NCOA3    , PARP9    , ARID5B   , TNFRSF10B, CCND2    , RPS6KA5  , GSTO1    , EIF2AK3  , CD40     , PPM1F    , USP6NL   , RIPOR2   , RAPGEF5
7     SH2D3C  , RGS14   , AKAP13  , CHML    , ARHGAP42, DENND5B , FGD2    , RASA3   , DENND3  , TBC1D9B , RAP1GAP2, TBC1D9  , RABGAP1 , CYTH4   , ARHGAP4 , CCDC88C , MYO9B   , NF1     , DOCK10  , RALGAPA2, PREX1   , RALGDS  , RGS1    , SIPA1   , HPS4    , ARHGEF1 , CYTH1   , SH3BP5  , USP6NL  , RAPGEF5 , ELMO1
8     TANK     , SH2D3C   , RAD50    , TNIP1    , SEMA4D   , BAZ2A    , AKAP13   , CSK      , EEF2     , ENG      , F12      , PTK2B    , FGD2     , CARD8    , GRAMD4   , GGA3     , HIPK2    , HCLS1    , KRAS     , LYN      , NAB2     , NEDD9    , PECAM1   , PIK3CG   , PLCG2    , NDFIP2   , MOB1A    , FBXW7    , PRR5     , PRKCD    , PELI1    , PTBP1    , ARRDC3   , PTPN1    , PTPRJ    , BCL2     , BCL3     , BID      , SDC4     , VSIR     , VCP      , CNBP     , DERL1    , ZYG11B   , LRRK1    , CASP3    , PARP9    , GLYR1    , CBFA2T3  , TNFRSF10B, CCND2    , ACVR1    , EIF2AK3  , CD40     , RNF14    , ABCG1    , PPM1F    , HERPUD1  , CTIF
9     ARPC2  , PLXNC1 , CDK6   , SEMA4D , CSK    , ETS1   , PTK2B  , FGA    , FGG    , CORO1C , RND1   , ANK3   , IRF1   , LYN    , NEDD9  , NF1    , ZBTB7B , PIK3CG , PRKCD  , PELI1  , ZMIZ1  , ARID1B , PREX1  , PTPRJ  , RAC2   , BCL2   , RREB1  , SAA1   , SDC4   , VSIR   , ST6GAL1, SIPA1  , TLN1   , UTRN   , XBP1   , CASP3  , AP3D1  , CYTH1  , CD27   , CHST2  , PPM1F  , RIPOR2
10    CDK6   , CTCF   , U2AF2  , CYBB   , EEF2   , ENG    , ETS1   , F12    , PTK2B  , CARD8  , FOXP1  , ANK3   , STOML2 , ID3    , TICAM2 , IRF1   , IRF4   , KRAS   , SCIMP  , NFATC2 , ZBTB7B , PIK3CG , BCL11A , PLCG2  , SLC38A2, POU2AF1, TENT5C , PELI1  , ARID1B , PTPRJ  , BCL3   , SAA1   , PRDM1  , VSIR   , CREB3L2, TRAF5  , XBP1   , YY1    , CNBP   , FRMD8  , KAT2B  , HNRNPLL, QKI    , EIF2AK3, CD40   , PPM1F  , KDM4A  , CTIF
11    RAD50   , CDK9    , CCT4    , CTCF    , BAZ2A   , BAZ1A   , SDE2    , PTK2B   , PSME4   , ZMYND8  , RNASEH1 , ZBTB38  , REPIN1  , HNRNPA1 , ID3     , ISG20   , NUGGC   , MYO18A  , NASP    , ZBTB7A  , UCHL5   , FBXW7   , SLF2    , PRKCD   , WRNIP1  , BACH1   , ARID1B  , TCF3    , UBE2B   , VCP     , YY1     , CNBP    , RNASEH2B, PARP9   , KAT2B   , MBD4    , HELB    , CD40    , CDC34
12    SEMA4D  , RGS14   , ARHGAP42, PTK2B   , TBC1D9B , RAP1GAP2, TBC1D9  , CORO1C  , NEDD9   , NF1     , DOCK10  , RALGAPA2, PREX1   , RALGDS  , RGS1    , SIPA1   , CD40    , USP6NL  , RAPGEF5
13    ARPC2  , CDK6   , PTK2B  , FGA    , FGG    , CORO1C , NEDD9  , NF1    , PREX1  , PTPRJ  , RAC2   , BCL2   , RREB1  , SDC4   , ST6GAL1, TLN1   , UTRN   , PPM1F
14    UBE2E3, RNF126, PELI1 , RNF213, TRAF3 , TRAF5 , UBE2B , UBE2G1
15    CDK6     , IKZF1    , CSK      , ELF4     , PTK2B    , TNFRSF13B, FOXP1    , STOML2   , TICAM2   , INPP5D   , IRF1     , IRF4     , LYN      , NEDD9    , NFATC2   , PRDX1    , ZBTB7B   , ZBTB7A   , PIK3CG   , PLCG2    , POU2AF1  , DOCK10   , PRKCD    , PELI1    , ZMIZ1    , ARID1B   , PREX1    , PTPRJ    , RAC2     , BCL2     , BCL3     , BID      , SDC4     , PRDM1    , VSIR     , SP3      , TCF3     , XBP1     , YY1      , CASP3    , AP3D1    , CD27     , CD40     , RIPOR2
16    TANK    , SH2D3C  , TXNIP   , RGS14   , AKAP13  , CHML    , ARHGAP42, DENND5B , DMPK    , FGD2    , RASA3   , DENND3  , CARD8   , TBC1D9B , RAP1GAP2, TBC1D9  , PSME4   , RABGAP1 , TNFAIP8 , CYTH4   , KRAS    , ARHGAP4 , CCDC88C , MYO9B   , NF1     , UCHL5   , SERPINB6, ELP3    , MOB1A   , FBXW7   , DOCK10  , PRKCD   , WRNIP1  , RALGAPA2, PREX1   , RAC2    , RALGDS  , RGS1    , VSIR    , SIPA1   , VCP     , CASP3   , PARP9   , HPS4    , ARHGEF1 , CYTH1   , CD27    , SH3BP5  , PSMF1   , GMFG    , USP6NL  , RAPGEF5 , ELMO1
17    CDK6   , IKZF1  , GAB3   , EVI2B  , PTK2B  , FOXP1  , HCLS1  , INPP5D , IREB2  , IRF1   , IRF4   , LYN    , NEDD9  , NF1    , ZBTB7B , ZBTB7A , PLCG2  , POU2AF1, FBXW7  , DOCK10 , ZMIZ1  , ARID1B , PREX1  , PTPRJ  , BCL2   , BCL3   , PRDM1  , VSIR   , SP3    , TCF3   , XBP1   , YY1    , LRRK1  , CBFA2T3, AP3D1  , CD27
18    TANK     , SH2D3C   , RAD50    , CDK9     , TNIP1    , SEMA4D   , RGS14    , BAZ2A    , AKAP13   , U2AF2    , CSK      , ENG      , PTK2B    , FGD2     , CORO1C   , PDCD4    , HIPK2    , HCLS1    , KRAS     , LYN      , CCDC88C  , NAB2     , NEDD9    , NF1      , PECAM1   , PIK3CG   , PLCG2    , NDFIP2   , RASIP1   , MOB1A    , FBXW7    , PRR5     , PRKCD    , PELI1    , ZMIZ1    , PTBP1    , ARRDC3   , PTPN1    , PTPRJ    , BCL2     , SDC4     , UBE2B    , VCP      , DERL1    , LRRK1    , CASP3    , PARP9    , GLYR1    , TNFRSF10B, KAT2B    , CCND2    , ACVR1    , EIF2AK3  , SH3BP5   , CD40     , PPM1F    , HERPUD1
19    SEMA4D, PTK2B , HCLS1 , LYN   , NEDD9 , PECAM1, PLCG2 , FBXW7 , PTPN1 , PTPRJ , LRRK1 , PARP9 , ACVR1 , CD40
20    TANK     , SH2D3C   , RAD50    , TNIP1    , SEMA4D   , BAZ2A    , AKAP13   , CSK      , ENG      , PTK2B    , FGD2     , HIPK2    , HCLS1    , KRAS     , LYN      , NAB2     , NEDD9    , PECAM1   , PIK3CG   , PLCG2    , NDFIP2   , MOB1A    , FBXW7    , PRR5     , PRKCD    , PELI1    , PTBP1    , ARRDC3   , PTPN1    , PTPRJ    , BCL2     , SDC4     , VCP      , DERL1    , LRRK1    , PARP9    , GLYR1    , TNFRSF10B, CCND2    , ACVR1    , CD40
21    CD99    , RNF14   , PSME4   , CLEC2D  , RNF126  , PVR     , CDC34   , CD40    , NFATC2  , CSK     , FBXW7   , RNF130  , SEC24A  , UBE2B   , PLCG1   , VASP    , PSMF1   , KLC1    , RAP1B   , CDC16   , NECTIN2 , RAP1GAP2, UBE2G1  , KRAS    , PTPRJ   , SEC24D  , ORAI2   , CYBB    , INPP5D  , UBE2E3  , FGG     , FGA     , SPSB1   , RNF213  , PRR5    , PLCG2   , UBE2J1  , SIPA1   , LYN
22    RAD50  , CDK9   , BAZ1A  , SDE2   , RNASEH1, ZBTB38 , REPIN1 , ID3    , NUGGC  , NASP   , UCHL5  , WRNIP1 , YY1    , HELB   , CDC34
23    BAZ2A   , CBX3    , PSME4   , CBX6    , ZMYND8  , JARID2  , LYN     , PLCG2   , ZFAND6  , VCP     , GLYR1   , ANKRD13A, KDM4A
24    ARPC1B , ARPC2  , PDLIM5 , RGS14  , AKAP13 , PTK2B  , FGD2   , FLNB   , CORO1C , CCDC69 , RND1   , ANK3   , HCLS1  , KPNB1  , KRAS   , ARHGAP4, MYO18A , MKLN1  , CCDC88C, MYO1C  , NEDD9  , NF1    , CHMP3  , SSH1   , PRR5   , PRKCD  , CORO1B , PREX1  , PTPN1  , NECTIN2, RAC2   , BCL2   , SDC4   , SIPA1  , TLN1   , UBE2B  , VASP   , VCP    , WIPF1  , FMNL1  , RAE1   , SSH2   , KAT2B  , LIMD1  , GMFG   , PPM1F  , ELMO1
25    ARPC1B , ARPC2  , PDLIM5 , AKAP13 , PTK2B  , FGD2   , FLNB   , CORO1C , RND1   , HCLS1  , KRAS   , MYO18A , MKLN1  , CCDC88C, MYO1C  , MYO9B  , NEDD9  , NF1    , SSH1   , PRKCD  , CORO1B , PREX1  , PTPN1  , RAC2   , BCL2   , SDC4   , TLN1   , VASP   , WIPF1  , FMNL1  , SSH2   , GMFG   , PPM1F  , ELMO1
26    RAD50  , CDK6   , IKZF1  , SEMA4D , TXNIP  , CTCF   , CCDC85B, BAZ2A  , CBX3   , U2AF2  , ELK3   , CBX6   , ZMYND8 , ZBTB38 , FOXP1  , PDCD4  , HIPK2  , HCLS1  , HNRNPA1, ID3    , FOXK2  , IRF1   , IRF2   , JARID2 , MBD1   , NAB2   , NFATC2 , ZBTB7B , ZBTB7A , BCL11A , POU2F1 , TENT5C , RESF1  , BACH1  , PTBP1  , ZNF608 , BCL3   , RREB1  , PRDM1  , SP3    , TCF3   , TRAF5  , YY1    , CNBP   , PARP9  , ARID5B , CBFA2T3, KAT2B  , LIMD1  , RPS6KA5, HELB   , NFE2L3 , PPM1F  , KDM4A
27    CDK6     , IKZF1    , CSK      , DGKH     , ELF4     , PTK2B    , FGA      , FGG      , TNFRSF13B, SHPK     , FOXP1    , STOML2   , TICAM2   , INPP5D   , IRF1     , IRF4     , MYO18A   , LYN      , NEDD9    , NFATC2   , PRDX1    , ZBTB7B   , ZBTB7A   , PIK3CG   , PLCG2    , POU2AF1  , DOCK10   , PRKCD    , PELI1    , ZMIZ1    , ARID1B   , PREX1    , PTPRJ    , NECTIN2  , RAC2     , BCL2     , BCL3     , SAA1     , BID      , SDC4     , PRDM1    , SELPLG   , VSIR     , SP3      , TCF3     , TLN1     , XBP1     , YY1      , CASP3    , AP3D1    , CD27     , CD40     , RIPOR2
28    RABGAP1 , EPN1    , EXOC1   , SCFD1   , CYTH4   , HPS4    , DENND3  , CYTH1   , MAN1A1  , SEC24A  , CHMP3   , GGA3    , KLC1    , GNS     , RAB30   , VPS37B  , RAB5A   , USP6NL  , SEC24D  , ANK3    , ARPC2   , DENND5B , TRAPPC12, GOLGB1  , COPG1   , ACBD3   , FNBP1   , RALGAPA2, MYO1C   , MAN1A2  , CHML    , TXNDC5
29    PTK2B    , TNFRSF13B, INPP5D   , LYN      , NFATC2   , ZBTB7A   , PLCG2    , POU2AF1  , DOCK10   , PRKCD    , PELI1    , PTPRJ    , BCL2     , BCL3     , SP3      , TCF3     , XBP1     , YY1      , CASP3    , CD27     , CD40
30    TANK    , SH2D3C  , SEMA4D  , RGS14   , AKAP13  , CHML    , ARHGAP42, CMTM8   , DENND5B , FGD2    , RASA3   , DENND3  , CARD8   , TBC1D9B , RAP1GAP2, TBC1D9  , PSME4   , RABGAP1 , CYTH4   , KRAS    , ARHGAP4 , CCDC88C , MYO9B   , NF1     , MOB1A   , FBXW7   , DOCK10  , PRKCD   , WRNIP1  , RALGAPA2, PREX1   , RALGDS  , RGS1    , VSIR    , SIPA1   , DNAJC7  , VCP     , CASP3   , HPS4    , STBD1   , ARHGEF1 , CYTH1   , SH3BP5  , GMFG    , USP6NL  , RAPGEF5 , ELMO1
⋮     ⋮
11007
11008
11009
11010
11011
11012
11013
11014
11015
11016
11017
11018
11019
11020
11021
11022
11023
11024
11025
11026
11027
11028
11029
11030
11031
11032
11033
11034
11035
11036

In [26]:
fora(pathways=all_pathways, genes=spec.genes, universe=all.genes, minSize = 1, maxSize = Inf)

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”

     pathway
1    GOBP_POSITIVE_REGULATION_OF_PEPTIDYL_TYROSINE_PHOSPHORYLATION
2    GOBP_PEPTIDYL_TYROSINE_MODIFICATION
3    GOBP_REGULATION_OF_PEPTIDYL_TYROSINE_PHOSPHORYLATION
4    GOBP_LEUKOCYTE_DIFFERENTIATION
5    GOBP_NEUTROPHIL_EXTRAVASATION
6    GOBP_LYMPHOCYTE_ACTIVATION
7    GOBP_REGULATION_OF_LOCOMOTION
8    GOBP_REGULATION_OF_CELL_ADHESION
9    GOBP_POSITIVE_REGULATION_OF_PROTEIN_MODIFICATION_PROCESS
10   GOBP_REGULATION_OF_MAP_KINASE_ACTIVITY
11   GOBP_DNA_METABOLIC_PROCESS
12   GOBP_B_CELL_DIFFERENTIATION
13   KEGG_FC_GAMMA_R_MEDIATED_PHAGOCYTOSIS
14   GOBP_MATURE_B_CELL_DIFFERENTIATION_INVOLVED_IN_IMMUNE_RESPONSE
15   GOBP_NEUTROPHIL_MIGRATION
16   GOBP_POSITIVE_REGULATION_OF_MOLECULAR_FUNCTION
17   GOBP_REGULATION_OF_CELL_CYCLE
18   GOBP_LOCOMOTION
19   GOBP_MONONUCLEAR_CELL_DIFFERENTIATION
20   GOBP_REGULATION_OF_PROTEIN_MODIFICATION_PROCESS
21   GOBP_POSITIVE_REGULATION_OF_PROTEIN_METABOLIC_PROCESS
22   GOBP_POSITIVE_REGULATION_OF_GENE_EXPRESSION
23   GOBP_REGULATION_OF_ENDOPLASMIC_RETICULUM_STRESS_INDUCED_INTRINSIC_APOPTOTIC_SIGNALING_PATHWAY
24   GOBP_NEGATIVE_REGULATION_OF_MULTICELLULAR_ORGANISMAL_PROCESS
25   GOBP_POSITIVE_REGULATION_OF_NEUTROPHIL_MIGRATION
26   GOBP_CELL_ADHESION
27   GOBP_POSITIVE_REGULATION_OF_PHOSPHORYLATION
28   GOBP_PROTEIN_LOCALIZATION_TO_CHROMOSOME
29   GOBP_GRANULOCYTE_MIGRATION
30   GOBP_REGULATION_OF_CELL_SUBSTRATE_ADHESION
⋮    ⋮
8756 GOBP_REGULATION_OF_ATP_BIOSYNTHETIC_PROCESS
8757 GOBP_NEGATIVE_REGULATION_OF_ATP_BIOSYNTHETIC_PROCESS
8758 GOBP_POSITIVE_REGULATION_OF_ATP_BIOSYNTHETIC_PROCESS
8759 GOBP_REGULATION_OF_DENDRITIC_CELL_DIFFERENTIATION
8760 GOBP_POSITIVE_REGULATION_OF_DENDRITIC_CELL_DIFFERENTIATION
8761 GOBP_REGULATION_OF_NEURON_MIGRATION
8762 GOBP_POSITIVE_REGULATION_OF_NEURON_MIGRATION
8763 GOBP_REGULATION_OF_CHLORIDE_TRANSPORT
8764 GOBP_POSITIVE_REGULATION_OF_EXTRINSIC_APOPTOTIC_SIGNALING_PATHWAY
8765 GOBP_NEGATIVE_REGULATION_OF_CHROMOSOME_ORGANIZATION
8766 GOBP_REGULATION_OF_STORE_OPERATED_CALCIUM_ENTRY
8767 GOBP_NEGATIVE_REGULATION_OF_CATION_CHANNEL_ACTIVITY
8768 GOBP_REGULATION_OF_CYSTEINE_TYPE_ENDOPEPTIDASE_ACTIVITY_INVOLVED_IN_APOPTOTIC_SIGNALING_PATHWAY
8769 GOBP_NEGATIVE_REGULATION_OF_CYSTEINE_TYPE_ENDOPEPTIDASE_ACTIVITY_INVOLVED_IN_APOPTOTIC_SIGNALING_PATHWAY
8770 GOBP_POSITIVE_REGULATION_OF_CYSTEINE_TYPE_ENDOPEPTIDASE_ACTIVITY_INVOLVED_IN_APOPTOTIC_SIGNALING_PATHWAY
8771 GOBP_REGULATION_OF_CYSTEINE_TYPE_ENDOPEPTIDASE_ACTIVITY_INVOLVED_IN_EXECUTION_PHASE_OF_APOPTOSIS
8772 GOBP_REGULATION_OF_UNSATURATED_FATTY_ACID_BIOSYNTHETIC_PROCESS
8773 GOBP_POSITIVE_REGULATION_OF_UNSATURATED_FATTY_ACID_BIOSYNTHETIC_PROCESS
8774 GOBP_REGULATION_OF_CAVEOLIN_MEDIATED_ENDOCYTOSIS
8775 GOBP_MALONYL_COA_METABOLIC_PROCESS
8776 HALLMARK_NOTCH_SIGNALING
8777 HALLMARK_MYOGENESIS
8778 HALLMARK_HEDGEHOG_SIGNALING
8779 HALLMARK_MYC_TARGETS_V2
8780 HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION
8781 HALLMARK_FATTY_ACID_METABOLISM
8782 HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY
8783 HALLMARK_UV_RESPONSE_DN
8784 HALLMARK_BILE_ACID_METABOLISM
8785 HALLMARK_SPERMATOGENESIS
     pval         padj       overlap size
1    7.133223e-06 0.06266536 12       28
2    6.767914e-05 0.15854957 14       44
3    7.324992e-05 0.15854957 12       34
4    9.216047e-05 0.15854957 25      112
5    1.100201e-04 0.15854957  4        4
6    1.193819e-04 0.15854957 29      141
7    1.391781e-04 0.15854957 24      108
8    1.531889e-04 0.15854957 23      102
9    1.624298e-04 0.15854957 24      109
10   2.481700e-04 0.17705027  9       23
11   2.646117e-04 0.17705027 26      126
12   2.885529e-04 0.17705027 13       44
13   3.079982e-04 0.17705027  8       19
14   3.310801e-04 0.17705027  6       11
15   3.310801e-04 0.17705027  6       11
16   3.538218e-04 0.17705027 31      164
17   3.894594e-04 0.17705027 24      115
18   3.938312e-04 0.17705027 25      122
19   4.061650e-04 0.17705027 21       95
20   4.253458e-04 0.17705027 32      173
21   4.253458e-04 0.17705027 32      173
22   4.433814e-04 0.17705027 27      137
23   4.796042e-04 0.17765573  5        8
24   4.923925e-04 0.17765573 22      103
25   5.055655e-04 0.17765573  4        5
26   5.666512e-04 0.18349298 27      139
27   5.721959e-04 0.18349298 19       84
28   6.057253e-04 0.18349298  6       12
29   6.057253e-04 0.18349298  6       12
30   7.196717e-04 0.21074385  9       26
⋮    ⋮            ⋮          ⋮       ⋮
8756 1            1          0        5
8757 1            1          0        1
8758 1            1          0        2
8759 1            1          0        2
8760 1            1          0        2
8761 1            1          0        1
8762 1            1          0        1
8763 1            1          0        1
8764 1            1          0        6
8765 1            1          0        8
8766 1            1          0        1
8767 1            1          0        4
8768 1            1          0        3
8769 1            1          0        1
8770 1            1          0        2
8771 1            1          0        1
8772 1            1          0        1
8773 1            1          0        1
8774 1            1          0        1
8775 1            1          0        1
8776 1            1          0        2
8777 1            1          0       15
8778 1            1          0        4
8779 1            1          0        8
8780 1            1          0       13
8781 1            1          0       21
8782 1            1          0        5
8783 1            1          0       11
8784 1            1          0       10
8785 1            1          0        3
     overlapGenes
1    SEMA4D, PTK2B , LYN   , NEDD9 , PECAM1, PLCG2 , FBXW7 , PTPN1 , PTPRJ , LRRK1 , PARP9 , CD40
2    SEMA4D, CSK   , PTK2B , HIPK2 , LYN   , NEDD9 , PECAM1, PLCG2 , FBXW7 , PTPN1 , PTPRJ , LRRK1 , PARP9 , CD40
3    SEMA4D, PTK2B , LYN   , NEDD9 , PECAM1, PLCG2 , FBXW7 , PTPN1 , PTPRJ , LRRK1 , PARP9 , CD40
4    IKZF1  , EVI2B  , PTK2B  , INPP5D , IRF1   , IRF4   , LYN    , NEDD9  , ZBTB7A , PLCG2  , POU2AF1, FBXW7  , DOCK10 , ARID1B , PTPRJ  , BCL2   , BCL3   , PRDM1  , VSIR   , TCF3   , XBP1   , YY1    , LRRK1  , AP3D1  , CD27
5    CD99  , PECAM1, PIK3CG, RIPOR2
6    IKZF1    , CSK      , PTK2B    , TNFRSF13B, STOML2   , INPP5D   , IRF1     , IRF4     , LYN      , NEDD9    , ZBTB7A   , PIK3CG   , PLCG2    , POU2AF1  , DOCK10   , ARID1B   , PTPRJ    , RAC2     , BCL2     , BCL3     , PRDM1    , VSIR     , TCF3     , XBP1     , YY1      , AP3D1    , CD27     , CD40     , RIPOR2
7    PLXNC1 , SEMA4D , PTK2B  , ZMYND8 , LYN    , CD99   , NEDD9  , PECAM1 , PIK3CG , PLCG2  , FBXW7  , DOCK10 , CAMK1D , ARRDC3 , PTPRJ  , RAC2   , BCL2   , RREB1  , VSIR   , ST6GAL1, XBP1   , CHST2  , CD40   , RIPOR2
8    ARPC2  , PLXNC1 , SEMA4D , CSK    , PTK2B  , IRF1   , LYN    , NEDD9  , PIK3CG , ARID1B , PTPRJ  , RAC2   , BCL2   , RREB1  , VSIR   , ST6GAL1, UTRN   , XBP1   , AP3D1  , CYTH1  , CD27   , CHST2  , RIPOR2
9    TNIP1 , SEMA4D, BAZ2A , CSK   , PTK2B , FGD2  , HIPK2 , LYN   , NEDD9 , PECAM1, PIK3CG, PLCG2 , MOB1A , FBXW7 , ARRDC3, PTPN1 , PTPRJ , BCL2  , DERL1 , LRRK1 , PARP9 , GLYR1 , CCND2 , CD40
10   CSK   , PTK2B , FGD2  , PDCD4 , LYN   , PIK3CG, PTPN1 , PTPRJ , CD40
11   CDK9    , CCT4    , CTCF    , BAZ2A   , SDE2    , PTK2B   , ZMYND8  , RNASEH1 , REPIN1  , ID3     , ISG20   , NUGGC   , ZBTB7A  , UCHL5   , FBXW7   , BACH1   , ARID1B  , TCF3    , UBE2B   , YY1     , CNBP    , RNASEH2B, PARP9   , KAT2B   , MBD4    , CD40
12   PTK2B  , INPP5D , ZBTB7A , PLCG2  , POU2AF1, DOCK10 , PTPRJ  , BCL2   , BCL3   , TCF3   , XBP1   , YY1    , CD27
13   VASP  , ARPC1B, PLCG2 , INPP5D, RAC2  , ARPC2 , PIK3CG, LYN
14   PTK2B  , PLCG2  , POU2AF1, DOCK10 , BCL3   , XBP1
15   CD99  , PECAM1, PIK3CG, CAMK1D, RAC2  , RIPOR2
16   CDK9   , SEMA4D , CCT4   , CSK    , PTK2B  , FGD2   , CARD8  , TBC1D9 , HIPK2  , IRF4   , LYN    , NEDD9  , ZBTB7A , PIK3CG , PLCG2  , FBXW7  , DOCK10 , CAMK1D , ARRDC3 , PTPN1  , BCL2   , VSIR   , TCF3   , DERL1  , NCOA3  , PARP9  , CCND2  , EIF2AK3, CD40   , USP6NL , RIPOR2
17   CDK9    , CTCF    , PIM2    , SDE2    , EVI2B   , HIPK2   , ID3     , IRF1    , NUGGC   , CDK17   , UCHL5   , PLCG2   , FBXW7   , ARID1B  , BCL2    , BCL2L1  , UBE2B   , YY1     , RNASEH2B, PARP9   , KAT2B   , CCND2   , TP53I13 , CABLES1
18   PLXNC1 , SEMA4D , PTK2B  , ZMYND8 , LYN    , CD99   , NEDD9  , PECAM1 , PIK3CG , PLCG2  , FBXW7  , DOCK10 , CAMK1D , ARRDC3 , PTPRJ  , RAC2   , BCL2   , RREB1  , VSIR   , ST6GAL1, VASP   , XBP1   , CHST2  , CD40   , RIPOR2
19   IKZF1  , PTK2B  , INPP5D , IRF1   , IRF4   , LYN    , ZBTB7A , PLCG2  , POU2AF1, DOCK10 , ARID1B , PTPRJ  , BCL2   , BCL3   , PRDM1  , VSIR   , TCF3   , XBP1   , YY1    , AP3D1  , CD27
20   CDK9   , TNIP1  , SEMA4D , BAZ2A  , U2AF2  , CSK    , PTK2B  , FGD2   , PDCD4  , HIPK2  , LYN    , CCDC88C, NEDD9  , PECAM1 , PIK3CG , PLCG2  , MOB1A  , FBXW7  , ARRDC3 , PTPN1  , PTPRJ  , BCL2   , UBE2B  , DERL1  , LRRK1  , PARP9  , GLYR1  , KAT2B  , CCND2  , EIF2AK3, CD40   , HERPUD1
21   TNIP1  , SEMA4D , BAZ2A  , CSK    , EEF2   , F12    , PTK2B  , FGD2   , CARD8  , HIPK2  , LYN    , NEDD9  , PECAM1 , PIK3CG , PLCG2  , MOB1A  , FBXW7  , ARRDC3 , PTPN1  , PTPRJ  , BCL2   , BCL3   , VSIR   , CNBP   , DERL1  , LRRK1  , PARP9  , GLYR1  , CCND2  , EIF2AK3, CD40   , HERPUD1
22   CTCF   , U2AF2  , EEF2   , F12    , PTK2B  , CARD8  , STOML2 , ID3    , IRF1   , IRF4   , PIK3CG , PLCG2  , POU2AF1, TENT5C , ARID1B , PTPRJ  , BCL3   , PRDM1  , VSIR   , CREB3L2, XBP1   , YY1    , CNBP   , KAT2B  , QKI    , EIF2AK3, CD40
23   PTPN1  , BCL2L1 , XBP1   , EIF2AK3, HERPUD1
24   SEMA4D   , CSK      , F12      , PTK2B    , CHSY1    , CARD8    , TNFRSF13B, PDCD4    , INPP5D   , IRF1     , JARID2   , LYN      , PIK3CG   , ACP5     , FBXW7    , ARRDC3   , BCL2     , BCL3     , VSIR     , YY1      , EIF2AK3  , RIPOR2
25   CD99  , CAMK1D, RAC2  , RIPOR2
26   ARPC2  , PLXNC1 , TNIP1  , SEMA4D , CSK    , PTK2B  , IRF1   , LYN    , CD99   , MKLN1  , NEDD9  , PECAM1 , PIK3CG , ARID1B , PTPRJ  , RAC2   , BCL2   , RREB1  , VSIR   , ST6GAL1, UTRN   , XBP1   , AP3D1  , CYTH1  , CD27   , CHST2  , RIPOR2
27   SEMA4D, CSK   , PTK2B , FGD2  , HIPK2 , LYN   , NEDD9 , PECAM1, PIK3CG, PLCG2 , MOB1A , FBXW7 , PTPN1 , PTPRJ , BCL2  , LRRK1 , PARP9 , CCND2 , CD40
28   CDK9    , CCT4    , CTCF    , ZMYND8  , JARID2  , TRAPPC12
29   CD99  , PECAM1, PIK3CG, CAMK1D, RAC2  , RIPOR2
30   ARPC2  , PTK2B  , NEDD9  , PTPRJ  , RAC2   , BCL2   , RREB1  , ST6GAL1, UTRN
⋮    ⋮
8756
8757
8758
8759
8760
8761
8762
8763
8764
8765
8766
8767
8768
8769
8770
8771
8772
8773
8774
8775
8776
8777
8778
8779
8780
8781
8782
8783
8784
8785

In [80]:
set.seed(999)
all.paths.res <- data.frame()

for (cell in c('B','Cholangiocyte','Endothelial','Hepatocytes','HSC','Mast','Myeloid','NK','Schwann','T')) {
    spec.genes <- unique(filter(spec.links, celltype==cell)$Gene)
    all.genes <- unique(all.links$gene)
    
    spec.genes <- spec.genes[!spec.genes %in% rps$Approved.symbol]
    all.genes <- all.genes[!all.genes %in% rps$Approved.symbol]
    
    res <- fora(pathways=all_pathways, genes=spec.genes, universe=all.genes, minSize = 1, maxSize = Inf)
    res$overlapGenes <- sapply(res$overlapGenes, function(x) paste(unlist(x), collapse=','))
    
    write.table(res, paste0('/nfs/lab/tscc/welison/FNIH.Liver/03_ABC/',cell,'_fGSEA.fora_specific_links.tsv'),
                   sep='\t', col.names=TRUE, row.names=F, quote=F)
    
    filter(res, str_detect(pathway, 'GOBP')) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/03_ABC/',cell,'_fGSEA.fora_GO.BP_specific_links.tsv'),
                   sep='\t', col.names=TRUE, row.names=F, quote=F)
    
    res$cell <- cell
    all.paths.res <- rbind(all.paths.res, res)
    message(paste0(nrow(filter(res, padj < 0.05))), " significant pathways for ", cell)
}

dim(all.paths.res)
head(all.paths.res)

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”
67 significant pathways for B

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”
117 significant pathways for Cholangiocyte

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”
188 significant pathways for Endothelial

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”
401 significant pathways for Hepatocytes

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”
27 significant pathways for HSC

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”
0 significant pathways for Mast

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”
870 significant pathways for Myeloid

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”
0 significant pathways for NK

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”
0 significant pathways for Schwann

Warning message in fora(pathways = all_pathways, genes = spec.genes, universe = all.genes, :
“Not all of the input genes belong to the universe, such genes were removed”
0 significant pathways for T

[1] 110360      7

  pathway                                              pval         padj
1 GOBP_CELLULAR_RESPONSE_TO_STRESS                     1.634993e-07 0.001804378
2 GOBP_REGULATION_OF_INTRACELLULAR_SIGNAL_TRANSDUCTION 9.648580e-07 0.003851055
3 GOBP_REGULATION_OF_GTPASE_ACTIVITY                   1.139698e-06 0.003851055
4 REACTOME_CYTOKINE_SIGNALING_IN_IMMUNE_SYSTEM         1.669072e-06 0.003851055
5 GOBP_SMALL_GTPASE_MEDIATED_SIGNAL_TRANSDUCTION       2.208264e-06 0.003851055
6 GOBP_POSITIVE_REGULATION_OF_MOLECULAR_FUNCTION       2.211667e-06 0.003851055
  overlap size
1 75      709
2 72      701
3 25      147
4 42      334
5 31      214
6 62      585
  overlapGenes
1 TANK,SH2D3C,RAD50,CDK6,CDK9,ERLIN1,RGS14,CBX3,CYBB,BMT2,SDE2,PTK2B,ERP44,PSME4,ZMYND8,ZBTB38,FOXP1,SESN1,PDCD4,HIPK2,NPC1L1,STOML2,HNRNPA1,SCIMP,LYN,MAN1A1,CCDC88C,NF1,NFATC2,PRDX1,ZBTB7B,ZBTB7A,UCHL5,UBE2J1,PDK1,SERPINB6,SLC38A2,FBXW7,RNF126,SLF2,PRKCD,WRNIP1,BACH1,ZMIZ1,ARID1B,PTPN1,BCL2,BCL2L1,BCL3,BID,CREB3L2,SIPA1,TRAF3,TRAF5,DNAJC7,UBE2B,VCP,VDAC1,XBP1,YY1,DERL1,RNASEH2B,CASP3,CCM2,PARP9,LRRC8C,TNFRSF10B,KAT2B,MBD4,HELB,CD27,EIF2AK3,NFE2L3,HERPUD1,SUSD6
2 TANK,TNIP1,SEMA4D,RGS14,PIM2,AKAP13,ARHGAP42,CSK,BMT2,ENG,PTK2B,FGD2,FGA,FGG,RASA3,DENND3,CARD8,RAP1GAP2,SGMS1,CYTH4,SESN1,PDCD4,HIPK2,HCLS1,HINT1,TICAM2,KRAS,SCIMP,ARHGAP4,LYN,MYO9B,NF1,PRDX1,PIK3CG,PLCG2,ZFAND6,NDFIP2,RASIP1,FBXW7,PRR5,PRKCD,CDC42SE2,PELI1,RALGAPA2,PTBP1,ARRDC3,PREX1,PTPN1,PTPRJ,RAP1B,BCL2,BCL2L1,BCL3,BID,SIPA1,TRAF3,TRAF5,TRIP6,UBE2B,XBP1,RNASEH2B,LRRK1,TNFRSF10B,LIMD1,ARHGEF1,CYTH1,CD27,EIF2AK3,CD40,HERPUD1,RIPOR2,CDC34
3 PLXNC1,SEMA4D,RGS14,ARHGAP42,PTK2B,FGD2,RASA3,TBC1D9B,RAP1GAP2,TBC1D9,CORO1C,RABGAP1,NEDD9,NF1,RASIP1,DOCK10,RALGAPA2,PREX1,RALGDS,RGS1,SIPA1,CD40,USP6NL,RIPOR2,RAPGEF5
4 PSME4,PTPN18,CSF2RB,RPS6KA5,CD40,RAE1,CSK,PIK3CG,KPNB1,PTK2B,PLCG1,IRF1,PSMF1,RAP1B,TRAF3,NUP210,KRAS,FLNB,IRF4,CD27,POU2F1,GSTO1,PTPRJ,PDCD4,MX1,GAB3,PRKCD,CASP3,IRF2,INPP5D,BCL2L1,BCL2,ISG20,SAA1,PITPNA,MX2,IFITM2,PTPN1,PELI1,PLCG2,TNFRSF13B,LYN
5 SH2D3C,AKAP13,CHML,ARHGAP42,FGD2,RASA3,DENND3,RAP1GAP2,CYTH4,RND1,RAB30,KPNB1,KRAS,ARHGAP4,CCDC88C,MYO9B,NF1,PIK3CG,RASIP1,DOCK10,CDC42SE2,RALGAPA2,PREX1,RALGDS,RAP1B,SIPA1,ARHGEF1,CYTH1,RIPOR2,RAPGEF5,ELMO1
6 TANK,RAD50,CDK9,SEMA4D,CCT4,RGS14,AKAP13,ARHGAP42,CSK,PTK2B,FGD2,CARD8,TBC1D9B,RAP1GAP2,GRAMD4,TBC1D9,CORO1C,GNA15,ANK3,HIPK2,HCLS1,TICAM2,IRF4,LYN,NAB2,NEDD9,NF1,ZBTB7A,PIK3CG,PLCG2,FBXW7,DOCK10,PRKCD,CAMK1D,RALGAPA2,ARRDC3,PREX1,PTPN1,RALGDS,BCL2,RGS1,BID,SDC4,VSIR,SIPA1,TCF3,TRAF5,VCP,DERL1,NCOA3,PARP9,ARID5B,TNFRSF10B,CCND2,RPS6KA5,GSTO1,EIF2AK3,CD40,PPM1F,USP6NL,RIPOR2,RAPGEF5
  cell
1 B
2 B
3 B
4 B
5 B
6 B

In [81]:
write.table(all.paths.res, paste0('/nfs/lab/tscc/welison/FNIH.Liver/03_ABC/All_fGSEA.fora_specific_links.tsv'),
                   sep='\t', col.names=TRUE, row.names=F, quote=F)
    
    filter(all.paths.res, str_detect(pathway, 'GOBP')) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/03_ABC/All_fGSEA.fora_GO.BP_specific_links.tsv'),
                   sep='\t', col.names=TRUE, row.names=F, quote=F)

### Homer

In [84]:
for (cell in c('B','Cholangiocyte','Endothelial','Hepatocytes','HSC','Mast','Myeloid','NK','Schwann','T')) {
    spec.links %>% 
        filter(celltype==cell) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/03_ABC/',cell,'_specific_link_peaks.bed'),
                    col.names=F, row.names=F, quote=F, sep='\t')
}
all.links %>%
    write.table('/nfs/lab/tscc/welison/FNIH.Liver/03_ABC/All_link_peaks.bed',
                col.names=F, row.names=F, quote=F, sep='\t')

In [89]:
commands <- character()

for (cell in c('B','Cholangiocyte','Endothelial','Hepatocytes','HSC','Mast','Myeloid','NK','Schwann','T')) {
    commands <- c(commands, paste0('findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/',cell,
                 '_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.',
                 cell,'/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer'))
}

write.table(commands, '/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/241224_WE_specific_links_homer.txt',
           col.names=F, row.names=F, quote=F, sep='\t')

commands

 [1] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/B_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.B/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
 [2] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/Cholangiocyte_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.Cholangiocyte/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
 [3] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/Endothelial_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.Endothelial/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
 [4] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/Hepatocytes_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.Hepatocytes/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
 [5] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/HSC_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.HSC/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
 [6] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/Mast_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.Mast/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
 [7] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/Myeloid_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.Myeloid/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
 [8] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/NK_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.NK/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
 [9] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/Schwann_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.Schwann/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[10] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/T_specific_link_peaks.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.T/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/03_ABC/All_link_peaks.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"

In [4]:
read.table('/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/outs/241224_specific_links.Hepatocytes
/knownResults.txt')

                     Motif                               Name  Consensus
MA0761.2_ETV1        NNACAGGAAGTGNN                      1e-91 -209.80
MA1563.2_SOX18       AACAATDV                            1e-65 -150.50
MA1942.1_ETV2::FOXI1 BGTAAACAGGAAGYR                     1e-65 -150.40
MA0868.2_SOX8        AGAACAATRG                          1e-64 -149.60
MA0062.3_GABPA       NBCACTTCCTGTNN                      1e-60 -138.90
MA0077.1_SOX9        CCATTGTTY                           1e-54 -126.30
MA1508.1_IKZF1       RRAACAGGAARN                        1e-51 -119.40
MA1950.1_FLI1::FOXI1 RTAAACAGGAARYN                      1e-51 -117.90
MA1120.1_SOX13       DAACAATGGNN                         1e-50 -116.70
MA1953.1_FOXO1::ELF1 RTAAACAGGAAGTN                      1e-45 -105.40
MA1936.1_ERF::FOXO1  RTAAACAGGAAGBS                      1e-45 -104.90
MA1935.1_ERF::FOXI1  GTAAACMGGAAGTR                      1e-45 -104.90
MA1152.1_SOX15       CYATTGTTTT                          1e-45 -103.90
MA0640.2_ELF3        NNCCACTTCCTGNT                      1e-44 -102.70
MA1562.1_SOX14       CCGAACAATG                          1e-42  -98.92
MA0867.2_SOX4        GAACAAAGGV                          1e-41  -96.04
MA1947.1_ETV5::FOXO1 GTAAACAGGAWGT                       1e-40  -94.07
MA0143.4_SOX2        DWACAATGGNH                         1e-40  -94.00
MA0473.3_ELF1        RAVCAGGAAGTGVN                      1e-37  -86.19
MA1954.1_FOXO1::ELK1 RWMAACAGGAAGTR                      1e-32  -74.98
MA0598.3_EHF         NNCACTTCCTGTTNN                     1e-30  -69.54
MA1955.1_FOXO1::ELK3 RTMAACAGGAAGTN                      1e-29  -68.00
MA1946.1_ETV5::FOXI1 GTAAACAGGAAGT                       1e-27  -63.50
MA1952.1_FOXJ2::ELF1 RTAAACAGGAAGTR                      1e-26  -60.24
MA0766.2_GATA5       CWGATAASRV                          1e-26  -60.18
MA0076.2_ELK4        CCACTTCCGGY                         1e-23  -54.92
MA0750.2_ZBTB7A      NSCCGGAAGTGSV                       1e-22  -51.99
MA0036.3_GATA2       NYCTTATCTNH                         1e-22  -50.68
MA1956.1_FOXO1::FLI1 GTAAACAGGAAGTK                      1e-20  -48.09
MA0098.3_ETS1        ACCGGAAGTR                          1e-19  -44.23
⋮                    ⋮                                   ⋮     ⋮
MA0740.2_KLF14       GGGGCGGGG                           1     0
MA0806.1_TBX4        AGGTGTGA                            1     0
MA0684.2_RUNX3       NWAACCTCAANN                        1     0
MA1959.1_KLF7        DGGGCGGGG                           1     0
MA0772.1_IRF7        MCGAAAGCGAAAVT                      1     0
MA0493.2_KLF1        DGGGCGGGG                           1     0
MA0046.2_HNF1A       RRTTAATNATTAACH                     1     0
MA0803.1_TBX15       AGGTGTGA                            1     0
MA0738.1_HIC2        RTGCCCACB                           1     0
MA0499.2_MYOD1       NNGCACCTGTCNB                       1     0
MA1930.1_CTCF        CTGCAGTKCCNVCHNHYGGCCACYAGRKGGCRCYN 1     0
MA0522.3_TCF3        NVCACCTGCNN                         1     0
MA1648.1_TCF12       NNCACCTGCNN                         1     0
MA1631.1_ASCL1       NNGCACCTGCCNB                       1     0
MA1636.1_CEBPG       NDATGATGCAATMWH                     1     0
MA0102.4_CEBPA       NDATTGCACAATHN                      1     0
MA0139.1_CTCF        TGGCCACYAGGGGGCRCYA                 1     0
MA0836.2_CEBPD       DATTGCACAATHN                       1     0
MA0830.2_TCF4        NNGCACCTGCCNB                       1     0
MA0820.1_FIGLA       AMCACCTGKT                          1     0
MA0731.1_BCL6B       TGCTTTCTAGGAATTCM                   1     0
MA0735.1_GLIS1       AGACCCCCCACGAWGC                    1     0
MA0749.1_ZBED1       CTATCGCGACATA                       1     0
MA0752.1_ZNF410      TMCATCCCATAATAHTC                   1     0
MA0758.1_E2F7        TTTTCCCGCCAAAA                      1     0
MA0103.3_ZEB1        SNCACCTGCVS                         1     0
MA1558.1_SNAI1       DGCAGGTGYD                          1     0
MA1559.1_SNAI3       AACAGGTGCA                          1     0
MA0469.3_E2F3        RTTTTGGCGCCAAAAY                    1     0
MA0745.2_SNAI2       NYGCACCTGTMNY                       1     0
                     P.value Log  P.value.1 q.value X.Benjamini.
MA0761.2_ETV1        0       1178 50.30%    14304.1 30.17%
MA1563.2_SOX18       0        342 14.60%     2435.2 5.14%
MA1942.1_ETV2::FOXI1 0        736 31.43%     8033.8 16.95%
MA0868.2_SOX8        0        354 15.12%     2589.5 5.46%
MA0062.3_GABPA       0       1061 45.30%    13842.9 29.20%
MA0077.1_SOX9        0        266 11.36%     1786.5 3.77%
MA1508.1_IKZF1       0       1013 43.25%    13494.4 28.46%
MA1950.1_FLI1::FOXI1 0        643 27.46%     7216.6 15.22%
MA1120.1_SOX13       0        340 14.52%     2803.8 5.91%
MA1953.1_FOXO1::ELF1 0        547 23.36%     5968.7 12.59%
MA1936.1_ERF::FOXO1  0        556 23.74%     6118.1 12.91%
MA1935.1_ERF::FOXI1  0        787 33.60%     9907.4 20.90%
MA1152.1_SOX15       0        465 19.85%     4752.5 10.02%
MA0640.2_ELF3        0       1044 44.58%    14553.9 30.70%
MA1562.1_SOX14       0        168 7.17%       955.7 2.02%
MA0867.2_SOX4        0        525 22.42%     5823.6 12.28%
MA1947.1_ETV5::FOXO1 0        524 22.37%     5850.3 12.34%
MA0143.4_SOX2        0        286 12.21%     2402.0 5.07%
MA0473.3_ELF1        0        940 40.14%    13165.9 27.77%
MA1954.1_FOXO1::ELK1 0        519 22.16%     6218.5 13.12%
MA0598.3_EHF         0        939 40.09%    13726.9 28.95%
MA1955.1_FOXO1::ELK3 0        374 15.97%     4102.6 8.65%
MA1946.1_ETV5::FOXI1 0        429 18.32%     5064.6 10.68%
MA1952.1_FOXJ2::ELF1 0        597 25.49%     7940.2 16.75%
MA0766.2_GATA5       0        261 11.14%     2589.0 5.46%
MA0076.2_ELK4        0        674 28.78%     9464.8 19.96%
MA0750.2_ZBTB7A      0        657 28.05%     9271.2 19.56%
MA0036.3_GATA2       0        264 11.27%     2819.0 5.95%
MA1956.1_FOXO1::FLI1 0        246 10.50%     2607.4 5.50%
MA0098.3_ETS1        0        490 20.92%     6643.4 14.01%
⋮                    ⋮       ⋮    ⋮         ⋮       ⋮
MA0740.2_KLF14       1       588  25.11%    14073.9 29.69%
MA0806.1_TBX4        1       117  5.00%      3567.8 7.53%
MA0684.2_RUNX3       1       142  6.06%      4175.4 8.81%
MA1959.1_KLF7        1       652  27.84%    15486.6 32.67%
MA0772.1_IRF7        1        49  2.09%      1879.7 3.96%
MA0493.2_KLF1        1       634  27.07%    15203.9 32.07%
MA0046.2_HNF1A       1        17  0.73%       975.7 2.06%
MA0803.1_TBX15       1       106  4.53%      3403.0 7.18%
MA0738.1_HIC2        1       131  5.59%      4127.9 8.71%
MA0499.2_MYOD1       1       173  7.39%      5161.1 10.89%
MA1930.1_CTCF        1        87  3.71%      3053.2 6.44%
MA0522.3_TCF3        1        81  3.46%      2913.8 6.15%
MA1648.1_TCF12       1        97  4.14%      3393.7 7.16%
MA1631.1_ASCL1       1       202  8.63%      5985.1 12.62%
MA1636.1_CEBPG       1        44  1.88%      2145.2 4.52%
MA0102.4_CEBPA       1        51  2.18%      2379.5 5.02%
MA0139.1_CTCF        1       182  7.77%      5983.6 12.62%
MA0836.2_CEBPD       1        54  2.31%      2627.5 5.54%
MA0830.2_TCF4        1       164  7.00%      5655.7 11.93%
MA0820.1_FIGLA       1       136  5.81%      5032.7 10.62%
MA0731.1_BCL6B       1         0  0.00%         5.1 0.01%
MA0735.1_GLIS1       1         0  0.00%        10.4 0.02%
MA0749.1_ZBED1       1         0  0.00%         5.0 0.01%
MA0752.1_ZNF410      1         0  0.00%        27.1 0.06%
MA0758.1_E2F7        1         0  0.00%        32.7 0.07%
MA0103.3_ZEB1        1       131  5.59%      5993.2 12.64%
MA1558.1_SNAI1       1        87  3.71%      4196.8 8.85%
MA1559.1_SNAI3       1        62  2.65%      3254.1 6.86%
MA0469.3_E2F3        1         0  0.00%        11.9 0.03%
MA0745.2_SNAI2       1        56  2.39%      2895.9 6.11%