In [1]:
#always run this first!!
#essential reticulate functions that allow us to use python packages in R
#you'll need a conda env with 'leidenalg' and 'pandas' installed to do this
#then route reticulate to the python installed in that conda env with the below functions
Sys.setenv(RETICULATE_PYTHON="/home/welison/.conda/envs/decontX_reticulate/bin/python")
library(reticulate)
reticulate::use_python("/home/welison/.conda/envs/decontX_reticulate/bin/python")
reticulate::use_condaenv("/home/welison/.conda/envs/decontX_reticulate")
reticulate::py_module_available(module='leidenalg') #needs to be TRUE
reticulate::import('leidenalg') #good to make sure this doesn't error

Warning message:
“package ‘reticulate’ was built under R version 4.3.3”

[1] TRUE

Module(leidenalg)

In [3]:
#is you get messages that any of these packages aren't installed
#go ahead and locally install them yourself using install.packages()

#library(GenomeInfoDb,lib.loc="/nfs/lab/welison/multiome_practice/lib/")

suppressMessages(library(hdf5r))
suppressMessages(library(Seurat))
suppressMessages(library(Signac))
suppressMessages(library(EnsDb.Hsapiens.v86))
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
suppressMessages(library(Matrix))
#install.packages('harmony')
suppressMessages(library(harmony))
suppressMessages(library(data.table))
#suppressMessages(library(ggpubr))
library(gridExtra)
warnLevel <- getOption('warn')
options(warn = -1)
library(BPCells)
library(stringr)
library(soupx)

Warning message:
“package ‘Seurat’ was built under R version 4.3.3”
Warning message:
“package ‘sp’ was built under R version 4.3.3”

ERROR: Error: package or namespace load failed for ‘Signac’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/welison/.conda/envs/mamba/envs/seurat5.0_decontx/lib/R/library/Rsamtools/libs/Rsamtools.so':
  /home/welison/.conda/envs/decontX_reticulate/lib/python3.10/lib-dynload/../../libcrypto.so.3: version `OPENSSL_3.3.0' not found (required by /home/welison/.conda/envs/mamba/envs/seurat5.0_decontx/lib/./libssl.so.3)

In [ ]:
sessionInfo()

In [ ]:
library(RhpcBLASctl)
RhpcBLASctl::blas_set_num_threads(24)

In [5]:
pool1_rds_dir <- '/nfs/lab/projects/nash_nafld_liver/pipeline_output/'
pool2_rds_dir <- '/nfs/lab/scorban/fnih_liver_231110/demuxlet_results/results1Mvariants/'
pool3_4_rds_dir <- '/nfs/lab/projects/nash_nafld_liver/sample_qc/'

In [6]:
pool1_samples <- c('MM_1341_1_2_MM_1337_1_2', 'MM_1342_1_2_MM_1338_1_2', 
                   'MM_1343_1_2_MM_1339_1_2',  'MM_1344_1_2_MM_1340_1_2')
pool2_samples <- c('QY_2270_2_QY_2269_2', 'QY_2272_2_QY_2271_2', 
                   'QY_2274_1_2_QY_2273_1_2', 'QY_2276_2_QY_2275_2', 
                   'QY_2278_2_QY_2277_2', 'QY_2280_2_QY_2279_2', 
                   'QY_2282_2_QY_2281_2', 'QY_2284_1_2_QY_2283_1_2')  
pool3_4_samples <- c('QY_2380_2_QY_2379_2', 'QY_2382_2_QY_2381_2', 
                     'QY_2384_1_2_QY_2383_1_2', 'QY_2386_2_QY_2385_2', 
                     'QY_2388_2_QY_2387_2', 'QY_2390_2_QY_2389_2', 
                     'QY_2392_2_QY_2391_2', 'QY_2394_1_2_QY_2393_1_2', 
                     'QY_2396_1_2_QY_2395_1_2', 'QY_2398_2_QY_2397_2', 
                     'QY_2400_2_QY_2399_2', 'QY_2402_2_QY_2401_2', 
                     'QY_2404_1_2_QY_2403_1_2', 'QY_2406_2_QY_2405_2', 
                     'QY_2408_2_QY_2407_2', 'QY_2410_2_QY_2409_2')

In [10]:
paste0(pool1_rds_dir, pool1_samples[1], '/intermediate_filtered.rds')

[1] "/nfs/lab/projects/nash_nafld_liver/pipeline_output/MM_1341_1_2_MM_1337_1_2/intermediate_filtered.rds"

In [11]:
adata_1 <- readRDS(paste0(pool1_rds_dir, pool1_samples[1], '/intermediate_filtered.rds'))
adata_1

An object of class Seurat
235602 features across 13865 samples within 3 assays
Active assay: ATAC (170783 features, 170783 variable features)
 2 layers present: counts, data
 2 other assays present: RNA, SCT
 5 dimensional reductions calculated: pca, umap.rna, lsi, umap.atac, umap.wnn

In [12]:
adata_2 <- readRDS(paste0(pool2_rds_dir, pool2_samples[1], '/intermediate_filtered.rds'))
adata_2

An object of class Seurat
187988 features across 20058 samples within 3 assays
Active assay: ATAC (122998 features, 122998 variable features)
 2 layers present: counts, data
 2 other assays present: RNA, SCT
 5 dimensional reductions calculated: pca, umap.rna, lsi, umap.atac, umap.wnn

In [13]:
adata_3 <- readRDS(paste0(pool3_4_rds_dir, pool3_4_samples[1], '/intermediate_filtered.rds'))
adata_3

An object of class Seurat
219755 features across 23040 samples within 3 assays
Active assay: ATAC (153684 features, 153684 variable features)
 2 layers present: counts, data
 2 other assays present: RNA, SCT
 5 dimensional reductions calculated: pca, umap.rna, lsi, umap.atac, umap.wnn

In [5]:
adata <- readRDS('/nfs/lab/projects/nash_nafld_liver/downstream_all/06052024_fnih_liver_ALL28lanes_ALL87donors_50kHVWsby16pool_HarmonyCovariates_DonorDemuxAndPoolingBatch_filtered.rds')
adata

An object of class Seurat
157583 features across 425551 samples within 4 assays
Active assay: windows (50000 features, 50000 variable features)
 2 layers present: counts, data
 3 other assays present: RNA, RNA_raw, SCT
 7 dimensional reductions calculated: pca, harmony.rna, umap.rna, lsi, harmony.atac, umap.atac, umap.wnn

In [7]:
int_rds <- readRDS('/nfs/lab/projects/nash_nafld_liver/sample_qc/QY_2380_2_QY_2379_2/intermediate_filtered.rds')
int_rds

An object of class Seurat
219755 features across 23040 samples within 3 assays
Active assay: ATAC (153684 features, 153684 variable features)
 2 layers present: counts, data
 2 other assays present: RNA, SCT
 5 dimensional reductions calculated: pca, umap.rna, lsi, umap.atac, umap.wnn

In [ ]:
FeatureMatrix

ERROR: Error in library(SoupX): there is no package called 'SoupX'

In [ ]:
# In this script we will read in the filtered .rds file (from sample_metrics_filtering.R)
# and then perform SoupX on the RNA counts. Afterwards, we will add in the ATAC WINDOWS counts
# (from sample_make_ATAC_lfm_fromBCs.py), regenerate bulk metrics, and perform standard clustering analyses.

# This is v3 of the pipeline and the following changes have been implemented:
# - FindClusters() algorithm has been changed from alg 3 to alg 4.
# - We are using an automated method to estimate contamination.
# - ^ The previous manual method is still here, just commented out. To use that, comment out the automated method and uncomment out the manual method.
# - Added in a round integer function for SoupX. 
# - All plots are outputted as a pdf and merged at the end of this script. 
# - Additional necessary libraries have been added.

### Set up steps
#Read in necessary inputs
args = commandArgs(trailingOnly = TRUE)
sample_dir <- args[1]
output_dir <- args[2] #sample specific subdir of overall outputs dir
reticulate_path <- args[3]
marker_file <- args[4]
short_marker_file <- args[5]
soupx_marker_file <- args[6]
demux_out <- args[7]

#Set reticulate python
#These are essential reticulate functions that allow us to use python packages in R
#you'll need a conda env with 'leidenalg' and 'pandas' installed to do this
#then route reticulate to the python installed in that conda env with the below functions
Sys.setenv(RETICULATE_PYTHON=sprintf("%s/bin/python",reticulate_path))
library(reticulate)
reticulate::use_python(sprintf("%s/bin/python",reticulate_path))
reticulate::use_condaenv(reticulate_path)

# Load necessary libraries
suppressMessages(library(hdf5r))
suppressMessages(library(Seurat))
suppressMessages(library(Signac))
suppressMessages(library(harmony))

suppressMessages(library(EnsDb.Hsapiens.v86))
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
suppressMessages(library(Matrix))
suppressMessages(library(data.table))
suppressMessages(library(ggpubr))
suppressMessages(library(knitr))
suppressMessages(library(SoupX))
suppressMessages(library(grid))
suppressMessages(library(ggplotify))
suppressMessages(library(patchwork))
suppressMessages(library(here))
suppressMessages(library(rlist))
suppressMessages(library(qpdf))
suppressMessages(library(tidyverse))


opts_chunk$set(tidy=TRUE)
warnLevel <- getOption('warn')
options(warn = -1)


### Read in .rds Seurat object
print(paste("[[R script 3]]: Reading in the RDS file:",Sys.time()))
adata <- readRDS(file = file.path(output_dir,'intermediate_filtered.rds'))

### Perform SoupX count correction
#Read in raw (tod) and filtered (toc) gex metrics
print(paste("[[R script 3]]: Gathering data and creating the Soup Channel object:",Sys.time()))
wd <- sample_dir
tod <- Seurat::Read10X_h5(file.path(wd, 'raw_feature_bc_matrix.h5'))$`Gene Expression`
DefaultAssay(adata) <- 'RNA'
toc = GetAssayData(object = adata, slot = "counts")

#Compile necessary metadata (pull out the required metadata from the clustered filtered 
#adata object; we need the UMAP coordinates (RD1 and RD2) and the cluster assignments at minimum)
metadata <- (cbind(as.data.frame(adata[["umap.wnn"]]@cell.embeddings),
                   as.data.frame(Idents(adata))))
colnames(metadata) <- c("RD1","RD2","Cluster")

#Make sure the metadata BCs match the toc matrix barcodes
print(paste("[[R script 3]]: Checking all necessary barcode and gene indices match:",Sys.time()))
if (FALSE %in% (row.names(metadata) %in% colnames(toc)) == TRUE) {
  stop('Not all metadata barcodes found in toc')}
if (FALSE %in% (colnames(toc) %in% row.names(metadata)) == TRUE) {
  stop('Not all toc barcodes found in metadata')}

#Make sure the toc and tod indices match
if (FALSE %in% (row.names(tod) %in% row.names(toc)) == TRUE) {
  stop("Not all tod genes found in toc")}
if (FALSE %in% (row.names(toc) %in% row.names(tod)) == TRUE) {
  stop("Not all toc genes found in tod")}
if (FALSE %in% (row.names(toc) == row.names(tod)) == TRUE) {
  stop("toc and tod gene indices don't match")
}

#Create a Soup Channel object and add in the metadata
sc <- SoupChannel(tod,toc)
sc <- setDR(sc,metadata[colnames(sc$toc),c("RD1","RD2")])
sc <- setClusters(sc,setNames(metadata$Cluster,rownames(metadata)))

# Automated method for defining noise
sc = autoEstCont(sc)
#print(paste("Auto Estimated Contamination Fraction:",median(adata2[[]][,'nFeature_RNA'])))

#Output the estimated percentage of background as a separate file!
background <- sc$soupProfile[order(sc$soupProfile$est,decreasing=TRUE),] 
write.table(background,file.path(output_dir,"SoupX_estimated_background.csv"), sep='\t') 
### keep an eye on this output (some is char, other is #s; not sure if we need stringsAsFactors = T/F?)

print(paste('[[R script 3]]: Estimated global contamination fraction:',(sc$fit$rhoEst)*100,"%"))
# roundToInt function
out <- adjustCounts(sc,roundToInt=TRUE)


### Visualize changes to expression profile post SoupX
#Read in short marker gene list and select genes we have data for
#marker.genes.short <- scan(short_marker_file,what="",sep="\n")
#gene_names1 <- row.names(out)
#master_list1 <- marker.genes.short[marker.genes.short %in% gene_names1]
#master_list1 <- master_list1[seq(1,9)]

### Load Post SoupX RNA into Seurat Object and add ATAC Windows
print(paste('[[R script 3]]: Creating new Seurat Object with SoupX Counts:', Sys.time()))
adata2 = CreateSeuratObject(out)
adata2[['percent.mt']] <- PercentageFeatureSet(adata2, pattern = '^MT-')

#add in previous raw RNA data as another assay (RNA_raw)
DefaultAssay(adata) <- 'RNA'
raw_rna <-  GetAssayData(object = adata, slot = "counts")
raw_rna_assay <- CreateAssayObject(counts = raw_rna)
adata2[['RNA_raw']] <- raw_rna_assay

#read in the ATAC long format matrix as a table
print(paste("[[R script 3]]: Converting the ATAC long format matrix into a sparse matrix:",Sys.time()))
atac_lfm <- read.table(file.path(output_dir, 'atac.long_fmt.filtered_barcode.mtx.gz'), sep='\t', header=FALSE, stringsAsFactors=FALSE)

#we need to make sure the ATAC BCs match the one currently in adata2$RNA
#double check that all desired BCs are found in the ATAC BCs (and vice versa)
bc_order <- colnames(adata2[["RNA"]])
if (FALSE %in% (bc_order %in% atac_lfm$V2) == TRUE) {
  stop("Not all BCs from adata2 found in ATAC long format matrix")}
if (FALSE %in% (atac_lfm$V2 %in% bc_order) == TRUE) {
  stop("Not all BCs from ATAC long format matrix found in adata2")}

#now set the levels of the lfm based on the desired bc order and reorder based on them
atac_lfm$V2 <- factor(atac_lfm$V2, levels=bc_order)
reordered_lfm <- atac_lfm[order(atac_lfm$V2),]
#do the factoring for windows (V1) in whatever order (automatically alphanumeric?)
reordered_lfm$V1 <- as.factor(reordered_lfm$V1)
#finally make the ATAC sparse matrix and double check the BC order is correct
atac_counts2 <- with(reordered_lfm,sparseMatrix(i=as.numeric(V1), j=as.numeric(V2), x=V3, dimnames=list(levels(V1), levels(V2))))
if (FALSE %in% (colnames(atac_counts2) == bc_order) == TRUE) {
  stop("Unable to create an ATAC sparse matrix with the correct BC order")}

#assemble the other necessary components for a chromatin assay object
print(paste("[[R script 3]]: Creating the Chromatin Assay Object:",Sys.time()))
grange.counts2 <- StringToGRanges(rownames(atac_counts2), sep = c(':', '-'))
grange.use2 <- seqnames(grange.counts2) %in% standardChromosomes(grange.counts2)
atac_counts2 <- atac_counts2[as.vector(grange.use2), ]
suppressMessages(annotations <- GetGRangesFromEnsDb(ensdb=EnsDb.Hsapiens.v86))
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- 'hg38'

#create the chromatin assay object and add to Seurat object
frag.file2 <- file.path(wd, 'atac_fragments.tsv.gz')
chrom_assay2 <- CreateChromatinAssay(counts=atac_counts2, sep=c(':', '-'), genome='hg38', fragments=frag.file2, min.cells=0, min.features=-1, annotation=annotations)
adata2[['ATAC']] <- chrom_assay2


### Compute post-SoupX bulk metrics
#add QC data in
print(paste("[[R script 3]]: Reading in QC data:",Sys.time()))
qc <- read.table(file.path(wd, 'per_barcode_metrics.csv'), sep=',', header=TRUE, stringsAsFactors=1)
qc <- as.data.frame(qc)
rownames(qc) <- qc$gex_barcode
qc <- qc[Cells(adata2), 6:length(colnames(qc))]
adata2 <- AddMetaData(adata2, qc)

#now compute bulk metrics
print(paste("[[R script 3]]: Computing final bulk metrics:",Sys.time()))
print(paste("[[R script 3]]: ATAC median high-quality fragments per cell (atac_fragments):",median(adata2[[]][,'atac_fragments'])))
DefaultAssay(adata2) <- 'ATAC'
adata2 <- TSSEnrichment(adata2)
print(paste("[[R script 3]]: ATAC median TSSe:",median(adata2[[]][,'TSS.enrichment'])))
print(paste("[[R script 3]]: RNA median genes per cell:",median(adata2[[]][,'nFeature_RNA'])))
print(demux_out)
####### DEMUXLET COMPONENT ######
########### DEMUXLET ########
files <- list.files(demux_out, pattern = "\\.best", full.names = FALSE, recursive = TRUE)
demux_fp <- paste(demux_out,files, sep ='/')
demux <- read.table(demux_fp, sep='\t', header=T)
demux_sub <- demux[str_detect(demux$DROPLET.TYPE, "SNG"),]

##### below may change by project ####
### the lines below are responsible for shortening vcf donor IDs
### the line parsing might be different then below
### in github are code examples to use for projects previously done
# for pancreas and lung pool: demux_sub$donor_id <-gsub("_.*","",demux_sub$BEST.GUESS)

demux_sub$donor_id <-gsub("_.*","",demux_sub$BEST.GUESS)

demux_sub_filt <- demux_sub[demux_sub$BARCODE %in% colnames(adata2),]

### Add donor metadata under column 'donor_demux'
multiome_filtered <- adata2[,colnames(adata2) %in% demux_sub_filt$BARCODE]
rownames(demux_sub_filt) <- demux_sub_filt[,2]
filtered_df <- demux_sub_filt$donor_id

multiome_filtered <- AddMetaData(
  object = multiome_filtered,
  metadata = filtered_df,
  col.name = 'donor_demux'
)

print(paste("[[R script 3]]: Post demuxlet object:",nrow(multiome_filtered@meta.data)))

adata2 <- multiome_filtered

### Analyze and cluster the post-SoupX object
# RNA analysis
#DefaultAssay(adata2) <- 'RNA'
#adata2 <- SCTransform(adata2, verbose = FALSE) %>% RunPCA() %>% RunUMAP(dims=1:50, reduction.name='umap.rna', reduction.key='rnaUMAP_')
DefaultAssay(adata2) <- 'RNA'
suppressWarnings(adata2 <- SCTransform(adata2, verbose=FALSE))
adata2 <- RunPCA(adata2)
adata2 <- RunHarmony(adata2, group.by.vars='donor_demux', assay.use='SCT', reduction.save='harmony.rna')
adata2 <- RunUMAP(adata2, dims=1:50, reduction='harmony.rna', reduction.name='umap.rna', reduction.key='rnaUMAP_')


# ATAC analysis
# We exclude the first dimension as this is typically correlated with sequencing depth
DefaultAssay(adata2) <- 'ATAC'
adata2 <- RunTFIDF(adata2)
adata2 <- FindTopFeatures(adata2, min.cutoff='q25', verbose=FALSE)
adata2 <- RunSVD(adata2)
hm_atac <- HarmonyMatrix(Embeddings(adata2, reduction='lsi'),  adata2@meta.data, 'donor_demux' ,do_pca=FALSE)
adata2[['harmony.atac']] <- CreateDimReducObject(embeddings=hm_atac, key='atac_', assay='ATAC')
adata2 <- RunUMAP(adata2, dims=2:50, reduction='harmony.atac', reduction.name='umap.atac', reduction.key='atacUMAP_')



adata2 <- FindMultiModalNeighbors(adata2, reduction.list=list('harmony.rna', 'harmony.atac'), dims.list=list(1:50, 2:50))
adata2 <- RunUMAP(adata2, nn.name='weighted.nn', reduction.name='umap.wnn', reduction.key='wnnUMAP_')
adata2 <- FindClusters(adata2, graph.name='wsnn', algorithm=4, resolution = .2, verbose=FALSE, method="igraph")

adata2$log_nCount_ATAC = log(adata2$nCount_ATAC)
adata2$log_nCount_SCT = log(adata2$nCount_SCT)
adata2$log_nFeature_ATAC = log(adata2$nFeature_ATAC)
adata2$log_nFeature_SCT = log(adata2$nFeature_SCT)


### Save final Seurat object to an .rds file 
print(paste("Saving final RDS:",Sys.time()))
saveRDS(adata2, file = file.path(output_dir,'final_filtered.rds'))


### Plotting results (as pdfs, more than previous script)
print(paste("Outputting Plots:",Sys.time()))

#3 UMAPs
p1 <- DimPlot(adata2, reduction='umap.rna', group.by='seurat_clusters', label=TRUE, label.size=8, repel=TRUE) + ggtitle('RNA')
p1 <- p1 + xlab('UMAP 1') + ylab('UMAP 2') + ggtitle('RNA only')
p2 <- DimPlot(adata2, reduction='umap.atac', group.by='seurat_clusters', label=TRUE, label.size=8, repel=TRUE) + ggtitle('ATAC')
p2 <- p2 + xlab('UMAP 1') + ylab('UMAP 2') + ggtitle('ATAC only')
p3 <- DimPlot(adata2, reduction='umap.wnn', group.by='seurat_clusters', label=TRUE, label.size=8, repel=TRUE) + ggtitle('WNN')
p3 <- p3 + xlab('UMAP 1')+ ylab('UMAP 2') + ggtitle('Combined')
figure <- ggarrange(p1 & NoLegend(), p2 & NoLegend(), p3 & NoLegend(), ncol = 3, nrow = 1)
out_figure <- annotate_figure(figure, top = text_grob("Final Filtered UMAPS - R Script #2", color = "red", face = "bold", size = 25))
pdf_path3 <- file.path(output_dir, '/plots/plot_f.pdf')
ggsave(pdf_path3, out_figure, width=7, height=3, units="in", scale=3)

#Violin plots of metrics
p1 <- VlnPlot(adata2, features='nCount_SCT', group.by='seurat_clusters', pt.size=0, log=TRUE) + geom_boxplot(width=.6, fill='white', alpha=.6, pt.size=0) + geom_hline(yintercept=median(adata2$nCount_SCT), linetype='dashed', lw=2) + 
  theme(plot.title = element_text(size = 25), axis.text = element_text(size=20))
p2 <- VlnPlot(adata2, features='nFeature_SCT', group.by='seurat_clusters', pt.size=0, log=TRUE) + geom_boxplot(width=.6, fill='white', alpha=.6, pt.size=0) + geom_hline(yintercept=median(adata2$nFeature_SCT), linetype='dashed', lw=2) + 
  theme(plot.title = element_text(size = 25), axis.text = element_text(size=20))
p3 <- VlnPlot(adata2, features='nCount_ATAC', group.by='seurat_clusters', pt.size=0, log=TRUE) + geom_boxplot(width=.6, fill='white', alpha=.6, pt.size=0) + geom_hline(yintercept=median(adata2$nCount_ATAC), linetype='dashed', lw=2) + 
  theme(plot.title = element_text(size = 25), axis.text = element_text(size=20))
p4 <- VlnPlot(adata2, features='nFeature_ATAC', group.by='seurat_clusters', pt.size=0, log=TRUE) + geom_boxplot(width=.6, fill='white', alpha=.6, pt.size=0) + geom_hline(yintercept=median(adata2$nFeature_ATAC), linetype='dashed', lw=2) + 
  theme(plot.title = element_text(size = 25), axis.text = element_text(size=20))
p5 <- VlnPlot(adata2, features='nCount_RNA', group.by='seurat_clusters', pt.size=0, log=TRUE) + geom_boxplot(width=.6, fill='white', alpha=.6, pt.size=0) + geom_hline(yintercept=median(adata2$nCount_SCT), linetype='dashed', lw=2) + 
  theme(plot.title = element_text(size = 25), axis.text = element_text(size=20))
p6 <- VlnPlot(adata2, features='nFeature_RNA', group.by='seurat_clusters', pt.size=0, log=TRUE) + geom_boxplot(width=.6, fill='white', alpha=.6, pt.size=0) + geom_hline(yintercept=median(adata2$nFeature_SCT), linetype='dashed', lw=2) + 
  theme(plot.title = element_text(size = 25), axis.text = element_text(size=20))
figure <- ggarrange(p1, p3, p5, p2, p4, p6, ncol = 3, nrow = 2)
out_figure <- annotate_figure(figure, top = text_grob("Final Filtered Metrics Violin Plots - R Script #2", color = "red", face = "bold", size = 25))
pdf_path4 <- file.path(output_dir, '/plots/plot_g.pdf')
ggsave(pdf_path4, out_figure, width=7, height=3, units="in", scale=3)

#UMAP feature plots of metrics
p1 <- FeaturePlot(adata2, reduction='umap.wnn', features=c('log_nCount_ATAC','log_nFeature_ATAC','log_nCount_SCT','log_nFeature_SCT'), 
                  cols=c('lightgrey', 'red'), ncol=4) + xlab('UMAP 1') + ylab('UMAP 2')
p1 & theme(plot.title=element_text(hjust=0.5))

out_figure <- p1 + plot_annotation(title = "Final Features Metrics FeaturePlot - R Script #2") & theme(plot.title = element_text(hjust = 0.5))
pdf_path5 <- file.path(output_dir, '/plots/plot_h.pdf')
ggsave(pdf_path5, out_figure, width=9, height=3, units="in", scale=3)

#Marker gene plot
options(repr.plot.width=12, repr.plot.height=6)
marker.genes.long <- scan(marker_file,what="",sep="\n")
unique_markers <- unique(marker.genes.long)
p1 <- DotPlot(adata2, assay='SCT', features=unique_markers, cluster.idents=TRUE) 
p1 <- p1 + theme(axis.text.x=element_text(angle=45, hjust=1)) + xlab('') + ylab('')
p1

out_figure <- annotate_figure(p1, top = text_grob("Final Filtered Marker Genes - R Script #2", color = "red", face = "bold", size = 25))
pdf_path6 <- file.path(output_dir, '/plots/plot_i.pdf')
ggsave(pdf_path6, out_figure, width=3, height=2, units="in", scale=3)

#Marker gene feature plot -- this currently has workarounds in case no immune cells are found, but not other rare cell types
#Select for short list marker genes that are found in the data
marker.genes.short <- scan(short_marker_file,what="",sep="\n")
unique_markers <- unique(marker.genes.short)
gene_names2 <- row.names(adata2[["SCT"]][])
master_list2 <- unique_markers[unique_markers %in% gene_names2]
master_list2 <- master_list2[seq(1,9)]
sct.master_list2 <- paste('sct_',master_list2,sep="")
print("Marker genes selected for cell type FeaturePlots:")
print(sct.master_list2)

options(repr.plot.width=15, repr.plot.height=15)
p1 <- FeaturePlot(adata2, reduction='umap.wnn', features=sct.master_list2[c(1,2,3)], ncol=3)
p2 <- FeaturePlot(adata2, reduction='umap.wnn', features=sct.master_list2[c(4,5,6)], ncol=3) 
p3 <- FeaturePlot(adata2, reduction='umap.wnn', features=sct.master_list2[c(7,8,9)], ncol=3) 
for (j in c(1,2,3)) {
  p1[[j]] <- p1[[j]] + xlab('')
  p2[[j]] <- p2[[j]] + xlab('')
}
for (j in c(2,3)) {
  p1[[j]] <- p1[[j]] + ylab('') + theme(legend.position = c(.05, .95))
  p2[[j]] <- p2[[j]] + ylab('') + theme(legend.position = c(.05, .95))
  p3[[j]] <- p3[[j]] + ylab('') + theme(legend.position = c(.05, .95))
  p1[[1]] <- p1[[1]] + theme(legend.position = c(.05, .95))
  p2[[1]] <- p2[[1]] + theme(legend.position = c(.05, .95))
  p3[[1]] <- p3[[1]] + theme(legend.position = c(.05, .95))
}

figure <- p1 / p2 /p3
out_figure <- figure +
plot_annotation(title = "Final Filtered Marker Genes UMAP FeaturePlot- R Script #2") &  theme(plot.title = element_text(hjust = 0.5))
pdf_path7 <- file.path(output_dir, '/plots/plot_j.pdf')
ggsave(pdf_path7, out_figure, width=3, height=3, units="in", scale=3)

# Combine all PDF plots
pdf_dir <- file.path(output_dir, '/plots')
pdf_files <- list.files(here(pdf_dir), pattern="plot_", full.names = TRUE)
pdf_combine(input = pdf_files, output = file.path(output_dir, 'final_output_plots.pdf'))

# Remove all PDF plots (other than final)
temp_path <- file.path(output_dir,'/plots')
unlink(temp_path,recursive=TRUE)

print(paste("Done:",Sys.time()))

In [6]:
test <- read.table('/nfs/lab/welison/mega_pancreas/intermediates/Single_Sample_Processing_Intermediates/nPOD/231121_WE_SSP_Intermediates/Raw_adatas/MM_510_AMULET_barcode_table.csv')

dim(test)
head(test)

[1] 666833      1

  V1
1 barcode,cell_id,is__cell_barcode
2 1,AAACAGCCAAACAACA-1,None,0
3 2,AAACAGCCAAACATAG-1,None,0
4 3,AAACAGCCAAACCCTA-1,None,0
5 4,AAACAGCCAAACCTAT-1,None,0
6 5,AAACAGCCAAACCTTG-1,None,0

In [ ]:
library <- 'MM_1341_1_2_MM_1337_1_2'

read.

In [ ]:
amulet_barcodes <- data.frame(barcode=colnames(adata))

amulet_table <- dplyr::left_join(amulet_barcodes, data.frame(barcode=colnames(adata), 
                                         cell_id=colnames(adata), 
                                         is__cell_barcode=TRUE))
amulet_table$is__cell_barcode[is.na(amulet_table$is__cell_barcode)] <- FALSE
amulet_table$is__cell_barcode <- as.numeric(amulet_table$is__cell_barcode)
amulet_table$cell_id[is.na(amulet_table$cell_id)] <- 'None'

write.table(amulet_table, paste0(outdir, samp,  "_AMULET_barcode_table.csv"), 
            sep=',', col.names=T, row.names=T, quote=F)

In [8]:
DefaultAssay(adata) <- 'SCT'

adata$RNA_raw <- NULL
adata$windows <- NULL

gc()

       used       (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells   12332660   658.7    22039490   1177.1    14674365    783.7
Vcells 7530635289 57454.2 15798642234 120534.1 14893286634 113626.8

In [9]:
table(adata$batch)

 firstPR fourthPR secondPR  thirdPR
   41571   131572   116609   135799

In [10]:
table(adata$lane)

MM_1341_1_2_MM_1337_1_2 MM_1342_1_2_MM_1338_1_2 MM_1343_1_2_MM_1339_1_2
                  10474                   10204                   10299
MM_1344_1_2_MM_1340_1_2     QY_2270_2_QY_2269_2     QY_2272_2_QY_2271_2
                  10594                   14390                   14225
QY_2274_1_2_QY_2273_1_2     QY_2276_2_QY_2275_2     QY_2278_2_QY_2277_2
                  13893                   14509                   15678
    QY_2280_2_QY_2279_2     QY_2282_2_QY_2281_2 QY_2284_1_2_QY_2283_1_2
                  14783                   14625                   14506
    QY_2380_2_QY_2379_2     QY_2382_2_QY_2381_2 QY_2384_1_2_QY_2383_1_2
                  16769                   17142                   17818
    QY_2386_2_QY_2385_2     QY_2388_2_QY_2387_2     QY_2390_2_QY_2389_2
                  16627                   16592                   16978
    QY_2392_2_QY_2391_2 QY_2394_1_2_QY_2393_1_2 QY_2396_1_2_QY_2395_1_2
                  16764                   17109                   16995
    QY_2398_2_QY_2397_2     QY_2400_2_QY_2399_2     QY_2402_2_QY_2401_2
                  16532                   16226                   16292
QY_2404_1_2_QY_2403_1_2     QY_2406_2_QY_2405_2     QY_2408_2_QY_2407_2
                  16577                   16309                   16614
    QY_2410_2_QY_2409_2
                  16027

In [11]:
table(adata$condition)

    NAFL     NASH NASH_ALD   Normal
  140784    91151    57430   136186

In [12]:
table(adata$donor_demux)

HL150001 HL150009 HL150013 HL150015 HL160017 HL160022 HL160026 HL160029
   11154     3618     2324     5706     9121     2620     7463     1865
HL160030 HL160032 HL160035 HL160037 HL160040 HL160041 HL160042 HL170044
    5406     6887     4417     4068     9087     3663     1531     5447
HL170046 HL170047 HL170048 HL170049 HL170052 HL170055 HL170058 HL170060
    2574     2357     7195     1773     5153     4391     3557     1765
HL170062 HL170064 HL170065 HL170066 HL180069 HL180071 HL180809 HL181010
   10711     7725     4483     7524     4648     1465     8733     4459
HL181029 HL181031 HL190114 HL190214 HL190215 HL190326 HL190603 HL190606
    3456    12670     2670     2214    12841     4493     5413     2049
HL190624 HL190827 HL190909 HL191002 HL191025 HL191216 HL200115 HL200212
    2575     3992     4017     4453     1438     3413     5579     3946
HL200525 HL200529 HL200615 HL200707 HL200805 HL200925 HL201024 HL201120
    4187     3230     3773     1403     3045     2391     2729     4143
HL210120 HL210207 HL210521 HL210614 HL210621 HL210706 HL210726 HL210727
    3248     5789     3962     4169     6820     7448     3268     3149
HL210806 HL211001 HL211025 HL211106 HL211122 HL220127 HL220210 HL220216
    2584    10186     3905     3872     6678     5306     3041     1830
HL220402 HL220405 HL220613 HL220628 HL220825 HL221006 HL221019 HL221119
    3382     4850     3262     4997     1060     7387      891     7152
HL221201 HL221215 HL230212 HL230302 HL230316 HL230324 HL230325
    8058     8267     5721     2298     4485     9512    15964

In [13]:
table(adata$disease_status)

Control Disease
 136186  289365

In [14]:
FM_20 <- FindMarkers(adata, assay='SCT', ident.1='20', max.cells.per.ident=50000)
FM_20

            p_val     avg_log2FC pct.1 pct.2 p_val_adj
NRXN1       0         10.836665  0.974 0.008 0
CDH19       0          6.655456  0.970 0.039 0
CADM2       0          6.867549  0.948 0.048 0
NRXN3       0          7.174875  0.920 0.026 0
ADGRB3      0          5.418672  0.961 0.098 0
GRIK2       0          7.125994  0.890 0.038 0
NEGR1       0          7.141432  0.861 0.017 0
SCN7A       0          6.365527  0.857 0.019 0
NCAM2       0          5.673819  0.866 0.058 0
SLC35F1     0          7.657991  0.799 0.009 0
KIRREL3     0          7.596777  0.775 0.016 0
ANK3        0          2.905528  0.920 0.194 0
XKR4        0         13.582308  0.716 0.000 0
ANK2        0          6.053172  0.751 0.037 0
TENM3       0          5.279125  0.766 0.073 0
NKAIN3      0          7.235190  0.699 0.012 0
SEMA3C      0          5.413074  0.710 0.024 0
SORCS1      0          7.213467  0.686 0.008 0
LPAR1       0          4.627456  0.738 0.061 0
CHL1        0          5.798164  0.695 0.022 0
CASC15      0          4.325190  0.708 0.041 0
NCAM1       0          4.468119  0.693 0.041 0
GPM6B       0          6.110880  0.630 0.016 0
COL28A1     0          5.892738  0.619 0.022 0
FRMD5       0          7.385162  0.597 0.007 0
NLGN4X      0          4.462493  0.615 0.035 0
GULP1       0          4.223319  0.617 0.040 0
ADGRL3      0          4.752077  0.597 0.029 0
PMP22       0          4.780183  0.608 0.046 0
PLCE1       0          4.667131  0.582 0.037 0
⋮           ⋮         ⋮          ⋮     ⋮     ⋮
TAB1        0.9851823  0.5545742 0.078 0.082 1
NAXE        0.9863435  0.3760145 0.011 0.010 1
DENND6A-AS1 0.9863911  0.2706662 0.050 0.050 1
CALM1       0.9866228  0.5082748 0.165 0.182 1
AC079807.1  0.9872676  0.3368712 0.011 0.010 1
CRMP1       0.9889539  0.1153075 0.013 0.014 1
RPS28       0.9895038  0.5424439 0.197 0.216 1
SLC22A15    0.9896475  0.2810759 0.080 0.082 1
FHL3        0.9898435  0.3675609 0.011 0.010 1
HMGN4       0.9908275  0.5051386 0.061 0.063 1
CEP97       0.9910238  0.3057706 0.050 0.049 1
CUEDC2      0.9914201  0.2081258 0.019 0.018 1
AZIN1-AS1   0.9916155  0.6363905 0.128 0.134 1
GLA         0.9918285 -0.1371946 0.019 0.019 1
IFT57       0.9925450  0.4097457 0.054 0.054 1
KIAA1841    0.9935269  0.4494895 0.095 0.100 1
MN1         0.9936116  0.1516717 0.013 0.013 1
FAM234A     0.9940420  0.7024051 0.065 0.066 1
TRIM34      0.9941161  0.2317135 0.022 0.021 1
ADGRG6      0.9944579 -0.1446879 0.803 0.672 1
SAA2        0.9946724 -0.9821552 0.736 0.574 1
AP001453.1  0.9949998  0.2304208 0.013 0.013 1
MED12       0.9956282  0.1006824 0.024 0.024 1
LINC02035   0.9957246  0.2149342 0.015 0.015 1
UBE2S       0.9961485  0.2404084 0.015 0.014 1
ZNF593      0.9963251  0.2120556 0.011 0.011 1
ERICH6-AS1  0.9964680  0.1806166 0.011 0.011 1
ZNF426      0.9965992  0.1146460 0.022 0.021 1
PDE4DIP     0.9974357  0.6299809 0.212 0.237 1
AC022098.1  0.9988121  0.1785448 0.022 0.022 1

In [15]:
FM_12 <- FindMarkers(adata, assay='SCT', ident.1='12', max.cells.per.ident=50000)
FM_12

           p_val     avg_log2FC pct.1 pct.2 p_val_adj
DIAPH3     0         6.996414   0.722 0.015 0
CENPK      0         5.803406   0.711 0.023 0
BRIP1      0         4.591486   0.767 0.099 0
POLQ       0         6.603375   0.667 0.010 0
EZH2       0         4.414522   0.776 0.119 0
CEP128     0         2.977598   0.742 0.145 0
SMC4       0         3.328708   0.767 0.171 0
CENPP      0         3.291303   0.842 0.246 0
MELK       0         6.749750   0.603 0.009 0
BRCA2      0         4.685277   0.627 0.039 0
FANCI      0         4.963383   0.607 0.034 0
NCAPG2     0         4.408518   0.620 0.052 0
MMS22L     0         3.629645   0.672 0.108 0
BARD1      0         3.722721   0.648 0.088 0
KNTC1      0         3.929680   0.611 0.056 0
NSD2       0         2.877614   0.779 0.227 0
HELLS      0         5.234675   0.584 0.032 0
LINC01572  0         3.808271   0.631 0.080 0
ASPM       0         6.459572   0.559 0.014 0
KNL1       0         4.765903   0.576 0.041 0
DTL        0         6.301787   0.539 0.010 0
ATAD5      0         4.065727   0.581 0.052 0
ATAD2      0         3.267669   0.729 0.201 0
LMNB1      0         4.743545   0.546 0.031 0
PRIM2      0         2.599336   0.787 0.272 0
ZGRF1      0         4.044690   0.562 0.051 0
RFC3       0         3.332498   0.607 0.100 0
ANLN       0         7.717429   0.510 0.004 0
ECT2       0         4.057043   0.559 0.062 0
RRM2       0         4.995172   0.517 0.028 0
⋮          ⋮         ⋮          ⋮     ⋮     ⋮
TLE5       0.9198673 -0.1201808 0.098 0.097 1
KCNMB2-AS1 0.9231541 -0.2726270 0.054 0.054 1
AL391684.1 0.9277244 -0.1630096 0.047 0.047 1
LGI1       0.9320137  0.1281266 0.012 0.012 1
LMCD1-AS1  0.9327727 -0.2617810 0.165 0.161 1
IL15RA     0.9338376 -0.1466866 0.191 0.184 1
GLCCI1     0.9385572 -0.4214024 0.282 0.273 1
CSRP1      0.9397165 -0.2182575 0.077 0.079 1
CACNA1D    0.9405967  0.3153683 0.327 0.354 1
LYPD6B     0.9479028  0.2045288 0.010 0.011 1
KCNH8      0.9535179 -0.2356170 0.013 0.014 1
AP000240.1 0.9543780  0.1279761 0.011 0.011 1
CNN3       0.9544396 -0.1021814 0.271 0.263 1
AC012065.3 0.9564551 -0.1320314 0.010 0.012 1
MIR2052HG  0.9610558 -0.1996400 0.018 0.018 1
AC008050.1 0.9710054 -0.4759450 0.060 0.061 1
OCA2       0.9727199  0.1123820 0.013 0.012 1
AC109597.1 0.9773217  0.1107686 0.015 0.014 1
KIRREL3    0.9790104 -0.1919725 0.017 0.017 1
SDK2       0.9809249  0.1331587 0.010 0.010 1
LSP1       0.9837434  0.1838135 0.011 0.010 1
CCDC30     0.9840796 -0.1465238 0.108 0.105 1
OFD1       0.9849954 -0.1089003 0.194 0.193 1
NID2       0.9865512 -0.2015360 0.026 0.026 1
KALRN      0.9866019 -0.1439296 0.395 0.400 1
DNM3OS     0.9875472 -0.4471496 0.081 0.078 1
SBDS       0.9896355  0.1094427 0.043 0.042 1
ZMAT3      0.9921346 -0.1477267 0.155 0.153 1
EIF2AK3    0.9933726 -0.1496959 0.298 0.288 1
SCN1A-AS1  0.9966821  0.2176532 0.133 0.134 1

In [16]:
FM_17 <- FindMarkers(adata, assay='SCT', ident.1='17', max.cells.per.ident=50000)
FM_17

           p_val     avg_log2FC pct.1 pct.2 p_val_adj
PTPRC      0         1.5709001  0.929 0.161 0
CELF2      0         1.1830842  0.857 0.176 0
SKAP1      0         2.1000201  0.915 0.244 0
ARHGAP15   0         0.9018286  0.860 0.223 0
FYN        0         1.4712313  0.861 0.231 0
CD96       0         2.9449672  0.657 0.046 0
CD247      0         2.7217102  0.645 0.045 0
PARP8      0         1.7992648  0.939 0.354 0
STAT4      0         1.6646181  0.750 0.176 0
IKZF1      0         1.6215304  0.661 0.111 0
SLFN12L    0         3.2460895  0.587 0.040 0
TC2N       0         2.3864198  0.627 0.084 0
AOAH       0         1.1202142  0.724 0.181 0
TOX        0         1.8009822  0.669 0.132 0
BCL11B     0         3.7720102  0.558 0.030 0
THEMIS     0         3.7656284  0.551 0.026 0
PRKCH      0         0.9878219  0.817 0.306 0
LINC01934  0         3.3796404  0.535 0.036 0
IKZF3      0         2.9983450  0.524 0.040 0
SYTL3      0         2.6464553  0.542 0.059 0
PDE7A      0         1.3922407  0.728 0.248 0
FYB1       0         0.2727519  0.619 0.149 0
SLC38A1    0         1.6621107  0.625 0.161 0
DOCK10     0         0.6461410  0.679 0.220 0
CCND3      0         1.2712559  0.642 0.186 0
MYBL1      0         3.2029177  0.489 0.035 0
PRKCQ      0         3.4942576  0.488 0.035 0
EMB        0         2.5441428  0.497 0.055 0
PYHIN1     0         3.1751852  0.470 0.035 0
PPP2R2B    0         3.1145846  0.470 0.038 0
⋮          ⋮         ⋮          ⋮     ⋮     ⋮
CALCOCO2   0.9513901 -0.2162377 0.304 0.288 1
TMC7       0.9521076  0.1042610 0.013 0.013 1
AL442067.3 0.9540872  0.1520055 0.012 0.011 1
ADCY3      0.9542986 -0.4164760 0.041 0.040 1
PPFIA2-AS1 0.9566694  0.1368371 0.011 0.010 1
TGFBR3     0.9570195 -0.5079964 0.500 0.454 1
RP2        0.9571723 -0.2315558 0.087 0.087 1
NEURL2     0.9580780 -0.1666134 0.031 0.031 1
SCRN1      0.9581873 -0.1102289 0.017 0.018 1
ZNF608     0.9603800 -0.3114020 0.255 0.242 1
NR1H3      0.9611418 -0.2763017 0.107 0.105 1
B3GNT5     0.9616212 -0.1028161 0.027 0.028 1
MTURN      0.9634188 -0.1362122 0.050 0.052 1
LGALS8     0.9653417 -0.2484233 0.210 0.204 1
RRAGC      0.9657354 -0.1749600 0.070 0.069 1
ATF7       0.9704154 -0.1847657 0.463 0.430 1
FCHO1      0.9724135 -0.1691852 0.020 0.020 1
TNFRSF10D  0.9744600 -0.2651091 0.143 0.140 1
AL354811.1 0.9775570  0.1637843 0.010 0.009 1
STIL       0.9784231 -0.1851425 0.024 0.024 1
ARIH1      0.9786794 -0.1093609 0.752 0.713 1
TAF4B      0.9790619 -0.2346776 0.031 0.030 1
TBC1D15    0.9813392 -0.3002267 0.466 0.421 1
AC091271.1 0.9827159  0.1614232 0.010 0.010 1
LINC00511  0.9836503 -0.3436055 0.012 0.013 1
IGHG4      0.9871621 -0.5652426 0.011 0.009 1
AC018816.1 0.9953860 -0.5043087 0.065 0.066 1
MARK3      0.9968933 -0.1678176 0.669 0.616 1
PGS1       0.9974918 -0.2523384 0.162 0.156 1
SYCP2      0.9996108 -0.1068028 0.029 0.029 1

In [17]:
FM_7 <- FindMarkers(adata, assay='SCT', ident.1='7', max.cells.per.ident=50000)
FM_7

           p_val     avg_log2FC pct.1 pct.2 p_val_adj
PTPRC      0         3.931134   0.938 0.125 0
CELF2      0         3.600850   0.909 0.142 0
ARHGAP15   0         2.958285   0.904 0.191 0
FYN        0         3.952691   0.906 0.200 0
CD247      0         7.331898   0.713 0.014 0
CD96       0         6.785078   0.710 0.015 0
SKAP1      0         4.738299   0.902 0.214 0
IKZF1      0         3.996119   0.719 0.083 0
SLFN12L    0         6.479232   0.623 0.013 0
AOAH       0         3.585917   0.763 0.154 0
PARP8      0         4.297534   0.935 0.327 0
STAT4      0         3.739848   0.744 0.150 0
SYTL3      0         5.515885   0.617 0.033 0
PRKCH      0         3.086618   0.852 0.280 0
FYB1       0         2.246146   0.694 0.124 0
TOX        0         4.131458   0.672 0.107 0
TC2N       0         4.739184   0.612 0.059 0
IKZF3      0         5.582686   0.560 0.016 0
DOCK10     0         2.564705   0.733 0.196 0
CARD11     0         5.968899   0.548 0.013 0
LINC01934  0         6.465206   0.542 0.013 0
PDE7A      0         3.643064   0.746 0.225 0
PYHIN1     0         6.261525   0.531 0.012 0
CCND3      0         3.512775   0.682 0.163 0
BCL11B     0         6.711698   0.519 0.007 0
ITGA4      0         3.998652   0.565 0.056 0
MYBL1      0         6.396417   0.519 0.013 0
EMB        0         4.867706   0.528 0.033 0
CHST11     0         1.983308   0.751 0.257 0
PRKCQ      0         5.860159   0.506 0.013 0
⋮          ⋮         ⋮          ⋮     ⋮     ⋮
AXIN1      0.7003678  0.6727115 0.083 0.090 1
CYTH3      0.7280701  0.6877116 0.122 0.128 1
AC022182.1 0.7339337  0.1200916 0.013 0.012 1
TMEM65     0.7626752  0.6199737 0.211 0.237 1
RPL32      0.7665937  0.7766908 0.134 0.146 1
ZNF675     0.7712023  0.6873717 0.064 0.066 1
USP9Y      0.7871844  0.5347615 0.263 0.305 1
ITGAX      0.7878213 -0.9278046 0.029 0.030 1
CMTM7      0.7903418  0.3771486 0.143 0.156 1
TET1       0.8035647  0.6099052 0.083 0.089 1
MR1        0.8330695  0.6501589 0.061 0.064 1
RAB2A      0.8366059  0.1867381 0.575 0.598 1
VIM        0.8405906  0.1666141 0.065 0.068 1
TOP2B      0.8421789  0.6343649 0.325 0.417 1
SKAP2      0.8451056  0.3096394 0.293 0.330 1
UBE2D2     0.8525334  0.6334678 0.294 0.370 1
CSGALNACT2 0.8593589  0.6420863 0.152 0.166 1
TTF2       0.8704678  0.5868421 0.064 0.068 1
RBMS3      0.8721217 -2.9236353 0.681 0.443 1
SESN1      0.8727411  0.6445196 0.315 0.392 1
CFL1       0.8782706  0.6464516 0.061 0.065 1
KIF13B     0.8841590  0.3396554 0.449 0.517 1
KSR1       0.9035567  0.6301294 0.134 0.143 1
RPS17      0.9054024  0.7646759 0.130 0.143 1
EZH2       0.9152675  0.9429923 0.117 0.126 1
RPL3       0.9512309  0.7218629 0.129 0.140 1
HERC5      0.9630300  0.2405602 0.045 0.044 1
CENPL      0.9643153 -0.1019294 0.012 0.013 1
FBF1       0.9657508  0.1305426 0.020 0.019 1
DNASE1     0.9747130  0.8457604 0.122 0.132 1

In [18]:
FM_T <- FindMarkers(adata, assay='SCT', ident.1='7', ident.2='17', max.cells.per.ident=50000)
FM_T

            p_val     avg_log2FC pct.1 pct.2 p_val_adj
F2          0         -4.612677  0.018 0.667 0
SERPINF2    0         -4.592495  0.018 0.631 0
FTCD        0         -4.435705  0.037 0.647 0
SHMT1       0         -3.668098  0.036 0.645 0
SLC28A1     0         -5.969599  0.008 0.615 0
MARC2       0         -5.636643  0.010 0.615 0
SLC22A3     0         -6.147991  0.008 0.607 0
ABCA8       0         -5.765418  0.012 0.609 0
HPX         0         -3.526806  0.035 0.628 0
RBMS3       0          2.553064  0.681 0.091 0
SLC22A7     0         -4.829477  0.028 0.617 0
MTTP        0         -5.738082  0.009 0.595 0
RGN         0         -4.552403  0.040 0.625 0
DNAH14      0         -3.975233  0.050 0.633 0
F11         0         -5.977328  0.007 0.590 0
MYLK        0         -4.376439  0.034 0.615 0
ACOT12      0         -6.026908  0.008 0.589 0
SERPING1    0         -3.672087  0.029 0.606 0
AC087482.1  0         -5.772625  0.008 0.585 0
HNF4A       0         -5.309404  0.011 0.588 0
SLC30A10    0         -4.202716  0.049 0.624 0
KLKB1       0         -4.040308  0.041 0.616 0
ADORA2A-AS1 0         -5.782946  0.008 0.583 0
ABAT        0         -2.779287  0.061 0.632 0
ENPP1       0         -3.492066  0.100 0.670 0
SEC16B      0         -5.735121  0.008 0.572 0
ALDH8A1     0         -5.117866  0.011 0.575 0
TTC6        0         -6.112435  0.008 0.572 0
LINC02484   0         -5.104280  0.028 0.591 0
XYLB        0         -3.348303  0.086 0.646 0
⋮           ⋮         ⋮          ⋮     ⋮     ⋮
PLEKHO1     0.9132018  0.1190657 0.032 0.032 1
ZNF714      0.9143402  0.2080637 0.048 0.049 1
TMED3       0.9160452  0.2013890 0.040 0.041 1
CNOT4       0.9177196  0.3625847 0.548 0.646 1
HNRNPU      0.9191207  0.2610864 0.604 0.678 1
LRRC37B     0.9231144  0.7861104 0.124 0.136 1
TGFBR1      0.9309414  0.9052116 0.252 0.317 1
GRAMD1B     0.9314446  0.4694502 0.086 0.088 1
JAZF1       0.9320127  0.4856896 0.575 0.705 1
IRF4        0.9354642 -0.6262738 0.018 0.017 1
NXPE3       0.9371125  0.7709774 0.051 0.054 1
TMEM65      0.9377198  1.0170294 0.211 0.254 1
BTG1        0.9410008  0.7397816 0.342 0.461 1
NAP1L4      0.9506747  0.7403692 0.372 0.523 1
TRPC3       0.9528625 -0.1155123 0.010 0.010 1
STAMBPL1    0.9569463  0.7985297 0.204 0.241 1
SNTB2       0.9664461  0.9074597 0.211 0.254 1
SHISAL2A    0.9723066 -0.1155123 0.010 0.011 1
TSBP1-AS1   0.9755367  0.3174471 0.010 0.010 1
MARCH6      0.9761717  0.3422441 0.563 0.656 1
AC068587.4  0.9774127  1.0568354 0.209 0.253 1
CD226       0.9792011  0.8884241 0.187 0.217 1
SPC25       0.9822836  0.6554872 0.015 0.015 1
MECP2       0.9862068  0.8308067 0.327 0.442 1
PVT1        0.9862564  0.9078076 0.241 0.291 1
AC092535.4  0.9903904  0.1394848 0.022 0.022 1
PKM         0.9936210  0.2002195 0.057 0.057 1
XPO6        0.9939488  0.7976417 0.340 0.471 1
NIBAN1      0.9942745  0.4656981 0.232 0.241 1
DENND6A     0.9949029  0.8731279 0.290 0.378 1