In [1]:
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(fgsea)

Warning message:
“package ‘dplyr’ was built under R version 4.3.2”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“package ‘stringr’ was built under R version 4.3.2”
Warning message:
“package ‘fgsea’ was built under R version 4.3.3”

In [2]:
trait_beds <- rev(list.files('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits/', full.names = TRUE)) #full.names makes sure you have the full file path
background_beds <- list.files('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/background/', full.names = TRUE)
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [3]:
out.dir <- '/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_FINRICH/outs/'

In [4]:
Sys.time()
commands <- character()

# Run for DE sites
for(FILE in trait_beds[1]){
    cs_file <- str_replace(FILE, '/nfs/lab/tscc','/tscc/projects/ps-gaultonlab')#paste0(sprintf('/nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/background/%s.spec.union.peaks.bed',
    results2 <- NULL #Create an empty dataframe to store results from loop
    message(FILE)

    bed.dir.tscc <- str_replace(bed.dir, '/nfs/lab/tscc','/tscc/projects/ps-gaultonlab')
    
    CELL='Hepatocytes'
    
    for (clust in 1:5) {
        background_name <- '/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5.txt'
        
        input_name <- paste0('/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5_cluster_',clust,'.bed')
        commands <- c(commands, paste0('findMotifsGenome.pl ',input_name,' hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_Fibrosis_depeak_kmeans5_',
                 clust,'/ -size 200 -bg ',background_name,' -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer'))
    }
    
    for (clust in 1:5) {
        background_name <- '/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5.txt'
        
        input_name <- paste0('/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5_cluster_',clust,'.bed')
        commands <- c(commands, paste0('findMotifsGenome.pl ',input_name,' hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_MASH_depeak_kmeans5_',
                 clust,'/ -size 200 -bg ',background_name,' -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer'))
    }
}

Sys.time()

length(commands)
head(commands)
tail(commands)

commands[str_detect(commands, 'nfs')]

[1] "2024-12-27 11:31:46 PST"

/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed

[1] "2024-12-27 11:31:46 PST"

[1] 10

[1] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5_cluster_1.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_Fibrosis_depeak_kmeans5_1/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[2] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5_cluster_2.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_Fibrosis_depeak_kmeans5_2/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[3] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5_cluster_3.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_Fibrosis_depeak_kmeans5_3/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[4] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5_cluster_4.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_Fibrosis_depeak_kmeans5_4/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[5] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5_cluster_5.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_Fibrosis_depeak_kmeans5_5/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[6] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5_cluster_1.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_MASH_depeak_kmeans5_1/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"

[1] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5_cluster_5.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_Fibrosis_depeak_kmeans5_5/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_Fibrosis_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[2] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5_cluster_1.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_MASH_depeak_kmeans5_1/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[3] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5_cluster_2.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_MASH_depeak_kmeans5_2/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[4] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5_cluster_3.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_MASH_depeak_kmeans5_3/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[5] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5_cluster_4.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_MASH_depeak_kmeans5_4/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[6] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5_cluster_5.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/ATAC_MASH_depeak_kmeans5_5/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/ATAC_MASH_depeak_kmeans5.txt -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"

character(0)

In [5]:
write.table(commands, '/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/241227_WE_DAC_clusters_homer.txt',
           col.names=F, row.names=F, quote=F, sep='\t')

In [8]:
directories <- list.dirs('/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/outs/')

directories[str_detect(directories, 'kmeans')]

In [25]:
vroom::vroom(paste0('/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/outs/ATAC_MASH_depeak_kmeans5_',i,'/knownResults.txt'))

Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    Motif Name            Consensus                           P-value
1   MA1130.1_FOSL2::JUN   NDATGAGTCATH                        1e-18
2   MA0478.1_FOSL2        KGRTGACTCAB                         1e-17
3   MA1141.1_FOS::JUND    NKATGAGTCATMN                       1e-17
4   MA1128.1_FOSL1::JUN   NKATGACTCATNN                       1e-17
5   MA1633.2_BACH1        ATGACTCAT                           1e-17
6   MA1134.1_FOS::JUNB    KATGAGTCATMN                        1e-16
7   MA0491.2_JUND         NNATGACTCATNN                       1e-16
8   MA1144.1_FOSL2::JUND  GATGACTCAT                          1e-16
9   MA0490.2_JUNB         NNATGACTCATNN                       1e-15
10  MA0477.2_FOSL1        NNATGACTCATNN                       1e-15
11  MA1138.1_FOSL2::JUNB  KATGACTCAT                          1e-15
12  MA0476.1_FOS          DVTGASTCATB                         1e-15
13  MA0099.3_FOS::JUN     ATGAGTCATM                          1e-15
14  MA1928.1_BNC2         NDGTGAGTCAYN                        1e-14
15  MA1142.1_FOSL1::JUND  NATGACTCAT                          1e-14
16  MA1135.1_FOSB::JUNB   GATGACTCAT                          1e-13
17  MA1634.1_BATF         DATGACTCATH                         1e-13
18  MA1137.1_FOSL1::JUNB  NKATGACTCATNN                       1e-13
19  MA0462.2_BATF::JUN    DATGACTCATH                         1e-13
20  MA0835.2_BATF3        WATGACTCATW                         1e-13
21  MA1132.1_JUN::JUNB    KATGACTCAT                          1e-11
22  MA0655.1_JDP2         ATGACTCAT                           1e-08
23  MA0496.3_MAFK         WGCTGACTCAGCANW                     1e-07
24  MA0160.2_NR4A2        BTAAAGGTCA                          1e-06
25  MA0089.2_MAFG::NFE2L1 AVNATGACTCAGCAAT                    1e-06
26  MA1101.2_BACH2        AAANCATGASTCATSNTTT                 1e-05
27  MA1494.1_HNF4A        GRGTCCAAAGGTCAH                     1e-04
28  MA1531.1_NR1D1        RGGTCAGTRGGTCAN                     1e-04
29  MA1136.1_FOSB::JUNB   ATGACGTCAT                          1e-04
30  MA0600.2_RFX2         SGTTGCCATGGCAACS                    1e-04
⋮   ⋮                     ⋮                                   ⋮
663 MA1964.1_SMAD2        NSCCAGACRB                          1
664 MA1970.1_TRPS1        DHTCTTATCTNH                        1
665 MA0679.2_ONECUT1      AAAAAATCAATAAWWN                    1
666 MA1511.2_KLF10        GGGGCGGGG                           1
667 MA1943.1_ETV2::HOXB13 ACCGGAAMYATAAAM                     1
668 MA0102.4_CEBPA        NDATTGCACAATHN                      1
669 MA0801.1_MGA          AGGTGTGA                            1
670 MA1104.2_GATA6        HWATCTTATCTNH                       1
671 MA0836.2_CEBPD        DATTGCACAATHN                       1
672 MA0756.2_ONECUT2      CGATCGATA                           1
673 MA1929.1_CTCF         CTGCAGTTCCNNNNNYNGCCACYAGGKGGCRCYV  1
674 MA1727.1_ZNF417       VABVNTGGGCGCCAM                     1
675 MA1593.1_ZNF317       TRACAGCAGAYW                        1
676 MA1119.1_SIX2         NNCTGAAACCTGATMC                    1
677 MA1709.1_ZIM3         AVCAACAGAAACCYA                     1
678 MA1585.1_ZKSCAN1      ATAGTAGGTG                          1
679 MA0833.2_ATF4         DDATGATGCAATMW                      1
680 MA0748.2_YY2          MSATGGCGGCS                         1
681 MA0742.2_KLF12        GGGGCGGGG                           1
682 MA0139.1_CTCF         TGGCCACYAGGGGGCRCYA                 1
683 MA0757.1_ONECUT3      AAAAAATCAATAAW                      1
684 MA1930.1_CTCF         CTGCAGTKCCNVCHNHYGGCCACYAGRKGGCRCYN 1
685 MA0149.1_EWSR1-FLI1   GGAAGGAAGGAAGGAAGG                  1
686 MA0731.1_BCL6B        TGCTTTCTAGGAATTCM                   1
687 MA0735.1_GLIS1        AGACCCCCCACGAWGC                    1
688 MA0749.1_ZBED1        CTATCGCGACATA                       1
689 MA0752.1_ZNF410       TMCATCCCATAATAHTC                   1
690 MA0779.1_PAX1         CGTCACGCATGASTGCM                   1
691 MA1544.1_OVOL1        AAWACCGTTATNYN                      1
692 MA1722.1_ZSCAN31      GCATAACTGCCCTGCGKCC                 1
    Log P-value q-value (Benjamini) # of Target Sequences with Motif(of 802)
1   -41.790     0.0000              249
2   -41.190     0.0000              222
3   -40.700     0.0000              240
4   -39.870     0.0000              244
5   -39.180     0.0000              208
6   -38.870     0.0000              220
7   -38.820     0.0000              217
8   -38.490     0.0000              234
9   -36.750     0.0000              224
10  -36.420     0.0000              231
11  -35.940     0.0000              236
12  -35.360     0.0000              234
13  -35.120     0.0000              241
14  -33.460     0.0000              226
15  -32.810     0.0000              213
16  -32.210     0.0000              232
17  -31.850     0.0000              232
18  -31.230     0.0000              231
19  -31.000     0.0000              234
20  -30.730     0.0000              233
21  -25.790     0.0000              199
22  -20.290     0.0000              126
23  -17.920     0.0000              183
24  -14.610     0.0000              129
25  -14.180     0.0000              101
26  -13.530     0.0000               77
27  -11.380     0.0003               32
28  -10.150     0.0010               27
29   -9.845     0.0013               52
30   -9.826     0.0013                7
⋮   ⋮           ⋮                   ⋮
663 -0.006369   1                    94
664 -0.006300   1                    49
665 -0.005069   1                    28
666 -0.004150   1                    52
667 -0.003981   1                     4
668 -0.003123   1                   104
669 -0.002983   1                    52
670 -0.002972   1                    46
671 -0.002486   1                   102
672 -0.002389   1                     9
673 -0.002358   1                    24
674 -0.001771   1                     9
675 -0.001533   1                    78
676 -0.001515   1                    36
677 -0.001505   1                    41
678 -0.001163   1                    20
679 -0.000720   1                    50
680 -0.000364   1                     2
681 -0.000359   1                    29
682 -0.000254   1                    31
683 -0.000057   1                     6
684 -0.000004   1                    15
685  0.000000   1                     0
686  0.000000   1                     0
687  0.000000   1                     0
688  0.000000   1                     0
689  0.000000   1                     0
690  0.000000   1                     0
691  0.000000   1                     0
692  0.000000   1                     0
    % of Target Sequences with Motif
1   31.05%
2   27.68%
3   29.93%
4   30.42%
5   25.94%
6   27.43%
7   27.06%
8   29.18%
9   27.93%
10  28.80%
11  29.43%
12  29.18%
13  30.05%
14  28.18%
15  26.56%
16  28.93%
17  28.93%
18  28.80%
19  29.18%
20  29.05%
21  24.81%
22  15.71%
23  22.82%
24  16.08%
25  12.59%
26  9.60%
27  3.99%
28  3.37%
29  6.48%
30  0.87%
⋮   ⋮
663 11.72%
664 6.11%
665 3.49%
666 6.48%
667 0.50%
668 12.97%
669 6.48%
670 5.74%
671 12.72%
672 1.12%
673 2.99%
674 1.12%
675 9.73%
676 4.49%
677 5.11%
678 2.49%
679 6.23%
680 0.25%
681 3.62%
682 3.87%
683 0.75%
684 1.87%
685 0.00%
686 0.00%
687 0.00%
688 0.00%
689 0.00%
690 0.00%
691 0.00%
692 0.00%
    # of Background Sequences with Motif(of 1716)
1   311.6
2   266.2
3   298.7
4   307.1
5   247.7
6   268.2
7   263.1
8   293.6
9   280.4
10  293.0
11  303.1
12  301.3
13  314.2
14  292.7
15  271.3
16  306.3
17  307.8
18  307.3
19  313.2
20  312.6
21  267.0
22  156.4
23  263.8
24  178.8
25  131.7
26   93.2
27   29.3
28   24.2
29   62.1
30    2.8
⋮   ⋮
663 252.4
664 144.8
665  92.4
666 154.6
667  24.1
668 281.9
669 156.8
670 141.3
671 278.4
672  42.3
673  85.5
674  43.1
675 224.2
676 119.0
677 132.3
678  77.2
679 159.7
680  22.9
681 107.6
682 114.8
683  43.7
684  82.1
685  10.0
686   2.3
687   0.0
688   0.0
689   0.0
690   0.9
691   5.1
692   7.9
    % of Background Sequences with Motif
1   18.16%
2   15.52%
3   17.41%
4   17.90%
5   14.43%
6   15.63%
7   15.33%
8   17.12%
9   16.34%
10  17.08%
11  17.66%
12  17.56%
13  18.32%
14  17.06%
15  15.81%
16  17.86%
17  17.94%
18  17.91%
19  18.26%
20  18.22%
21  15.56%
22  9.12%
23  15.38%
24  10.42%
25  7.67%
26  5.43%
27  1.71%
28  1.41%
29  3.62%
30  0.16%
⋮   ⋮
663 14.71%
664 8.44%
665 5.39%
666 9.01%
667 1.40%
668 16.43%
669 9.14%
670 8.23%
671 16.23%
672 2.47%
673 4.98%
674 2.51%
675 13.06%
676 6.94%
677 7.71%
678 4.50%
679 9.31%
680 1.34%
681 6.27%
682 6.69%
683 2.55%
684 4.78%
685 0.59%
686 0.13%
687 0.00%
688 0.00%
689 0.00%
690 0.05%
691 0.30%
692 0.46%

In [40]:
MASH.res <- data.frame()
for (i in 1:5) {
    MASH.res <- vroom::vroom(paste0('/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/outs/ATAC_MASH_depeak_kmeans5_',i,'/knownResults.txt')) %>%
        mutate(comparison='MASH',cluster=i) %>%
        select(Motif.Name=`Motif Name`, p.value=`P-value`, log.p.value=`Log P-value`, 
               q.value=`q-value (Benjamini)`, num.target.seqs.with.motif=contains("# of Target Sequences with Motif(of "),
              perc.target.seqs.with.motif=`% of Target Sequences with Motif`,
              num.background.seqs.with.motif=contains("# of Background Sequences with Motif(of "),
              perc.background.seqs.with.motif=`% of Background Sequences with Motif`, cluster, comparison) %>%
        mutate(perc.target.seqs.with.motif=as.numeric(str_remove(perc.target.seqs.with.motif, '%')),
              perc.background.seqs.with.motif=as.numeric(str_remove(perc.background.seqs.with.motif, '%'))) %>%
        mutate(FC=(perc.target.seqs.with.motif/perc.background.seqs.with.motif),
              L2FC=log2(abs(FC))) %>%
        rbind(MASH.res)
}

colnames(MASH.res)

dim(MASH.res)
head(MASH.res)

write.table(MASH.res,'/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/ATAC_MASH_depeak_kmeans5_homer_res.tsv',
           col.names=T, row.names=T, quote=F, sep='\t')

Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

 [1] "Motif.Name"                      "p.value"
 [3] "log.p.value"                     "q.value"
 [5] "num.target.seqs.with.motif"      "perc.target.seqs.with.motif"
 [7] "num.background.seqs.with.motif"  "perc.background.seqs.with.motif"
 [9] "cluster"                         "comparison"
[11] "FC"                              "L2FC"

[1] 3460   12

  Motif.Name          p.value log.p.value q.value num.target.seqs.with.motif
1 MA1130.1_FOSL2::JUN 1e-18   -41.79      0       249
2 MA0478.1_FOSL2      1e-17   -41.19      0       222
3 MA1141.1_FOS::JUND  1e-17   -40.70      0       240
4 MA1128.1_FOSL1::JUN 1e-17   -39.87      0       244
5 MA1633.2_BACH1      1e-17   -39.18      0       208
6 MA1134.1_FOS::JUNB  1e-16   -38.87      0       220
  perc.target.seqs.with.motif num.background.seqs.with.motif
1 31.05                       311.6
2 27.68                       266.2
3 29.93                       298.7
4 30.42                       307.1
5 25.94                       247.7
6 27.43                       268.2
  perc.background.seqs.with.motif cluster comparison FC       L2FC
1 18.16                           5       MASH       1.709802 0.7738291
2 15.52                           5       MASH       1.783505 0.8347154
3 17.41                           5       MASH       1.719127 0.7816761
4 17.90                           5       MASH       1.699441 0.7650606
5 14.43                           5       MASH       1.797644 0.8461072
6 15.63                           5       MASH       1.754958 0.8114368

In [42]:
Fibrosis.res <- data.frame()
for (i in 1:5) {
    Fibrosis.res <- vroom::vroom(paste0('/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/outs/ATAC_Fibrosis_depeak_kmeans5_',i,'/knownResults.txt')) %>%
        mutate(comparison='Fibrosis',cluster=i) %>%
        select(Motif.Name=`Motif Name`, p.value=`P-value`, log.p.value=`Log P-value`, 
               q.value=`q-value (Benjamini)`, num.target.seqs.with.motif=contains("# of Target Sequences with Motif(of "),
              perc.target.seqs.with.motif=`% of Target Sequences with Motif`,
              num.background.seqs.with.motif=contains("# of Background Sequences with Motif(of "),
              perc.background.seqs.with.motif=`% of Background Sequences with Motif`, cluster, comparison) %>%
        mutate(perc.target.seqs.with.motif=as.numeric(str_remove(perc.target.seqs.with.motif, '%')),
              perc.background.seqs.with.motif=as.numeric(str_remove(perc.background.seqs.with.motif, '%'))) %>%
        mutate(FC=(perc.target.seqs.with.motif/perc.background.seqs.with.motif),
              L2FC=log2(abs(FC))) %>%
        rbind(Fibrosis.res)
}

colnames(Fibrosis.res)

dim(Fibrosis.res)
head(Fibrosis.res)

write.table(Fibrosis.res,'/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/ATAC_Fibrosis_depeak_kmeans5_homer_res.tsv',
           col.names=T, row.names=T, quote=F, sep='\t')

Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

 [1] "Motif.Name"                      "p.value"
 [3] "log.p.value"                     "q.value"
 [5] "num.target.seqs.with.motif"      "perc.target.seqs.with.motif"
 [7] "num.background.seqs.with.motif"  "perc.background.seqs.with.motif"
 [9] "cluster"                         "comparison"
[11] "FC"                              "L2FC"

[1] 3460   12

  Motif.Name           p.value log.p.value q.value num.target.seqs.with.motif
1 MA1128.1_FOSL1::JUN  1e-199  -458.6      0       1758
2 MA0099.3_FOS::JUN    1e-198  -456.2      0       1743
3 MA1130.1_FOSL2::JUN  1e-197  -454.0      0       1746
4 MA1141.1_FOS::JUND   1e-194  -448.8      0       1686
5 MA1138.1_FOSL2::JUNB 1e-189  -437.0      0       1676
6 MA0477.2_FOSL1       1e-187  -430.7      0       1643
  perc.target.seqs.with.motif num.background.seqs.with.motif
1 36.28                       8040.2
2 35.98                       7951.5
3 36.04                       7989.7
4 34.80                       7604.8
5 34.59                       7621.2
6 33.91                       7436.2
  perc.background.seqs.with.motif cluster comparison FC       L2FC
1 17.98                           5       Fibrosis   2.017798 1.012781
2 17.78                           5       Fibrosis   2.023622 1.016940
3 17.87                           5       Fibrosis   2.016788 1.012059
4 17.01                           5       Fibrosis   2.045855 1.032704
5 17.05                           5       Fibrosis   2.028739 1.020583
6 16.63                           5       Fibrosis   2.039086 1.027923

In [43]:
arrange(Fibrosis.res, p.value)

     Motif.Name            p.value log.p.value q.value
1    MA1128.1_FOSL1::JUN   1e-199  -458.6      0
2    MA0099.3_FOS::JUN     1e-198  -456.2      0
3    MA1130.1_FOSL2::JUN   1e-197  -454.0      0
4    MA1141.1_FOS::JUND    1e-194  -448.8      0
5    MA1138.1_FOSL2::JUNB  1e-189  -437.0      0
6    MA0759.2_ELK3         1e-188  -433.5      0
7    MA0477.2_FOSL1        1e-187  -430.7      0
8    MA1135.1_FOSB::JUNB   1e-186  -430.4      0
9    MA1144.1_FOSL2::JUND  1e-186  -428.6      0
10   MA0765.3_ETV5         1e-186  -428.3      0
11   MA1137.1_FOSL1::JUNB  1e-185  -427.5      0
12   MA0476.1_FOS          1e-185  -426.3      0
13   MA1134.1_FOS::JUNB    1e-177  -408.1      0
14   MA1634.1_BATF         1e-176  -406.3      0
15   MA0462.2_BATF::JUN    1e-174  -401.6      0
16   MA1928.1_BNC2         1e-172  -397.9      0
17   MA0835.2_BATF3        1e-172  -397.6      0
18   MA0490.2_JUNB         1e-170  -393.3      0
19   MA1142.1_FOSL1::JUND  1e-166  -383.9      0
20   MA0491.2_JUND         1e-163  -376.9      0
21   MA1633.2_BACH1        1e-163  -375.8      0
22   MA0139.1_CTCF         1e-161  -371.2      0
23   MA1132.1_JUN::JUNB    1e-147  -339.8      0
24   MA0478.1_FOSL2        1e-144  -332.1      0
25   MA0028.2_ELK1         1e-142  -328.4      0
26   MA1716.1_ZNF76        1e-130  -301.5      0
27   MA0764.3_ETV4         1e-111  -257.0      0
28   MA1930.1_CTCF         1e-104  -240.2      0
29   MA0156.3_FEV          1e-102  -236.5      0
30   MA0746.2_SP3           1e-97  -223.4      0
⋮    ⋮                     ⋮       ⋮           ⋮
3431 MA0836.2_CEBPD        1       0           1
3432 MA0114.4_HNF4A        1       0           1
3433 MA0764.3_ETV4         1       0           1
3434 MA0484.2_HNF4G        1       0           1
3435 MA0139.1_CTCF         1       0           1
3436 MA0476.1_FOS          1       0           1
3437 MA0478.1_FOSL2        1       0           1
3438 MA0655.1_JDP2         1       0           1
3439 MA0841.1_NFE2         1       0           1
3440 MA0099.3_FOS::JUN     1       0           1
3441 MA1128.1_FOSL1::JUN   1       0           1
3442 MA1130.1_FOSL2::JUN   1       0           1
3443 MA1132.1_JUN::JUNB    1       0           1
3444 MA1134.1_FOS::JUNB    1       0           1
3445 MA1135.1_FOSB::JUNB   1       0           1
3446 MA1137.1_FOSL1::JUNB  1       0           1
3447 MA1138.1_FOSL2::JUNB  1       0           1
3448 MA1141.1_FOS::JUND    1       0           1
3449 MA1142.1_FOSL1::JUND  1       0           1
3450 MA1144.1_FOSL2::JUND  1       0           1
3451 MA1101.2_BACH2        1       0           1
3452 MA0462.2_BATF::JUN    1       0           1
3453 MA1634.1_BATF         1       0           1
3454 MA0835.2_BATF3        1       0           1
3455 MA0477.2_FOSL1        1       0           1
3456 MA0490.2_JUNB         1       0           1
3457 MA0491.2_JUND         1       0           1
3458 MA0089.2_MAFG::NFE2L1 1       0           1
3459 MA1928.1_BNC2         1       0           1
3460 MA1633.2_BACH1        1       0           1
     num.target.seqs.with.motif perc.target.seqs.with.motif
1    1758                       36.28
2    1743                       35.98
3    1746                       36.04
4    1686                       34.80
5    1676                       34.59
6    1392                        8.36
7    1643                       33.91
8    1671                       34.49
9    1651                       34.08
10   1126                        6.76
11   1696                       35.01
12   1671                       34.49
13   1568                       32.36
14   1683                       34.74
15   1676                       34.59
16   1619                       33.42
17   1687                       34.82
18   1589                       32.80
19   1559                       32.18
20   1525                       31.48
21   1478                       30.51
22   2895                       17.39
23   1463                       30.20
24   1487                       30.69
25   1204                        7.23
26    887                        5.33
27   1700                       10.21
28   1506                        9.04
29   1072                        6.44
30   5401                       32.43
⋮    ⋮                          ⋮
3431 402                         6.92
3432 562                         9.67
3433 143                         2.46
3434 565                         9.72
3435 379                         6.52
3436 574                         9.88
3437 568                         9.78
3438 286                         4.92
3439 159                         2.74
3440 612                        10.53
3441 622                        10.71
3442 607                        10.45
3443 545                         9.38
3444 524                         9.02
3445 586                        10.09
3446 607                        10.45
3447 573                         9.86
3448 580                         9.98
3449 527                         9.07
3450 572                         9.85
3451 190                         3.27
3452 631                        10.86
3453 624                        10.74
3454 637                        10.96
3455 574                         9.88
3456 549                         9.45
3457 513                         8.83
3458 267                         4.60
3459 591                        10.17
3460 513                         8.83
     num.background.seqs.with.motif perc.background.seqs.with.motif cluster
1    8040.2                         17.98                           5
2    7951.5                         17.78                           5
3    7989.7                         17.87                           5
4    7604.8                         17.01                           5
5    7621.2                         17.05                           5
6     833.7                          3.48                           3
7    7436.2                         16.63                           5
8    7635.0                         17.08                           5
9    7508.2                         16.79                           5
10    601.8                          2.51                           3
11   7834.3                         17.52                           5
12   7666.2                         17.15                           5
13   7081.5                         15.84                           5
14   7905.5                         17.68                           5
15   7893.0                         17.65                           5
16   7516.5                         16.81                           5
17   8003.5                         17.90                           5
18   7340.1                         16.42                           5
19   7202.6                         16.11                           5
20   7018.6                         15.70                           5
21   6700.5                         14.99                           5
22   2501.0                         10.43                           3
23   6877.3                         15.38                           5
24   7110.4                         15.90                           5
25    767.5                          3.20                           3
26    503.1                          2.10                           3
27   1375.1                          5.74                           3
28   1194.6                          4.98                           3
29    749.9                          3.13                           3
30   6037.1                         25.18                           3
⋮    ⋮                              ⋮                               ⋮
3431 4298.5                          9.63                           1
3432 5747.5                         12.88                           1
3433 1941.1                          4.35                           1
3434 5819.2                         13.04                           1
3435 4913.3                         11.01                           1
3436 7483.4                         16.77                           1
3437 7060.0                         15.82                           1
3438 4026.2                          9.02                           1
3439 2378.0                          5.33                           1
3440 7766.6                         17.40                           1
3441 7855.7                         17.60                           1
3442 7849.1                         17.59                           1
3443 6615.4                         14.82                           1
3444 6922.2                         15.51                           1
3445 7413.8                         16.61                           1
3446 7555.3                         16.93                           1
3447 7414.3                         16.61                           1
3448 7524.6                         16.86                           1
3449 6862.7                         15.38                           1
3450 7331.4                         16.43                           1
3451 2654.8                          5.95                           1
3452 7584.7                         17.00                           1
3453 7603.8                         17.04                           1
3454 7653.0                         17.15                           1
3455 7280.7                         16.31                           1
3456 7084.9                         15.88                           1
3457 6801.1                         15.24                           1
3458 3428.6                          7.68                           1
3459 7393.3                         16.57                           1
3460 6512.0                         14.59                           1
     comparison FC        L2FC
1    Fibrosis   2.017798  1.0127814
2    Fibrosis   2.023622  1.0169399
3    Fibrosis   2.016788  1.0120594
4    Fibrosis   2.045855  1.0327042
5    Fibrosis   2.028739  1.0205833
6    Fibrosis   2.402299  1.2644156
7    Fibrosis   2.039086  1.0279226
8    Fibrosis   2.019321  1.0138702
9    Fibrosis   2.029780  1.0213231
10   Fibrosis   2.693227  1.4293359
11   Fibrosis   1.998288  0.9987643
12   Fibrosis   2.011079  1.0079696
13   Fibrosis   2.042929  1.0306393
14   Fibrosis   1.964932  0.9744795
15   Fibrosis   1.959773  0.9706868
16   Fibrosis   1.988102  0.9913920
17   Fibrosis   1.945251  0.9599566
18   Fibrosis   1.997564  0.9982417
19   Fibrosis   1.997517  0.9982078
20   Fibrosis   2.005096  1.0036710
21   Fibrosis   2.035357  1.0252818
22   Fibrosis   1.667306  0.7375188
23   Fibrosis   1.963589  0.9734930
24   Fibrosis   1.930189  0.9487419
25   Fibrosis   2.259375  1.1759237
26   Fibrosis   2.538095  1.3437462
27   Fibrosis   1.778746  0.8308602
28   Fibrosis   1.815261  0.8601770
29   Fibrosis   2.057508  1.0408980
30   Fibrosis   1.287927  0.3650507
⋮    ⋮          ⋮         ⋮
3431 Fibrosis   0.7185877 -0.4767638
3432 Fibrosis   0.7507764 -0.4135448
3433 Fibrosis   0.5655172 -0.8223571
3434 Fibrosis   0.7453988 -0.4239157
3435 Fibrosis   0.5921889 -0.7558706
3436 Fibrosis   0.5891473 -0.7632997
3437 Fibrosis   0.6182048 -0.6938432
3438 Fibrosis   0.5454545 -0.8744691
3439 Fibrosis   0.5140713 -0.9599596
3440 Fibrosis   0.6051724 -0.7245819
3441 Fibrosis   0.6085227 -0.7166169
3442 Fibrosis   0.5940875 -0.7512525
3443 Fibrosis   0.6329285 -0.6598856
3444 Fibrosis   0.5815603 -0.7819993
3445 Fibrosis   0.6074654 -0.7191259
3446 Fibrosis   0.6172475 -0.6960790
3447 Fibrosis   0.5936183 -0.7523925
3448 Fibrosis   0.5919336 -0.7564928
3449 Fibrosis   0.5897269 -0.7618810
3450 Fibrosis   0.5995131 -0.7381369
3451 Fibrosis   0.5495798 -0.8635990
3452 Fibrosis   0.6388235 -0.6465106
3453 Fibrosis   0.6302817 -0.6659313
3454 Fibrosis   0.6390671 -0.6459608
3455 Fibrosis   0.6057633 -0.7231738
3456 Fibrosis   0.5950882 -0.7488247
3457 Fibrosis   0.5793963 -0.7873776
3458 Fibrosis   0.5989583 -0.7394724
3459 Fibrosis   0.6137598 -0.7042539
3460 Fibrosis   0.6052090 -0.7244945