In [1]:
#source activate newEnv
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
library(tibble)
library(broom)
library("parallel")
library(tidyr)
library(stringr)
library(qvalue)

Warning message:
“package ‘qvalue’ was built under R version 4.4.2”

# Write FINRICH commands

In [2]:
trait_beds <- rev(list.files('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits/', full.names = TRUE)) #full.names makes sure you have the full file path
background_beds <- list.files('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/', full.names = TRUE)
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis'

In [3]:
#dir.create('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/results/')

In [4]:
setwd('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/results/')

In [5]:
head(trait_beds)

[1] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed"
[2] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.EUR.MVP.2021.credset.bed"
[3] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//finngen_R11_T2D_WIDE_Hg38.bed"
[4] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//finngen_R11_T2D_Hg38.bed"
[5] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//finngen_R11_T1D_Hg38.bed"
[6] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//finngen_R11_T1D_EARLY_Hg38.bed"

In [6]:
out.dir <- '/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/'

In [10]:
Sys.time()
commands <- character()

# Run for DE sites
for(FILE in trait_beds[1]){
    cs_file <- str_replace(FILE, '/nfs/lab/tscc','/tscc/projects/ps-gaultonlab')#paste0(sprintf('/nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/background/%s.spec.union.peaks.bed',
    results2 <- NULL #Create an empty dataframe to store results from loop
    message(FILE)

    bed.dir.tscc <- str_replace(bed.dir, '/nfs/lab/tscc','/tscc/projects/ps-gaultonlab')
    
    CELL='Hepatocytes'
    
    for (clust in 1:5) {
        background_name <- '/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed'
        
        input_name <- paste0('/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k',clust,'.bed')
        commands <- c(commands, paste0('conda run -n FINRICH finrich ', cs_file,' ', input_name, ' ', background_name,' --permutations 1000 --processes 2 > ',
                                           out.dir,CELL,'__',str_remove(cs_file,'/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//')
                                           ,'__',str_remove(input_name, '/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/'),'.results '))
    }
}

Sys.time()

length(commands)
head(commands)
tail(commands)

commands[str_detect(commands, 'nfs')]

[1] "2025-02-19 08:18:05 PST"

/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed

[1] "2025-02-19 08:18:05 PST"

[1] 5

[1] "conda run -n FINRICH finrich /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k1.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed --permutations 1000 --processes 2 > /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/heatmap_k1.bed.results "
[2] "conda run -n FINRICH finrich /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k2.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed --permutations 1000 --processes 2 > /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/heatmap_k2.bed.results "
[3] "conda run -n FINRICH finrich /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k3.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed --permutations 1000 --processes 2 > /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/heatmap_k3.bed.results "
[4] "conda run -n FINRICH finrich /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k4.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed --permutations 1000 --processes 2 > /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/heatmap_k4.bed.results "
[5] "conda run -n FINRICH finrich /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k5.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed --permutations 1000 --processes 2 > /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/heatmap_k5.bed.results "

[1] "conda run -n FINRICH finrich /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k1.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed --permutations 1000 --processes 2 > /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/heatmap_k1.bed.results "
[2] "conda run -n FINRICH finrich /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k2.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed --permutations 1000 --processes 2 > /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/heatmap_k2.bed.results "
[3] "conda run -n FINRICH finrich /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k3.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed --permutations 1000 --processes 2 > /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/heatmap_k3.bed.results "
[4] "conda run -n FINRICH finrich /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k4.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed --permutations 1000 --processes 2 > /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/heatmap_k4.bed.results "
[5] "conda run -n FINRICH finrich /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k5.bed /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed --permutations 1000 --processes 2 > /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/heatmap_k5.bed.results "

character(0)

In [11]:
write.table(commands, '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/250219_commands_NAFLD_TRANS_ancestry.txt',col.names=F, row.names=F, quote=F, sep='\t')

# Results

In [12]:
out.dir.ophelia <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/'
out.dir.ophelia

[1] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/results/Hepatocytes__MVP.NAFLD.TRANS.MVP.2021.credset.bed__DAR_clusters_High_Fibrosis/"

In [14]:
files <- list.files(out.dir.ophelia, pattern = '')

length(files)
head(files)
tail(files)

[1] 5

[1] "heatmap_k1.bed.results" "heatmap_k2.bed.results" "heatmap_k3.bed.results"
[4] "heatmap_k4.bed.results" "heatmap_k5.bed.results"

[1] "heatmap_k1.bed.results" "heatmap_k2.bed.results" "heatmap_k3.bed.results"
[4] "heatmap_k4.bed.results" "heatmap_k5.bed.results"

### Clusters

In [15]:
out.df <- data.frame()

for (file in files) {
    trait <- str_split(file, '__', simplify=T)[2]
    ct <- str_split(file, '__', simplify=T)[1]
    in.file <- str_split(file, '__', simplify=T)[3]
    
    test.group <- ifelse(str_detect(in.file,'k1'),'k1',
                        ifelse(str_detect(in.file,'k2'),'k2',
                        ifelse(str_detect(in.file,'k3'),'k3',
                        ifelse(str_detect(in.file,'k4'),'k4','k5'))))
    
    res <- strsplit(readLines(paste0(out.dir.ophelia,file))[1], ":|,|}")
    res <- as.data.frame(res)
    if (length(res > 0)){
        results <- data.frame(matrix(ncol=0, nrow=1))
        results$modality <- 'ATAC'
        results$cell_type <- ct
        results$pval <- res[2,]
        results$fold_enrich <- res[4,]
        results$logOR <- res[6,]
        results$conf_lower <- res[8,]
        results$conf_upper  <- res[10,]
    }
    res <- cbind(data.frame(trait=trait, ct=ct, test.group=test.group), results)
    res
    
    
    out.df <- rbind(out.df, res)
}

out.df

#Endo differential - no loci in background

  trait ct                     test.group modality cell_type              pval
1 NA    heatmap_k1.bed.results NA         ATAC     heatmap_k1.bed.results  1.0
2 NA    heatmap_k2.bed.results NA         ATAC     heatmap_k2.bed.results  1.0
3 NA    heatmap_k3.bed.results NA         ATAC     heatmap_k3.bed.results  1.0
4 NA    heatmap_k4.bed.results NA         ATAC     heatmap_k4.bed.results NA
5 NA    heatmap_k5.bed.results NA         ATAC     heatmap_k5.bed.results NA
  fold_enrich logOR      conf_lower conf_upper
1  0.0         -Infinity  -Infinity  -Infinity
2  0.0         -Infinity  -Infinity  -Infinity
3  0.0         -Infinity  -Infinity  -Infinity
4 NA          NA         NA         NA
5 NA          NA         NA         NA

In [28]:
read.table('/nfs/lab/tscc/welison/FNIH.Liver/02_DESEQ_ATAC/gaulton.peaks/Hepatocytes_High_Fibrosis_vs_Control.dds.res') %>%
    filter(padj < 0.05) %>%
    rownames() %>%
    str_split(':|-', simplify=T) %>%
    write.table('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/High_Fibrosis_All.bed',
               sep='\t', col.names=F, row.names=F, quote=F)

In [29]:
read.table('/nfs/lab/tscc/welison/FNIH.Liver/02_DESEQ_ATAC/gaulton.peaks/Hepatocytes_Low_Fibrosis_vs_Control.dds.res') %>%
    filter(padj < 0.05) %>%
    rownames() %>%
    str_split(':|-', simplify=T) %>%
    write.table('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/Low_Fibrosis_All.bed',
               sep='\t', col.names=F, row.names=F, quote=F)

# Write Homer

In [7]:
#source activate newEnv
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
library(tibble)
library(broom)
library("parallel")
library(tidyr)
library(stringr)
library(qvalue)

In [8]:
trait_beds <- rev(list.files('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits/', full.names = TRUE)) #full.names makes sure you have the full file path
background_beds <- list.files('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/', full.names = TRUE)
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis'

In [9]:
#dir.create('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/results/')

In [10]:
setwd('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/results/')

In [11]:
head(trait_beds)

[1] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed"
[2] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.EUR.MVP.2021.credset.bed"
[3] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//finngen_R11_T2D_WIDE_Hg38.bed"
[4] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//finngen_R11_T2D_Hg38.bed"
[5] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//finngen_R11_T1D_Hg38.bed"
[6] "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//finngen_R11_T1D_EARLY_Hg38.bed"

In [12]:
out.dir <- '/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/results/'

In [15]:
Sys.time()
homer.commands <- character()

# Run for DE sites
for(FILE in trait_beds[1]){
    cs_file <- str_replace(FILE, '/nfs/lab/tscc','/tscc/projects/ps-gaultonlab')#paste0(sprintf('/nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/background/%s.spec.union.peaks.bed',
    results2 <- NULL #Create an empty dataframe to store results from loop
    message(FILE)

    bed.dir.tscc <- str_replace(bed.dir, '/nfs/lab/tscc','/tscc/projects/ps-gaultonlab')
    
    CELL='Hepatocytes'
    
    for (clust in 1:5) {
        background_name <- '/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed'
        
        input_name <- paste0('/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k',clust,'.bed')
        homer.commands <- c(homer.commands, paste0('findMotifsGenome.pl ',input_name,' hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.',
                     clust,'/ -size 200 -bg ',background_name,' -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer'))
    }
}

Sys.time()

length(homer.commands)
head(homer.commands)
tail(homer.commands)

commands[str_detect(homer.commands, 'nfs')]

[1] "2025-04-29 04:34:46 PDT"

/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits//MVP.NAFLD.TRANS.MVP.2021.credset.bed

[1] "2025-04-29 04:34:46 PDT"

[1] 5

[1] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k1.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.1/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[2] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k2.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.2/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[3] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k3.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.3/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[4] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k4.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.4/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[5] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k5.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.5/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"

[1] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k1.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.1/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[2] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k2.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.2/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[3] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k3.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.3/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[4] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k4.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.4/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"
[5] "findMotifsGenome.pl /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/heatmap_k5.bed hg38 /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.5/ -size 200 -bg /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites/DAR_clusters_High_Fibrosis/DAR_clusters_High_Fibrosis_all.bed -mknown /tscc/projects/ps-gaultonlab/welison/FNIH.Liver/12_HOMER/240722_WE_JASPAR_2022_monaLisa_Dump_noPseudo.homer"

character(0)

In [16]:
write.table(homer.commands, '/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/250429_commands.txt',col.names=F, row.names=F, quote=F, sep='\t')

# Read Homer

In [17]:
homer.state <- data.frame()
for (clust in 1:5) {
    file <- paste0('/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/outs/high.fib.cre.clusters.',clust,'/knownResults.txt')
    if (!file.exists(file)) {
        next
    }
    homer.state <- vroom::vroom(file) %>%
        mutate(cluster=paste0('k',clust)) %>%
        select(Motif.Name=`Motif Name`, p.value=`P-value`, log.p.value=`Log P-value`, 
               q.value=`q-value (Benjamini)`, num.target.seqs.with.motif=contains("# of Target Sequences with Motif(of "),
              perc.target.seqs.with.motif=`% of Target Sequences with Motif`,
              num.background.seqs.with.motif=contains("# of Background Sequences with Motif(of "),
              perc.background.seqs.with.motif=`% of Background Sequences with Motif`, cluster) %>%
        mutate(perc.target.seqs.with.motif=as.numeric(str_remove(perc.target.seqs.with.motif, '%')),
              perc.background.seqs.with.motif=as.numeric(str_remove(perc.background.seqs.with.motif, '%'))) %>%
        mutate(FC=(perc.target.seqs.with.motif/perc.background.seqs.with.motif),
              L2FC=log2(abs(FC))) %>%
        rbind(homer.state)
}

print(692 * 5)
dim(homer.state)
head(homer.state)

write.table(homer.state, '/nfs/lab/tscc/welison/FNIH.Liver/12_HOMER/250428_high_fib_cre_clusters_JASPAR2022.tsv', sep='\t', col.names=T, row.names=F, quote=F)

Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 692 Columns: 9
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): Motif Name, Consensus, % of Target Sequences with Motif, % of Backg...
dbl (5): P-value, Log P-value, q-value (Benjamini), # of Target Sequences wi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 3460

[1] 3460   11

  Motif.Name     p.value log.p.value q.value num.target.seqs.with.motif
1 MA0640.2_ELF3  1e-32   -74.11      0       1601
2 MA0598.3_EHF   1e-30   -70.21      0       1382
3 MA0761.2_ETV1  1e-29   -68.18      0       1586
4 MA0062.3_GABPA 1e-27   -63.77      0       1483
5 MA1508.1_IKZF1 1e-27   -62.66      0       1570
6 MA0473.3_ELF1  1e-26   -60.78      0       1443
  perc.target.seqs.with.motif num.background.seqs.with.motif
1 21.95                       1786.1
2 18.94                       1513.8
3 21.74                       1789.8
4 20.33                       1670.4
5 21.52                       1790.7
6 19.78                       1629.3
  perc.background.seqs.with.motif cluster FC       L2FC
1 16.56                           k5      1.325483 0.4065183
2 14.04                           k5      1.349003 0.4318934
3 16.60                           k5      1.309639 0.3891687
4 15.49                           k5      1.312460 0.3922731
5 16.60                           k5      1.296386 0.3744948
6 15.11                           k5      1.309067 0.3885388

In [18]:
filter(homer.state, q.value < 0.1) %>% select(cluster) %>% table()

cluster
 k1  k2  k3  k4  k5
111  66  32  71 160