In [2]:
import scanpy as sc
import numpy as np

In [3]:
# defining rank genes zones for tangram
# using all mash samples in RNA multiple
# downsampling for 10k cells out of all mash cells for tangram reference
# running rank genes on downsamples 10k cell reference

In [4]:
adata_mash = sc.read_h5ad('/tscc/projects/ps-epigen/users/cmiciano/Liver/RNA/spatial/spatial_scr/condition_h5ad/MASH.h5ad')
sc.pp.normalize_total(adata_mash) #it seems like its raw counts
# Logarithmize the data
sc.pp.log1p(adata_mash)
adata_mash_heps = adata_mash[adata_mash.obs['celltype'].isin(['Hepatocytes'])]
adata_mash_heps.obs['donor_demux'].value_counts()

donor_demux
HL221215    5625
HL221006    5105
HL170064    4009
HL170066    3715
HL230212    3495
HL200525    2127
HL220127    1946
HL170055    1943
HL191216    1675
HL200529    1661
HL200925    1505
HL170046    1419
HL210726    1327
HL170058    1281
HL191002    1139
HL160022    1097
HL191025     798
HL201024     780
HL190827     696
HL150013     541
HL221019     391
HL230302     311
HL180071     292
Name: count, dtype: int64

In [11]:
adata_mash_heps.obs['cellsubtype'].value_counts()

cellsubtype
Hepatocytes.Zone2        14148
Hepatocytes.Zone3        14090
Hepatocytes.Zone1         8039
Hepatocytes.Senescent     6083
Hepatocytes.Stress         518
Name: count, dtype: int64

In [ ]:
# remove stress and senescent clusters

In [12]:
adata_mash_heps = adata_mash_heps[~adata_mash_heps.obs['cellsubtype'].isin(['Hepatocytes.Stress'])]
adata_mash_heps.obs['cellsubtype'].value_counts()

cellsubtype
Hepatocytes.Zone2        14148
Hepatocytes.Zone3        14090
Hepatocytes.Zone1         8039
Hepatocytes.Senescent     6083
Name: count, dtype: int64

In [13]:
adata_mash_heps

View of AnnData object with n_obs × n_vars = 42360 × 36601
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_RNA_raw', 'nFeature_RNA_raw', 'donor_demux', 'nCount_SCT', 'nFeature_SCT', 'SCT.weight', 'seurat_clusters', 'log_nCount_SCT', 'log_nFeature_SCT', 'lane', 'batch', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'atac_fragments', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'TSS.enrichment', 'TSS.percentile', 'condition', 'disease_status', 'library', 'amulet', 'nCount_Peaks', 'nFeature_Peaks', 'Description', 'Age', 'BMI', 'Gender', 'Alcoholic..2..Drinks.Day.', 'Steatosis.grade', 'Steatosis..', 'Fat.distribution', 'Lobular.inflammation', 'Ballooning', 'Portal.inflammation', 'Hepatocyte.necrosis', 'MASH.CRN.score..X.8', 'Diagnosis', 'Peaks.weight', 'value', 'barcode', 'cellsubtype', 'celltype', 'nCount_Peaks_Full', 'nFeature_Peaks_Full', 'Fibrosis.stage', 'spatial_annotations'
    var: 'features'
    uns: 'log1p'
    obsm: 'X_umap.atac', 'X_umap.rna', 'X_umap.wnn'

In [14]:
sc_cells = 10000

In [15]:
# User input: Set n_obs to number of cells to keep

sc.pp.subsample(adata_mash_heps, n_obs=sc_cells, random_state=42)

In [16]:
adata_mash_heps

AnnData object with n_obs × n_vars = 10000 × 36601
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_RNA_raw', 'nFeature_RNA_raw', 'donor_demux', 'nCount_SCT', 'nFeature_SCT', 'SCT.weight', 'seurat_clusters', 'log_nCount_SCT', 'log_nFeature_SCT', 'lane', 'batch', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'atac_fragments', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'TSS.enrichment', 'TSS.percentile', 'condition', 'disease_status', 'library', 'amulet', 'nCount_Peaks', 'nFeature_Peaks', 'Description', 'Age', 'BMI', 'Gender', 'Alcoholic..2..Drinks.Day.', 'Steatosis.grade', 'Steatosis..', 'Fat.distribution', 'Lobular.inflammation', 'Ballooning', 'Portal.inflammation', 'Hepatocyte.necrosis', 'MASH.CRN.score..X.8', 'Diagnosis', 'Peaks.weight', 'value', 'barcode', 'cellsubtype', 'celltype', 'nCount_Peaks_Full', 'nFeature_Peaks_Full', 'Fibrosis.stage', 'spatial_annotations'
    var: 'features'
    uns: 'log1p'
    obsm: 'X_umap.atac', 'X_umap.rna', 'X_umap.wnn'

In [ ]:
# no stressed population?

In [17]:
sc.tl.rank_genes_groups(adata_mash_heps, groupby="cellsubtype", use_raw=False)

In [18]:
import pandas as pd
import csv

In [19]:
markers_df_adata_mash_heps = pd.DataFrame(adata_mash_heps.uns["rank_genes_groups"]["names"]).iloc[:, :]

In [20]:
markers_df_adata_mash_heps

,Hepatocytes.Senescent,Hepatocytes.Zone1,Hepatocytes.Zone2,Hepatocytes.Zone3
0,DTNA,CPS1,FGG,SLCO1B3
1,SERPINE1,HAL,FGB,CYP3A4
2,FAT1,PPARGC1A,HP,SLCO1B7
3,KLHL29,SDS,SAA2,ZNF385D
4,ANXA2,INSIG1,C3,CYP2E1
...,...,...,...,...
36596,SLC38A4,ZNF385D-AS2,KLF6,FGF14
36597,PLG,LINC01344,NRG1,FGFR2
36598,ADRA1A,MPPED1,AKR1C1,CREB5
36599,ADGRA3,CYP3A4,CYP3A4,HAL
36600,CYP2C8,ZNF385D,SLCO1B3,PTP4A1

In [21]:
# Iterate through each column and save it to a text file
for celltype in markers_df_adata_mash_heps.columns:
    #celltype = 'Hepatocytes.Senescent'
        # Extract the genes for the current cell type
    genes = markers_df_adata_mash_heps[celltype].dropna()  # Drop any NaN values if present
    
    # Add quotes around each gene
    genes_with_quotes = [f'{gene}' for gene in genes]
    #print(genes.head())
    # Create a dataframe with column name "x"
    output_df = pd.DataFrame(genes_with_quotes, columns=["x"])
    
    
    print(output_df.head())
    # Save to a text file named after the cell type
    output_df.to_csv(f"/tscc/projects/ps-epigen/users/cmiciano/Liver/RNA/scripts/zone_gene_lists/MASH_alldonors_nostress_{celltype}_RNA_Multiome_RankGenesALL.txt",
                     index=False, sep="\t",quoting=csv.QUOTE_ALL)

          x
0      DTNA
1  SERPINE1
2      FAT1
3    KLHL29
4     ANXA2
          x
0      CPS1
1       HAL
2  PPARGC1A
3       SDS
4    INSIG1
      x
0   FGG
1   FGB
2    HP
3  SAA2
4    C3
         x
0  SLCO1B3
1   CYP3A4
2  SLCO1B7
3  ZNF385D
4   CYP2E1

In [22]:

markers_df_adata_mash_heps_top50 = pd.DataFrame(adata_mash_heps.uns["rank_genes_groups"]["names"]).iloc[0:50, :]
markers_df_adata_mash_heps_top50.head()

  Hepatocytes.Senescent Hepatocytes.Zone1 Hepatocytes.Zone2 Hepatocytes.Zone3
0                  DTNA              CPS1               FGG           SLCO1B3
1              SERPINE1               HAL               FGB            CYP3A4
2                  FAT1          PPARGC1A                HP           SLCO1B7
3                KLHL29               SDS              SAA2           ZNF385D
4                 ANXA2            INSIG1                C3            CYP2E1

In [23]:
markers_df_adata_mash_heps_top50.shape # Check out dimensions

(50, 4)

In [24]:
#markers_df_adata_mash_heps_top50

In [25]:
markers_df_adata_mash_heps_top50 = list(np.unique(markers_df_adata_mash_heps_top50.melt().value.values))   # Create an array of the unique markers across all the cell types
len(markers_df_adata_mash_heps_top50)

195

In [19]:
#adata_mash_heps

In [26]:
adata_mash_heps.__dict__['_raw'].__dict__['_var'] = adata_mash_heps.__dict__['_raw'].__dict__['_var'].rename(columns={'_index': 'features'})

In [27]:
import os

In [28]:
gene_nums = 50

export_dir = '/tscc/projects/ps-epigen/users/cmiciano/Liver/RNA/outputs/sandbox/spatial/250214_tangram_preprocessing_genelist50_liver_mash_heps_alldonors_top50_nostress/'

if not os.path.isdir(export_dir):
    os.mkdir(export_dir)

print(export_dir)

/tscc/projects/ps-epigen/users/cmiciano/Liver/RNA/outputs/sandbox/spatial/250214_tangram_preprocessing_genelist50_liver_mash_heps_alldonors_top50_nostress/

In [31]:
#adata_mash_heps

AnnData object with n_obs × n_vars = 10000 × 36601
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_RNA_raw', 'nFeature_RNA_raw', 'donor_demux', 'nCount_SCT', 'nFeature_SCT', 'SCT.weight', 'seurat_clusters', 'log_nCount_SCT', 'log_nFeature_SCT', 'lane', 'batch', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'atac_fragments', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'TSS.enrichment', 'TSS.percentile', 'condition', 'disease_status', 'library', 'amulet', 'nCount_Peaks', 'nFeature_Peaks', 'Description', 'Age', 'BMI', 'Gender', 'Alcoholic..2..Drinks.Day.', 'Steatosis.grade', 'Steatosis..', 'Fat.distribution', 'Lobular.inflammation', 'Ballooning', 'Portal.inflammation', 'Hepatocyte.necrosis', 'MASH.CRN.score..X.8', 'Diagnosis', 'Peaks.weight', 'value', 'barcode', 'cellsubtype', 'celltype', 'nCount_Peaks_Full', 'nFeature_Peaks_Full', 'Fibrosis.stage', 'spatial_annotations'
    var: 'features'
    uns: 'log1p', 'rank_genes_groups'
    obsm: 'X_umap.atac', 'X_umap.rna', 'X_umap.wnn'

In [30]:
# Write out the preprocessed objects to be fed into a python script that runs tangram

adata_mash_heps.write(export_dir + 'Preprocessed_adsc.h5ad')
#ad_sp.write(export_dir + 'Preprocessed_adsp.h5ad')

file = open(export_dir +'markers','w')
for item in markers_df_adata_mash_heps_top50:
	file.write(item+"\n")
file.close()