In [2]:
library(ggplot2)
library(tidyr)
library(dplyr)
library(stringr)

# Create BED files of H3K27ac

In [3]:
make_count_bed_H3K27ac <- function(cell.type, int.filename, bed.filename) {
    exp.mat <- read.table(int.filename)
    
    ct_gtf <- data.frame(str_split(rownames(exp.mat), '[-:]', simplify=T))
    colnames(ct_gtf) <- c('#chr','start','end')
    ct_gtf$gene_id <- rownames(exp.mat)
    
    bed.mat <- cbind(ct_gtf, exp.mat)
    bed.mat <- arrange(bed.mat, `#chr`, start)
    write.table(bed.mat, bed.filename, quote=F, row.names=F, col.names=T, sep='\t')
}

In [5]:
unique_cell_types <- c('Endothelial', 'Hepatocytes', 'T', 'HSC', 'Cholangiocyte', 'Myeloid', 'NK', 'B', 'Mast', 'Schwann')
indir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/counts/'
outdir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/counts/'

##### NAME YOUR FILES #####
for (cell.type in unique_cell_types){
    # Not enough stuff for these cell types
    if (cell.type %in% c('NK','Mast','Schwann','B')) {
        next
    }
    #tmm.filename <- paste(indir, cell.type, '_perdonor.H3K27ac.TMM.tsv', sep = "")
    int.filename <- paste(indir, cell.type, '_perdonor.H3K27ac.INT.ATAC.Peaks.tsv', sep = "")
    bed.filename <- paste(outdir, cell.type, '_perdonor.H3K27ac.INT.ATAC.Peaks.bed', sep = "")
    make_count_bed_H3K27ac(cell.type, int.filename, bed.filename)
}

In [6]:
unique_cell_types <- c('Endothelial', 'Hepatocytes', 'T', 'HSC', 'Cholangiocyte', 'Myeloid', 'NK', 'B', 'Mast', 'Schwann')
indir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/counts/'
outdir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/counts/'

##### NAME YOUR FILES #####
for (cell.type in unique_cell_types){
    # Not enough stuff for these cell types
    if (cell.type %in% c('Mast','Schwann')) {
        next
    }
    #tmm.filename <- paste(indir, cell.type, '_perdonor.H3K27ac.TMM.tsv', sep = "")
    int.filename <- paste(indir, cell.type, '_perdonor.H3K27ac.INT.TSS.tsv', sep = "")
    bed.filename <- paste(outdir, cell.type, '_perdonor.H3K27ac.INT.TSS.bed', sep = "")
    make_count_bed_H3K27ac(cell.type, int.filename, bed.filename)
}

# Create BED files of H3K27me3

In [7]:
make_count_bed_H3K27me3 <- function(cell.type, int.filename, bed.filename) {
    exp.mat <- read.table(int.filename)
    
    ct_gtf <- data.frame(str_split(rownames(exp.mat), '[-:]', simplify=T))
    colnames(ct_gtf) <- c('#chr','start','end')
    ct_gtf$gene_id <- rownames(exp.mat)
    
    bed.mat <- cbind(ct_gtf, exp.mat)
    bed.mat <- arrange(bed.mat, `#chr`, start)
    write.table(bed.mat, bed.filename, quote=F, row.names=F, col.names=T, sep='\t')
}

In [8]:
unique_cell_types <- c('Endothelial', 'Hepatocytes', 'T', 'HSC', 'Cholangiocyte', 'Myeloid', 'NK', 'B', 'Mast', 'Schwann')
indir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/counts/'
outdir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/counts/'

##### NAME YOUR FILES #####
for (cell.type in unique_cell_types){
    # Not enough stuff for these cell types
    if (cell.type %in% c('Mast','Schwann','T','NK','B','HSC')) {
        next
    }
    #tmm.filename <- paste(indir, cell.type, '_perdonor.H3K27me3.TMM.tsv', sep = "")
    int.filename <- paste(indir, cell.type, '_perdonor.H3K27me3.INT.ATAC.Peaks.tsv', sep = "")
    bed.filename <- paste(outdir, cell.type, '_perdonor.H3K27me3.INT.ATAC.Peaks.bed', sep = "")
    make_count_bed_H3K27me3(cell.type, int.filename, bed.filename)
}

In [9]:
unique_cell_types <- c('Endothelial', 'Hepatocytes', 'T', 'HSC', 'Cholangiocyte', 'Myeloid', 'NK', 'B', 'Mast', 'Schwann')
indir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/counts/'
outdir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/counts/'

##### NAME YOUR FILES #####
for (cell.type in unique_cell_types){
    # Not enough stuff for these cell types
    if (cell.type %in% c('NK','B','Mast','Schwann','T')) {
        next
    }
    #tmm.filename <- paste(indir, cell.type, '_perdonor.H3K27me3.TMM.tsv', sep = "")
    int.filename <- paste(indir, cell.type, '_perdonor.H3K27me3.INT.TSS.tsv', sep = "")
    bed.filename <- paste(outdir, cell.type, '_perdonor.H3K27me3.INT.TSS.bed', sep = "")
    make_count_bed_H3K27me3(cell.type, int.filename, bed.filename)
}

# Write out covariates - H3K27ac

In [14]:
construct_cov_mat <- function(pc.filename, geno.pca.filename, meta, n_geno_pcs=10, cov.filename) {
    feat.pca <- read.table(pc.filename)
    colnames(feat.pca) <- paste0('feature.',colnames(feat.pca))
    
    meta.sub <- meta[rownames(feat.pca),]
    
    gene.pca <- read.table(geno.pca.filename)
    rownames(gene.pca) <- NULL
    gene.pca <- tibble::column_to_rownames(gene.pca,var='IID')
    gene.pca <- gene.pca[,paste0('PC', 1:n_geno_pcs)]
    gene.pca <- gene.pca[rownames(feat.pca),]
    colnames(gene.pca) <- paste0('genotype.',colnames(gene.pca))
    
    covar.mat <- cbind(meta.sub, cbind(feat.pca, gene.pca))
    
    covar.mat <- data.frame(t(covar.mat))
    
    write.table(covar.mat, cov.filename, col.names=T, row.names=T, quote=F, sep='\t')
}

In [15]:
meta = read.table("/nfs/lab/projects/nash_nafld_liver/downstream_all/08_H3K27ac_DESEQ/H3K27ac.meta.tsv", 
                  sep='\t', header=T)
#colnames(meta)
meta <- tibble::column_to_rownames(meta, var='donor_demux')
meta$Gender <- as.integer(factor(meta$Gender))
meta$disease_status <- as.integer(factor(meta$disease_status))
meta$batch <- as.integer(factor(meta$batch))
meta$condition <- as.integer(factor(meta$condition, levels=c('Control','MASL','MASH','MetALD')))
meta <- dplyr::select(meta, -Ballooning, -Fat.distribution, -Hepatocyte.necrosis, -Portal.inflammation,
                     -Age, -BMI)

dim(meta)
head(meta)

[1] 86 18

         B  Cholangiocyte Endothelial Hepatocytes HSC Mast Myeloid NK Schwann
HL150001 12  17            58          534         15 1     78     10 0
HL150009  3  11           104          761        116 0     65     17 3
HL150013 22  37           112          281         77 4    100     20 0
HL150015 12  69            89         1266         66 0     59     15 0
HL160017 10  32            71         1476         26 0    234     10 1
HL160022  0 129            45          131         28 0     50      0 2
         T  batch disease_status condition Steatosis.grade Fibrosis.stage
HL150001  4 1     2              2         1               0
HL150009 10 1     2              2         1               0
HL150013 31 3     2              3         1               2
HL150015 22 1     2              2         3               1
HL160017 22 1     2              4         1               2
HL160022  7 3     2              3         3               2
         Lobular.inflammation MASH.CRN.score..X.8 Gender
HL150001 0                    1                   2
HL150009 0                    1                   2
HL150013 1                    3                   2
HL150015 0                    3                   2
HL160017 1                    2                   2
HL160022 1                    5                   1

In [18]:
indir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/covariates/'
outdir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/covariates/'

n_pc <- 15
n_geno_pcs <- 10

geno.pca.filename <- '/nfs/lab/projects/nash_nafld_liver/genotypes/pca/Supplemental_gPCA_data.tsv'

##### NAME YOUR FILES #####
for (cell.type in unique_cell_types){
    # Not enough stuff for these cell types
    if (cell.type %in% c('NK','Mast','Schwann','B')) {
        next
    }
    pc.filename <- paste(outdir, cell.type, '_perdonor.H3K27ac.INT.ATAC.Peaks.', n_pc,'.PCs.tsv', sep = "")
    cov.filename <- paste(outdir, cell.type, '_perdonor.H3K27ac.ATAC.Peaks.covariates.tsv', sep = "")

    construct_cov_mat(pc.filename, geno.pca.filename, meta, n_geno_pcs, cov.filename)
}

In [19]:
indir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/covariates/'
outdir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/covariates/'

n_pc <- 15
n_geno_pcs <- 10

geno.pca.filename <- '/nfs/lab/projects/nash_nafld_liver/genotypes/pca/Supplemental_gPCA_data.tsv'

##### NAME YOUR FILES #####
for (cell.type in unique_cell_types){
    # Not enough stuff for these cell types
    if (cell.type %in% c('Mast','Schwann')) {
        next
    }
    pc.filename <- paste(outdir, cell.type, '_perdonor.H3K27ac.INT.TSS.', n_pc,'.PCs.tsv', sep = "")
    cov.filename <- paste(outdir, cell.type, '_perdonor.H3K27ac.TSS.covariates.tsv', sep = "")

    construct_cov_mat(pc.filename, geno.pca.filename, meta, n_geno_pcs, cov.filename)
}

# Write out covariates - H3K27me3

In [20]:
construct_cov_mat <- function(pc.filename, geno.pca.filename, meta, n_geno_pcs=10, cov.filename) {
    feat.pca <- read.table(pc.filename)
    colnames(feat.pca) <- paste0('feature.',colnames(feat.pca))
    
    meta.sub <- meta[rownames(feat.pca),]
    
    gene.pca <- read.table(geno.pca.filename)
    rownames(gene.pca) <- NULL
    gene.pca <- tibble::column_to_rownames(gene.pca,var='IID')
    gene.pca <- gene.pca[,paste0('PC', 1:n_geno_pcs)]
    gene.pca <- gene.pca[rownames(feat.pca),]
    colnames(gene.pca) <- paste0('genotype.',colnames(gene.pca))
    
    covar.mat <- cbind(meta.sub, cbind(feat.pca, gene.pca))
    
    covar.mat <- data.frame(t(covar.mat))
    
    write.table(covar.mat, cov.filename, col.names=T, row.names=T, quote=F, sep='\t')
}

In [21]:
meta = read.table("/nfs/lab/projects/nash_nafld_liver/downstream_all/09_H3K27me3_DESEQ/H3K27me3.meta.tsv", 
                  sep='\t', header=T)
#colnames(meta)
meta <- tibble::column_to_rownames(meta, var='donor_demux')
meta$Gender <- as.integer(factor(meta$Gender))
meta$disease_status <- as.integer(factor(meta$disease_status))
meta$batch <- as.integer(factor(meta$batch))
meta$condition <- as.integer(factor(meta$condition, levels=c('Control','MASL','MASH','MetALD')))
meta <- dplyr::select(meta, -Ballooning, -Fat.distribution, -Hepatocyte.necrosis, -Portal.inflammation,
                     -Age, -BMI)

dim(meta)
head(meta)

[1] 86 18

         B  Cholangiocyte Endothelial Hepatocytes HSC Mast Myeloid NK Schwann
HL150001  5  18            84          514        22  0     71     15 0
HL150009  5   9            80          713        66  0     83      6 3
HL150013 40  29           106          244        54  3    123     24 1
HL150015 23  64            67         1401        49  0     71     11 2
HL160017  9  28            39         1758        25  0    204      4 0
HL160022  1 149            20          158        23  0     42      2 0
         T  batch disease_status condition Steatosis.grade Fibrosis.stage
HL150001  2 1     2              2         1               0
HL150009 14 1     2              2         1               0
HL150013 28 3     2              3         1               2
HL150015 20 1     2              2         3               1
HL160017 25 1     2              4         1               2
HL160022 13 3     2              3         3               2
         Lobular.inflammation MASH.CRN.score..X.8 Gender
HL150001 0                    1                   2
HL150009 0                    1                   2
HL150013 1                    3                   2
HL150015 0                    3                   2
HL160017 1                    2                   2
HL160022 1                    5                   1

In [24]:
indir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/covariates/'
outdir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/covariates/'

n_pc <- 15
n_geno_pcs <- 10

geno.pca.filename <- '/nfs/lab/projects/nash_nafld_liver/genotypes/pca/Supplemental_gPCA_data.tsv'

##### NAME YOUR FILES #####
for (cell.type in unique_cell_types){
    # Not enough stuff for these cell types
    if (cell.type %in% c('Mast','Schwann','T','NK','B','HSC')) {
        next
    }
    pc.filename <- paste(outdir, cell.type, '_perdonor.H3K27me3.INT.ATAC.Peaks.', n_pc,'.PCs.tsv', sep = "")
    cov.filename <- paste(outdir, cell.type, '_perdonor.H3K27me3.ATAC.Peaks.covariates.tsv', sep = "")

    construct_cov_mat(pc.filename, geno.pca.filename, meta, n_geno_pcs, cov.filename)
}

In [25]:
indir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/covariates/'
outdir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/covariates/'

n_pc <- 15
n_geno_pcs <- 10

geno.pca.filename <- '/nfs/lab/projects/nash_nafld_liver/genotypes/pca/Supplemental_gPCA_data.tsv'

##### NAME YOUR FILES #####
for (cell.type in unique_cell_types){
    # Not enough stuff for these cell types
    if (cell.type %in% c('Mast','Schwann','T','NK','B')) {
        next
    }
    pc.filename <- paste(outdir, cell.type, '_perdonor.H3K27me3.INT.TSS.', n_pc,'.PCs.tsv', sep = "")
    cov.filename <- paste(outdir, cell.type, '_perdonor.H3K27me3.TSS.covariates.tsv', sep = "")

    construct_cov_mat(pc.filename, geno.pca.filename, meta, n_geno_pcs, cov.filename)
}

# VCF

We are going to use a vcf that is filtered, currently we have one with maf .01 and R2 .9, let's keep that but filter to maf .05. Also, we are going to rename the samples to match the count data and covariates.

cd /nfs/lab/projects/nash_nafld_liver/genotypes/imputed
bcftools view merged.dose.r209.maf01.vcf.gz -i 'MAF>0.05' -Oz -o merged.dose.r209.maf05.vcf.gz
bcftools query -l merged.dose.r209.maf05.vcf.gz > qtl.sample.conversion.txt
nano qtl.sample.conversion.txt
bcftools reheader merged.dose.r209.maf05.vcf.gz -s qtl.sample.conversion.txt -o Liver.QTL.r209.maf05.matchednames.vcf
bcftools view Liver.QTL.r209.maf05.matchednames.vcf -Oz -o Liver.QTL.r209.maf05.matchednames.vcf.gz
tabix Liver.QTL.r209.maf05.matchednames.vcf.gz

plink2 --make-bed \
    --output-chr chrM \
    --vcf Liver.QTL.r209.maf05.matchednames.vcf.gz \
    --out Liver.QTL.r209.maf05.matchednames

# Running tensorQTL

#### H3K27ac ATAC Peaks

# The beds need to be sorted:

cd counts
for ct in  $(ls *_perdonor.H3K27ac.INT.ATAC.Peaks.bed  | sed  's/_perdonor.H3K27ac.INT.ATAC.Peaks.bed//g'); do sort -k 1,1 -k2,2n ${ct}_perdonor.H3K27ac.INT.ATAC.Peaks.bed > ${ct}_perdonor.H3K27ac.INT.ATAC.Peaks.sort.bed; chmod 777 ${ct}_perdonor.H3K27ac.INT.ATAC.Peaks.sort.bed; done

# Then make the following script (make.scripts.sh)

#!/bin/bash

for ct in 'Endothelial' 'Hepatocytes' 'T' 'HSC' 'Cholangiocyte' 'Myeloid'; do

    # Create a unique SLURM batch script for each cell type
    batch_script="${ct}_H3K27ac_QTL.sh"

    # Write the batch script
    cat <<EOT > $batch_script
#!/bin/bash
#SBATCH --job-name=${ct}_H3K27ac_QTL      # Job name
#SBATCH --output=${ct}_H3K27ac_QTL_%j.out # Output file (%j will be replaced by job ID)
#SBATCH --error=${ct}_H3K27ac_QTL_%j.err  # Error file
#SBATCH --nodes=1                     # Number of nodes
#SBATCH --partition=a100              # Partition
#SBATCH --account=csd854
#SBATCH --qos=condo-gpu
#SBATCH --ntasks=1                    # Number of tasks
#SBATCH --cpus-per-task=1             # CPUs per task (5 cells in parallel, matches -P 5)
#SBATCH --mem=50G                     # Memory per node
#SBATCH --time=48:00:00               # Time limit (48 hours)
#SBATCH --gpus=2                      # Number of GPUs

plink_prefix_path=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/genotypes/Liver.QTL.r209.maf05.matchednames
expression_bed=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/counts/${ct}_perdonor.H3K27ac.INT.ATAC.Peaks.sort.bed
prefix=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/outs/${ct}
covariates_file=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/covariates/${ct}_perdonor.H3K27ac.ATAC.Peaks.covariates.tsv

echo "Set all variables for ${ct}"

# Run TensorQTL for all SNPs
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis_nominal

echo "Finished running tensorQTL, starting permutations for ${ct}"

# Run TensorQTL to get fdr adjusted lead snps and nominal cutoffs
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis \
    --fdr 0.05

echo "Done with ${ct}"

EOT

        chmod +x ${ct}_H3K27ac_QTL.sh
        
    # Create a unique SLURM batch script for each cell type
    batch_script="${ct}_H3K27ac_QTL_SuSiE.sh"

    # Write the batch script
    cat <<EOT > $batch_script
#!/bin/bash
#SBATCH --job-name=${ct}_H3K27ac_QTL_SuSiE      # Job name
#SBATCH --output=${ct}_H3K27ac_QTL_SuSiE%j.out # Output file (%j will be replaced by job ID)
#SBATCH --error=${ct}_H3K27ac_QTL_SuSiE%j.err  # Error file
#SBATCH --nodes=1                     # Number of nodes
#SBATCH --partition=condo              # Partition
#SBATCH --account=csd854
#SBATCH --qos=condo
#SBATCH --ntasks=1                    # Number of tasks
#SBATCH --cpus-per-task=2             # CPUs per task (5 cells in parallel, matches -P 5)
#SBATCH --mem=50G                     # Memory per node
#SBATCH --time=48:00:00               # Time limit (48 hours)

plink_prefix_path=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/genotypes/Liver.QTL.r209.maf05.matchednames
expression_bed=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/counts/${ct}_perdonor.H3K27ac.INT.ATAC.Peaks.sort.bed
prefix=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/outs/${ct}
covariates_file=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/ATAC.Peaks/covariates/${ct}_perdonor.H3K27ac.ATAC.Peaks.covariates.tsv

echo "Set all variables for ${ct}"

echo "Starting Susie"

# Finemap
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis_susie \
    --cis_output \${prefix}.cis_qtl.txt.gz

echo "Done with ${ct}"

EOT

        chmod +x ${ct}_H3K27ac_QTL_SuSiE.sh

done

In [ ]:
make.scripts.sh
for file in *_H3K27ac_QTL.sh; do echo sbatch $file; done > run_all_ct.sh 
for file in *_H3K27ac_QTL_SuSiE.sh; do echo sbatch $file; done > run_all_ct_SuSiE.sh 
bash run_all_ct.sh
bash run_all_ct_SuSiE.sh

#### H3K27ac TSS

# The beds need to be sorted:

cd counts
for ct in  $(ls *_perdonor.H3K27ac.INT.TSS.bed  | sed  's/_perdonor.H3K27ac.INT.TSS.bed//g'); do sort -k 1,1 -k2,2n ${ct}_perdonor.H3K27ac.INT.TSS.bed > ${ct}_perdonor.H3K27ac.INT.TSS.sort.bed; chmod 777 ${ct}_perdonor.H3K27ac.INT.TSS.sort.bed; done

# Then make the following script (make.scripts.sh)

#!/bin/bash

for ct in 'Endothelial' 'Hepatocytes' 'T' 'HSC' 'Cholangiocyte' 'Myeloid' 'NK' 'B'; do

    # Create a unique SLURM batch script for each cell type
    batch_script="${ct}_H3K27ac_QTL.sh"

    # Write the batch script
    cat <<EOT > $batch_script
#!/bin/bash
#SBATCH --job-name=${ct}_H3K27ac_QTL      # Job name
#SBATCH --output=${ct}_H3K27ac_QTL_%j.out # Output file (%j will be replaced by job ID)
#SBATCH --error=${ct}_H3K27ac_QTL_%j.err  # Error file
#SBATCH --nodes=1                     # Number of nodes
#SBATCH --partition=a100              # Partition
#SBATCH --account=csd854
#SBATCH --qos=condo-gpu
#SBATCH --ntasks=1                    # Number of tasks
#SBATCH --cpus-per-task=1             # CPUs per task (5 cells in parallel, matches -P 5)
#SBATCH --mem=50G                     # Memory per node
#SBATCH --time=48:00:00               # Time limit (48 hours)
#SBATCH --gpus=2                      # Number of GPUs

plink_prefix_path=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/genotypes/Liver.QTL.r209.maf05.matchednames
expression_bed=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/counts/${ct}_perdonor.H3K27ac.INT.TSS.sort.bed
prefix=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/outs/${ct}
covariates_file=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/covariates/${ct}_perdonor.H3K27ac.TSS.covariates.tsv

echo "Set all variables for ${ct}"

# Run TensorQTL for all SNPs
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis_nominal

echo "Finished running tensorQTL, starting permutations for ${ct}"

# Run TensorQTL to get fdr adjusted lead snps and nominal cutoffs
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis \
    --fdr 0.05

echo "Done with ${ct}"

EOT

        chmod +x ${ct}_H3K27ac_QTL.sh
        
    # Create a unique SLURM batch script for each cell type
    batch_script="${ct}_H3K27ac_QTL_SuSiE.sh"

    # Write the batch script
    cat <<EOT > $batch_script
#!/bin/bash
#SBATCH --job-name=${ct}_H3K27ac_QTL_SuSiE      # Job name
#SBATCH --output=${ct}_H3K27ac_QTL_SuSiE%j.out # Output file (%j will be replaced by job ID)
#SBATCH --error=${ct}_H3K27ac_QTL_SuSiE%j.err  # Error file
#SBATCH --nodes=1                     # Number of nodes
#SBATCH --partition=condo              # Partition
#SBATCH --account=csd854
#SBATCH --qos=condo
#SBATCH --ntasks=1                    # Number of tasks
#SBATCH --cpus-per-task=2             # CPUs per task (5 cells in parallel, matches -P 5)
#SBATCH --mem=50G                     # Memory per node
#SBATCH --time=48:00:00               # Time limit (48 hours)

plink_prefix_path=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/genotypes/Liver.QTL.r209.maf05.matchednames
expression_bed=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/counts/${ct}_perdonor.H3K27ac.INT.TSS.sort.bed
prefix=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/outs/${ct}
covariates_file=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/TSS/covariates/${ct}_perdonor.H3K27ac.TSS.covariates.tsv

echo "Set all variables for ${ct}"

echo "Starting Susie"

# Finemap
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis_susie \
    --cis_output \${prefix}.cis_qtl.txt.gz

echo "Done with ${ct}"

EOT

        chmod +x ${ct}_H3K27ac_QTL_SuSiE.sh

done

In [ ]:
make.scripts.sh
for file in *_H3K27ac_QTL.sh; do echo sbatch $file; done > run_all_ct.sh 
for file in *_H3K27ac_QTL_SuSiE.sh; do echo sbatch $file; done > run_all_ct_SuSiE.sh 
bash run_all_ct.sh
bash run_all_ct_SuSiE.sh

#### H3K27me3 ATAC Peaks

# The beds need to be sorted:

cd counts
for ct in  $(ls *_perdonor.H3K27me3.INT.ATAC.Peaks.bed  | sed  's/_perdonor.H3K27me3.INT.ATAC.Peaks.bed//g'); do sort -k 1,1 -k2,2n ${ct}_perdonor.H3K27me3.INT.ATAC.Peaks.bed > ${ct}_perdonor.H3K27me3.INT.ATAC.Peaks.sort.bed; chmod 777 ${ct}_perdonor.H3K27me3.INT.ATAC.Peaks.sort.bed; done

# Then make the following script (make.scripts.sh)

#!/bin/bash

for ct in 'Endothelial' 'Hepatocytes' 'Cholangiocyte' 'Myeloid'; do

    # Create a unique SLURM batch script for each cell type
    batch_script="${ct}_H3K27me3_QTL.sh"

    # Write the batch script
    cat <<EOT > $batch_script
#!/bin/bash
#SBATCH --job-name=${ct}_H3K27me3_QTL      # Job name
#SBATCH --output=${ct}_H3K27me3_QTL_%j.out # Output file (%j will be replaced by job ID)
#SBATCH --error=${ct}_H3K27me3_QTL_%j.err  # Error file
#SBATCH --nodes=1                     # Number of nodes
#SBATCH --partition=a100              # Partition
#SBATCH --account=csd854
#SBATCH --qos=condo-gpu
#SBATCH --ntasks=1                    # Number of tasks
#SBATCH --cpus-per-task=1             # CPUs per task (5 cells in parallel, matches -P 5)
#SBATCH --mem=50G                     # Memory per node
#SBATCH --time=48:00:00               # Time limit (48 hours)
#SBATCH --gpus=2                      # Number of GPUs

plink_prefix_path=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/genotypes/Liver.QTL.r209.maf05.matchednames
expression_bed=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/counts/${ct}_perdonor.H3K27me3.INT.ATAC.Peaks.sort.bed
prefix=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/outs/${ct}
covariates_file=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/covariates/${ct}_perdonor.H3K27me3.ATAC.Peaks.covariates.tsv

echo "Set all variables for ${ct}"

# Run TensorQTL for all SNPs
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis_nominal

echo "Finished running tensorQTL, starting permutations for ${ct}"

# Run TensorQTL to get fdr adjusted lead snps and nominal cutoffs
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis \
    --fdr 0.05

echo "Done with ${ct}"

EOT

        chmod +x ${ct}_H3K27me3_QTL.sh
        
    # Create a unique SLURM batch script for each cell type
    batch_script="${ct}_H3K27me3_QTL_SuSiE.sh"

    # Write the batch script
    cat <<EOT > $batch_script
#!/bin/bash
#SBATCH --job-name=${ct}_H3K27me3_QTL_SuSiE      # Job name
#SBATCH --output=${ct}_H3K27me3_QTL_SuSiE%j.out # Output file (%j will be replaced by job ID)
#SBATCH --error=${ct}_H3K27me3_QTL_SuSiE%j.err  # Error file
#SBATCH --nodes=1                     # Number of nodes
#SBATCH --partition=condo              # Partition
#SBATCH --account=csd854
#SBATCH --qos=condo
#SBATCH --ntasks=1                    # Number of tasks
#SBATCH --cpus-per-task=2             # CPUs per task (5 cells in parallel, matches -P 5)
#SBATCH --mem=50G                     # Memory per node
#SBATCH --time=48:00:00               # Time limit (48 hours)

plink_prefix_path=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/genotypes/Liver.QTL.r209.maf05.matchednames
expression_bed=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/counts/${ct}_perdonor.H3K27me3.INT.ATAC.Peaks.sort.bed
prefix=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/outs/${ct}
covariates_file=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/ATAC.Peaks/covariates/${ct}_perdonor.H3K27me3.ATAC.Peaks.covariates.tsv

echo "Set all variables for ${ct}"

echo "Starting Susie"

# Finemap
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis_susie \
    --cis_output \${prefix}.cis_qtl.txt.gz

echo "Done with ${ct}"

EOT

        chmod +x ${ct}_H3K27me3_QTL_SuSiE.sh

done

In [ ]:
make.scripts.sh
for file in *_H3K27me3_QTL.sh; do echo sbatch $file; done > run_all_ct.sh 
for file in *_H3K27me3_QTL_SuSiE.sh; do echo sbatch $file; done > run_all_ct_SuSiE.sh 
bash run_all_ct.sh
bash run_all_ct_SuSiE.sh

#### H3K27me3 TSS

# The beds need to be sorted:

cd counts
for ct in  $(ls *_perdonor.H3K27me3.INT.TSS.bed  | sed  's/_perdonor.H3K27me3.INT.TSS.bed//g'); do sort -k 1,1 -k2,2n ${ct}_perdonor.H3K27me3.INT.TSS.bed > ${ct}_perdonor.H3K27me3.INT.TSS.sort.bed; chmod 777 ${ct}_perdonor.H3K27me3.INT.TSS.sort.bed; done

# Then make the following script (make.scripts.sh)

#!/bin/bash

for ct in 'Endothelial' 'Hepatocytes' 'HSC' 'Cholangiocyte' 'Myeloid'; do

    # Create a unique SLURM batch script for each cell type
    batch_script="${ct}_H3K27me3_QTL.sh"

    # Write the batch script
    cat <<EOT > $batch_script
#!/bin/bash
#SBATCH --job-name=${ct}_H3K27me3_QTL      # Job name
#SBATCH --output=${ct}_H3K27me3_QTL_%j.out # Output file (%j will be replaced by job ID)
#SBATCH --error=${ct}_H3K27me3_QTL_%j.err  # Error file
#SBATCH --nodes=1                     # Number of nodes
#SBATCH --partition=a100              # Partition
#SBATCH --account=csd854
#SBATCH --qos=condo-gpu
#SBATCH --ntasks=1                    # Number of tasks
#SBATCH --cpus-per-task=1             # CPUs per task (5 cells in parallel, matches -P 5)
#SBATCH --mem=50G                     # Memory per node
#SBATCH --time=48:00:00               # Time limit (48 hours)
#SBATCH --gpus=2                      # Number of GPUs

plink_prefix_path=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/genotypes/Liver.QTL.r209.maf05.matchednames
expression_bed=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/counts/${ct}_perdonor.H3K27me3.INT.TSS.sort.bed
prefix=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/outs/${ct}
covariates_file=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/covariates/${ct}_perdonor.H3K27me3.TSS.covariates.tsv

echo "Set all variables for ${ct}"

# Run TensorQTL for all SNPs
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis_nominal

echo "Finished running tensorQTL, starting permutations for ${ct}"

# Run TensorQTL to get fdr adjusted lead snps and nominal cutoffs
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis \
    --fdr 0.05

echo "Done with ${ct}"

EOT

        chmod +x ${ct}_H3K27me3_QTL.sh
        
    # Create a unique SLURM batch script for each cell type
    batch_script="${ct}_H3K27me3_QTL_SuSiE.sh"

    # Write the batch script
    cat <<EOT > $batch_script
#!/bin/bash
#SBATCH --job-name=${ct}_H3K27me3_QTL_SuSiE      # Job name
#SBATCH --output=${ct}_H3K27me3_QTL_SuSiE%j.out # Output file (%j will be replaced by job ID)
#SBATCH --error=${ct}_H3K27me3_QTL_SuSiE%j.err  # Error file
#SBATCH --nodes=1                     # Number of nodes
#SBATCH --partition=condo              # Partition
#SBATCH --account=csd854
#SBATCH --qos=condo
#SBATCH --ntasks=1                    # Number of tasks
#SBATCH --cpus-per-task=2             # CPUs per task (5 cells in parallel, matches -P 5)
#SBATCH --mem=50G                     # Memory per node
#SBATCH --time=48:00:00               # Time limit (48 hours)

plink_prefix_path=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/genotypes/Liver.QTL.r209.maf05.matchednames
expression_bed=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/counts/${ct}_perdonor.H3K27me3.INT.TSS.sort.bed
prefix=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/outs/${ct}
covariates_file=/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/TSS/covariates/${ct}_perdonor.H3K27me3.TSS.covariates.tsv

echo "Set all variables for ${ct}"

echo "Starting Susie"

# Finemap
python3 -m tensorqtl \${plink_prefix_path} \${expression_bed} \${prefix} \
    --covariates \${covariates_file} \
    --mode cis_susie \
    --cis_output \${prefix}.cis_qtl.txt.gz

echo "Done with ${ct}"

EOT

        chmod +x ${ct}_H3K27me3_QTL_SuSiE.sh

done

In [ ]:
make.scripts.sh
for file in *_H3K27me3_QTL.sh; do echo sbatch $file; done > run_all_ct.sh 
for file in *_H3K27me3_QTL_SuSiE.sh; do echo sbatch $file; done > run_all_ct_SuSiE.sh 
bash run_all_ct.sh
bash run_all_ct_SuSiE.sh