In [1]:
library(dplyr)
library(stringr)
library(tidyr)

Warning message:
“package ‘dplyr’ was built under R version 4.3.2”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“package ‘stringr’ was built under R version 4.3.2”

In [9]:
MVP.cred.set.bed <- read.table('/nfs/lab/tscc/welison/FNIH.Liver/GWAS/NAFLD.TRANS.MVP.2021.credset.hg38.tsv',
                              sep='\t', header=T)

dim(MVP.cred.set.bed)
head(MVP.cred.set.bed)

[1] 1084   18

  CS.Type    LEAD.SNP    CS.SNP      Chr Position  EA NEA EAF   Beta   SE
1 Single SNP rs2642438   rs2642438   1   220970028 A  G   0.274 -0.075 0.0074
2            rs6734238   rs6734238   2   113841030 G  A   0.407 -0.057 0.0064
3            rs138033684 rs138033684 6    71895252 G  T   0.006  0.677 0.1120
4            rs2980888   rs2980888   8   126507308 T  C   0.286  0.130 0.0072
5            rs4484649   rs4484649   8    10571491 C  A   0.419  0.045 0.0066
6            rs4841132   rs4841132   8     9183596 A  G   0.106  0.123 0.0105
  P        N      PP     Nominated.Gene     Biological.Prior.Gene chr.hg38
1 6.65e-24 218595 96.86% MTARC1             MTARC1                1
2 4.94e-19 218595 99.04% IL1RN              IL1RN                 2
3 1.42e-09  37364 96.31% OGFRL1             OGFRL1                6
4 4.21e-72 218595 99.95% lnc-TRIB1-2;WASHC5 TRIB1                 8
5 1.38e-11 218595 98.51% SOX7;RP1L1;C8orf74 RP1L1;SOX7            8
6 6.62e-32 218595 98.79% PPP1R3B            PPP1R3B;TNKS;MFHAS1   8
  end.hg38  start.hg38
1 220796686 220796685
2 113083453 113083452
3  71185549  71185548
4 125495066 125495065
5  10713981  10713980
6   9326086   9326085

In [15]:
# SCHEMA: ["chr", "start", "end", "1" - name, "2" - score, "3" - strand, "4" - signal value, "5" - pValue, "6" - qValue, "summit"- ]

MVP.narrow.1k <- mutate(MVP.cred.set.bed, start=start.hg38-500, end=start.hg38+499, summit=500,
      strand='+',name=paste0(chr.hg38,':',end.hg38,':',NEA,':',EA),
      chr=paste0('chr',chr.hg38)) %>%
    select(chr, start, end, 
       name, score=PP, strand,
       signal=Beta, pValue=P, qValue=SE, summit)

dim(MVP.narrow.1k)
head(MVP.narrow.1k)

[1] 1084   10

  chr  start     end       name            score  strand signal pValue   qValue
1 chr1 220796185 220797184 1:220796686:G:A 96.86% +      -0.075 6.65e-24 0.0074
2 chr2 113082952 113083951 2:113083453:A:G 99.04% +      -0.057 4.94e-19 0.0064
3 chr6  71185048  71186047 6:71185549:T:G  96.31% +       0.677 1.42e-09 0.1120
4 chr8 125494565 125495564 8:125495066:C:T 99.95% +       0.130 4.21e-72 0.0072
5 chr8  10713480  10714479 8:10713981:A:C  98.51% +       0.045 1.38e-11 0.0066
6 chr8   9325585   9326584 8:9326086:G:A   98.79% +       0.123 6.62e-32 0.0105
  summit
1 500
2 500
3 500
4 500
5 500
6 500

In [16]:
write.table(MVP.narrow.1k, '/nfs/lab/tscc/welison/FNIH.Liver/13_chromBPNet_Peaks/variant_prediction/chrombpnet_plotting/250303_WE_MVP_hg38_credible_set_1k.narrowPeak',
           sep='\t', col.names=F, row.names=F, quote=F)