In [2]:
library(tidyr)
library(stringr)
library(vroom)
library(data.table)
options(scipen = 999)
library(biomaRt)
library(dplyr)

Warning message:
“package ‘stringr’ was built under R version 4.3.2”
Warning message:
“package ‘biomaRt’ was built under R version 4.3.2”
Warning message:
“package ‘dplyr’ was built under R version 4.3.2”

Attaching package: ‘dplyr’


The following object is masked from ‘package:biomaRt’:

    select


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [3]:
# Setup directories
traits.dir = "/nfs/lab/FinnGen_R11/finemap/summary/"
finrich.dir = '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/'
traits.bed.dir = "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH//traits/"

# DESeq Reuslts Bed

In [4]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/02_DESEQ_ATAC/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [5]:
list.files(deseq.outdir, pattern='.dds.res')

 [1] "B_Age.dds.res"
 [2] "B_Age.scaled.dds.res"
 [3] "B_BMI.dds.res"
 [4] "B_BMI.scaled.dds.res"
 [5] "B_Fibrosis.stage.dds.res"
 [6] "B_Lobular.inflammation.dds.res"
 [7] "B_MASH_ALL_vs_Control.dds.res"
 [8] "B_MASH_vs_Control.dds.res"
 [9] "B_MASH.CRN.score..X.8.dds.res"
[10] "B_MASL_vs_Control.dds.res"
[11] "B_MetALD_vs_Control.dds.res"
[12] "B_Steatosis.grade.dds.res"
[13] "Cholangiocyte_Age.dds.res"
[14] "Cholangiocyte_Age.scaled.dds.res"
[15] "Cholangiocyte_BMI.dds.res"
[16] "Cholangiocyte_BMI.scaled.dds.res"
[17] "Cholangiocyte_Fibrosis.stage.dds.res"
[18] "Cholangiocyte_Lobular.inflammation.dds.res"
[19] "Cholangiocyte_MASH_ALL_vs_Control.dds.res"
[20] "Cholangiocyte_MASH_vs_Control.dds.res"
[21] "Cholangiocyte_MASH.CRN.score..X.8.dds.res"
[22] "Cholangiocyte_MASL_vs_Control.dds.res"
[23] "Cholangiocyte_MetALD_vs_Control.dds.res"
[24] "Cholangiocyte_Steatosis.grade.dds.res"
[25] "Endothelial_Age.dds.res"
[26] "Endothelial_Age.scaled.dds.res"
[27] "Endothelial_BMI.dds.res"
[28] "Endothelial_BMI.scaled.dds.res"
[29] "Endothelial_Fibrosis.stage.dds.res"
[30] "Endothelial_Lobular.inflammation.dds.res"
[31] "Endothelial_MASH_ALL_vs_Control.dds.res"
[32] "Endothelial_MASH_vs_Control.dds.res"
[33] "Endothelial_MASH.CRN.score..X.8.dds.res"
[34] "Endothelial_MASL_vs_Control.dds.res"
[35] "Endothelial_MetALD_vs_Control.dds.res"
[36] "Endothelial_Steatosis.grade.dds.res"
[37] "Hepatocytes_Age.dds.res"
[38] "Hepatocytes_Age.scaled.dds.res"
[39] "Hepatocytes_BMI.dds.res"
[40] "Hepatocytes_BMI.scaled.dds.res"
[41] "Hepatocytes_Fibrosis.stage.dds.res"
[42] "Hepatocytes_Lobular.inflammation.dds.res"
[43] "Hepatocytes_MASH_ALL_vs_Control.dds.res"
[44] "Hepatocytes_MASH_vs_Control.dds.res"
[45] "Hepatocytes_MASH.CRN.score..X.8.dds.res"
[46] "Hepatocytes_MASL_vs_Control.dds.res"
[47] "Hepatocytes_MetALD_vs_Control.dds.res"
[48] "Hepatocytes_Steatosis.grade.dds.res"
[49] "HSC_Age.dds.res"
[50] "HSC_Age.scaled.dds.res"
[51] "HSC_BMI.dds.res"
[52] "HSC_BMI.scaled.dds.res"
[53] "HSC_Fibrosis.stage.dds.res"
[54] "HSC_Lobular.inflammation.dds.res"
[55] "HSC_MASH_ALL_vs_Control.dds.res"
[56] "HSC_MASH_vs_Control.dds.res"
[57] "HSC_MASH.CRN.score..X.8.dds.res"
[58] "HSC_MASL_vs_Control.dds.res"
[59] "HSC_MetALD_vs_Control.dds.res"
[60] "HSC_Steatosis.grade.dds.res"
[61] "Myeloid_Age.dds.res"
[62] "Myeloid_Age.scaled.dds.res"
[63] "Myeloid_BMI.dds.res"
[64] "Myeloid_BMI.scaled.dds.res"
[65] "Myeloid_Fibrosis.stage.dds.res"
[66] "Myeloid_Lobular.inflammation.dds.res"
[67] "Myeloid_MASH_ALL_vs_Control.dds.res"
[68] "Myeloid_MASH_vs_Control.dds.res"
[69] "Myeloid_MASH.CRN.score..X.8.dds.res"
[70] "Myeloid_MASL_vs_Control.dds.res"
[71] "Myeloid_MetALD_vs_Control.dds.res"
[72] "Myeloid_Steatosis.grade.dds.res"
[73] "NK_Age.dds.res"
[74] "NK_Age.scaled.dds.res"
[75] "NK_BMI.dds.res"
[76] "NK_BMI.scaled.dds.res"
[77] "NK_Fibrosis.stage.dds.res"
[78] "NK_Lobular.inflammation.dds.res"
[79] "NK_MASH_ALL_vs_Control.dds.res"
[80] "NK_MASH_vs_Control.dds.res"
[81] "NK_MASH.CRN.score..X.8.dds.res"
[82] "NK_MASL_vs_Control.dds.res"
[83] "NK_MetALD_vs_Control.dds.res"
[84] "NK_Steatosis.grade.dds.res"
[85] "T_Age.dds.res"
[86] "T_Age.scaled.dds.res"
[87] "T_BMI.dds.res"
[88] "T_BMI.scaled.dds.res"
[89] "T_Fibrosis.stage.dds.res"
[90] "T_Lobular.inflammation.dds.res"
[91] "T_MASH_ALL_vs_Control.dds.res"
[92] "T_MASH_vs_Control.dds.res"
[93] "T_MASH.CRN.score..X.8.dds.res"
[94] "T_MASL_vs_Control.dds.res"
[95] "T_MetALD_vs_Control.dds.res"
[96] "T_Steatosis.grade.dds.res"

In [6]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'ATAC.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'ATAC.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'ATAC.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'ATAC.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

In [7]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/08_H3K27ac_DESEQ/H3K27ac.peak.mats/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [8]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

In [9]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/09_H3K27me3_DESEQ/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [10]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "T:Fibrosis.stage.dds.res"

# H3K27ac ATAC Sites

In [11]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/08_H3K27ac_DESEQ/ATAC_Peaks/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [12]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_ATAC_Peaks.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_ATAC_Peaks.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_ATAC_Peaks.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_ATAC_Peaks.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Ballooning.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

# H3K27ac TSS

In [13]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/08_H3K27ac_DESEQ/tss/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [14]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_TSS.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_TSS.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_TSS.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_TSS.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

# H3K27me3 ATAC Sites

In [15]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/09_H3K27me3_DESEQ/ATAC_Peaks/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [16]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_ATAC_Peaks.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_ATAC_Peaks.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_ATAC_Peaks.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_ATAC_Peaks.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

# H3K27me3 TSS Sites

In [17]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/09_H3K27me3_DESEQ/tss/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [18]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_TSS.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_TSS.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_TSS.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_TSS.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

# Not in latest run

Yang's correlation sites moved to:
/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites (which is /nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/* on ophelia)
Also to: /nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/sites/

In [209]:
ref.deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/background/old.atac.deseq/'
back.bed.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/background/'

In [215]:
for (file in list.files(ref.deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(ref.deseq.outdir, file))
    res <- distinct(res)
    
    write.table(str_split(unique(rownames(res)), "[-:]", simplify=T),
            paste0(back.bed.dir, cell, "_DEfibrosis_atac_peaks.bed"), sep='\t', col.names=F, row.names=F, quote=F)
}

[1] "B:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "T:Fibrosis.stage.dds.res"

In [214]:
file <- list.files(ref.deseq.outdir, pattern='.dds.res')[1]
cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]

file
cell
contrast

[1] "B_Fibrosis.stage.dds.res"

[1] "B"

[1] "Fibrosis.stage.dds.res"

# Cell type specific units - ATAC

In [33]:
ct_5k <- read.table('/nfs/lab/mkim/Liver_Multiome/downstream/entropy_outputs/ATAC_ct_specific_cREs_lowest5k_CPM5.csv', header=T, sep=',')
dim(ct_5k)
head(ct_5k)

table(ct_5k$cell_type)

for (ct in unique(ct_5k$cell_type)) {
    ct_sub <- filter(ct_5k, cell_type==ct)
    write.table(str_split(unique(ct_sub$peak), "[-:]", simplify=T),
            paste0(bed.dir, ct, "_specific_5k.bed"), sep='\t', col.names=F, row.names=F, quote=F)
}

[1] 50000     4

  peak                      cell_type entropy   ct_cpm
1 chr3-160096878-160097077  Mast      0.2030185 119.04053
2 chr21-20797423-20797622   Mast      0.2198497 119.04053
3 chr2-132352920-132353119  Mast      0.8559688 119.04053
4 chr12-119988732-119989032 T         2.5023991  89.24170
5 chr10-103618850-103619150 Mast      1.6399602  81.21255
6 chr13-97367152-97367452   Mast      0.9933904  78.70493

            B Cholangiocyte   Endothelial   Hepatocytes           HSC
         5000          5000          5000          5000          5000
         Mast       Myeloid            NK       Schwann             T
         5000          5000          5000          5000          5000

In [34]:
subct_5k <- read.table('/nfs/lab/mkim/Liver_Multiome/downstream/entropy_outputs/all_cellsubtypes/ATAC_cst_specific_cREs_lowest5k_CPM5.csv', header=T, sep=',')
dim(subct_5k)
head(subct_5k)

table(subct_5k$cell_type)

for (ct in unique(subct_5k$cell_type)) {
    ct_sub <- filter(subct_5k, cell_type==ct)
    write.table(str_split(unique(ct_sub$peak), "[-:]", simplify=T),
            paste0(bed.dir, ct, "_subtype_specific_5k.bed"), sep='\t', col.names=F, row.names=F, quote=F)
}

[1] 96119     4

  peak                      cell_type                entropy   ct_cpm
1 chr21-20797423-20797622   Mast                     0.3966364 110.33874
2 chr3-160096878-160097077  Mast                     0.4435805 110.33874
3 chr2-132352920-132353119  Mast                     1.9181191 110.33874
4 chr17-31487737-31488037   NK                       3.9350405  98.88310
5 chr9-134025109-134025409  Central.Vein.Endothelial 4.4307652  84.88989
6 chr12-119988732-119989032 T                        3.5733255  84.53504

              Activated.HSC                           B
                       3910                        5000
   Central.Vein.Endothelial               Cholangiocyte
                       4237                        5000
      Hepatocytes.Senescent          Hepatocytes.Stress
                       2396                        5000
          Hepatocytes.Zone1           Hepatocytes.Zone2
                       3709                        1142
          Hepatocytes.Zone3                     Kupffer
                       3451                        5000
Lipid.Associated.Macrophage       Lymphatic.Endothelial
                       5000                        5000
                 Macrophage                        Mast
                       3975                        5000
                Mesenchymal                          NK
                       4980                        5000
                     Plasma                Quescent.HSC
                       5000                        5000
                    Schwann      Sinusoidal.Endothelial
                       5000                        5000
                          T        Vascular.Endothelial
                       5000                        3319

In [35]:
Hepato_5k <- read.table('/nfs/lab/mkim/Liver_Multiome/downstream/entropy_outputs/Hepatocytes/Hepatocytes_ATAC_ct_specific_cREs_lowest5k_CPM5.csv', header=T, sep=',')
dim(Hepato_5k)
head(Hepato_5k)

table(Hepato_5k$cell_type)

for (ct in unique(Hepato_5k$cell_type)) {
    ct_sub <- filter(Hepato_5k, cell_type==ct)
    write.table(str_split(unique(ct_sub$peak), "[-:]", simplify=T),
            paste0(bed.dir, ct, "_Hepatocytes_specific_5k.bed"), sep='\t', col.names=F, row.names=F, quote=F)
}

[1] 23915     4

  peak                     cell_type          entropy  ct_cpm
1 chr18-67516743-67517043  Hepatocytes.Zone1  2.308261 77.82831
2 chr2-221573520-221573820 Hepatocytes.Stress 2.003672 76.11995
3 chr15-48331259-48331559  Hepatocytes.Stress 2.046356 74.82641
4 chr4-48341157-48341457   Hepatocytes.Zone3  2.309178 74.32989
5 chr1-11671550-11671850   Hepatocytes.Stress 1.961561 70.05118
6 chr11-67805735-67806035  Hepatocytes.Zone1  2.301523 70.00295

Hepatocytes.Senescent    Hepatocytes.Stress     Hepatocytes.Zone1
                 5000                  5000                  5000
    Hepatocytes.Zone2     Hepatocytes.Zone3
                 3915                  5000

In [36]:
Endo_5k <- read.table('/nfs/lab/mkim/Liver_Multiome/downstream/entropy_outputs/Endothelial/Endothelial_ATAC_ct_specific_cREs_lowest5k_CPM5.csv', header=T, sep=',')
dim(Endo_5k)
head(Endo_5k)

table(Endo_5k$cell_type)

for (ct in unique(Endo_5k$cell_type)) {
    ct_sub <- filter(Endo_5k, cell_type==ct)
    write.table(str_split(unique(ct_sub$peak), "[-:]", simplify=T),
            paste0(bed.dir, ct, "_Endothelial_specific_5k.bed"), sep='\t', col.names=F, row.names=F, quote=F)
}

[1] 20000     4

  peak                     cell_type                entropy   ct_cpm
1 chr19-703929-704229      Central.Vein.Endothelial 1.8434006 91.32268
2 chr20-46689516-46689816  Central.Vein.Endothelial 1.8467018 82.78426
3 chr1-19449084-19449384   Lymphatic.Endothelial    1.3081102 79.21762
4 chr19-3326991-3327291    Lymphatic.Endothelial    0.9828938 75.82248
5 chr2-172308520-172308820 Lymphatic.Endothelial    1.0469458 73.55932
6 chr15-96158858-96159158  Lymphatic.Endothelial    1.2353829 70.72949

Central.Vein.Endothelial    Lymphatic.Endothelial   Sinusoidal.Endothelial
                    5000                     5000                     5000
    Vascular.Endothelial
                    5000

In [37]:
HSC_5k <- read.table('/nfs/lab/mkim/Liver_Multiome/downstream/entropy_outputs/HSC/HSC_ATAC_ct_specific_cREs_lowest5k_CPM5.csv', header=T, sep=',')
dim(HSC_5k)
head(HSC_5k)

table(HSC_5k$cell_type)

for (ct in unique(HSC_5k$cell_type)) {
    ct_sub <- filter(HSC_5k, cell_type==ct)
    write.table(str_split(unique(ct_sub$peak), "[-:]", simplify=T),
            paste0(bed.dir, ct, "_HSC_specific_5k.bed"), sep='\t', col.names=F, row.names=F, quote=F)
}

[1] 15000     4

  peak                      cell_type   entropy   ct_cpm
1 chr2-217858689-217858989  Mesenchymal 1.3800006 51.74125
2 chr8-22551681-22551981    Mesenchymal 1.4817848 47.58591
3 chr19-15195398-15195698   Mesenchymal 1.1747888 47.04157
4 chr11-119317076-119317376 Mesenchymal 0.8961375 45.00953
5 chr8-141401487-141401787  Mesenchymal 1.3012750 44.58585
6 chr2-169733723-169734023  Mesenchymal 1.4632432 43.51730

Activated.HSC   Mesenchymal  Quescent.HSC
         5000          5000          5000

In [38]:
Myeloid_5k <- read.table('/nfs/lab/mkim/Liver_Multiome/downstream/entropy_outputs/Myeloid/Myeloid_ATAC_ct_specific_cREs_lowest5k_CPM5.csv', header=T, sep=',')
dim(Myeloid_5k)
head(Myeloid_5k)

table(Myeloid_5k$cell_type)

for (ct in unique(Myeloid_5k$cell_type)) {
    ct_sub <- filter(Myeloid_5k, cell_type==ct)
    write.table(str_split(unique(ct_sub$peak), "[-:]", simplify=T),
            paste0(bed.dir, ct, "_Myeloid_specific_5k.bed"), sep='\t', col.names=F, row.names=F, quote=F)
}

[1] 15000     4

  peak                     cell_type                   entropy  ct_cpm
1 chr9-127569023-127569323 Macrophage                  1.549487 53.90940
2 chr12-76031534-76031834  Lipid.Associated.Macrophage 1.516928 49.50372
3 chr17-81346172-81346472  Macrophage                  1.544856 49.49422
4 chr21-45643238-45643538  Macrophage                  1.545914 46.73721
5 chr15-82046942-82047242  Macrophage                  1.565957 45.55482
6 chr19-703773-704073      Macrophage                  1.465763 43.32757

                    Kupffer Lipid.Associated.Macrophage
                       5000                        5000
                 Macrophage
                       5000

# Write Backround sets  
Need to remove doublets

Multiome:
cp /nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/celltype.peaks/*_union.* .

In [34]:
cells <- unlist(read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call/listofcells.txt'))
cells

back.bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/background/'

for (c in cells) {
    peak.tab <- read.table(paste0('/nfs/lab/projects/nash_nafld_liver/downstream_all/DPT.files/10.conserved_peaks/celltype_H3K27me3/FNIH_liver_H3K27me3.', 
                                   c, '.bed'))
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27me3.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
}

for (c in cells) {
    peak.tab <- read.table(paste0('/nfs/lab/projects/nash_nafld_liver/downstream_all/DPT.files/10.conserved_peaks/celltype_H3K27ac/FNIH_liver_H3K27ac.', 
                                   c, '.bed'))
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27ac.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
}

            V11             V12             V13             V14             V15
            "B" "Cholangiocyte"   "Endothelial"   "Hepatocytes"           "HSC"
            V16             V17             V18             V19            V110
         "Mast"       "Myeloid"            "NK"       "Schwann"             "T"

In [35]:
# Get TSS sites
for (c in cells) {
    peak.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/DPT.files/tss_mtx/',c,'_H3K27ac_donor_count.CPM.xls')) %>%
        rownames() %>%
        str_split('-|:', simplify=T) %>%
        as.data.frame()
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27ac_TSS.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
    
    peak.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/DPT.files/tss_mtx/',c,'_H3K27me3_donor_count.CPM.xls')) %>%
        rownames() %>%
        str_split('-|:', simplify=T) %>%
        as.data.frame()
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27me3_TSS.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
}

In [36]:
# Get ATAC sites
for (c in cells) {
    peak.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/DPT.files/LiverUnionPeak_mtx/',c,'_H3K27ac_donor.LiverUnionPeaks.cpm.ct.peaks.tsv')) %>%
        rownames() %>%
        str_split('-|:', simplify=T) %>%
        as.data.frame()
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27ac_ATAC_Peaks.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
    
    peak.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/DPT.files/LiverUnionPeak_mtx/',c,'_H3K27me3_donor.LiverUnionPeaks.cpm.ct.peaks.tsv')) %>%
        rownames() %>%
        str_split('-|:', simplify=T) %>%
        as.data.frame()
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27me3_ATAC_Peaks.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
}

In [29]:
# Get specificity backgrounds (run in terminal)

cd /nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/background/
tail -n +2 /nfs/lab/tscc/welison/FNIH.Liver/subtypes/Hepatocytes/LiverUnionPeaks.bed >  Hepatocyte_only_union_peaks.bed
tail -n +2 /nfs/lab/tscc/welison/FNIH.Liver/subtypes/Endothelial/LiverUnionPeaks.bed >  Endothelial_only_union_peaks.bed
tail -n +2 /nfs/lab/tscc/welison/FNIH.Liver/subtypes/HSC/LiverUnionPeaks.bed >  HSC_only_union_peaks.bed
tail -n +2 /nfs/lab/tscc/welison/FNIH.Liver/subtypes/Myeloid/LiverUnionPeaks.bed > Myeloid_only_union_peaks.bed
tail -n +2 /nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/subtype.peaks/LiverUnionPeaks.bed > subtype_union_peaks.bed
tail -n +2 /nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/celltype.peaks/LiverUnionPeaks.bed > celltype_union_peaks.bed

In [ ]:
celltype.markers <- read.table('/nfs/lab/tscc/welison/FNIH.Liver/Yang.Marker.Peaks/FNIH_Liver.celltype_specific_peaks.txt') 

dim(celltype.markers)
head(celltype.markers)

In [ ]:
for (cell in cells) {
    filter(celltype.markers, !stringr::str_detect(V2, '\\|')) %>%
        filter(V2=='Hepatocytes') %>%
        mutate(chr=str_split(V1,'-',simplify=T)[,1],
               start=str_split(V1,'-',simplify=T)[,2],
               end=str_split(V1,'-',simplify=T)[,3]) %>%
        select(chr,start,end) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/241216_WE_',cell,'_Yang_specific_peaks.bed'),
                   col.names=F, row.names=F, quote=F, sep='\t')
    filter(celltype.markers, str_detect(V2,'Hepatocytes')) %>%
        mutate(chr=str_split(V1,'-',simplify=T)[,1],
               start=str_split(V1,'-',simplify=T)[,2],
               end=str_split(V1,'-',simplify=T)[,3]) %>%
        select(chr,start,end) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/241216_WE_',cell,'_Yang_marker_peaks.bed'),
                   col.names=F, row.names=F, quote=F, sep='\t')
}

# New Markers

In [8]:
cells <- scan('/nfs/lab/tscc/rlmelton/liver_HOMER/liver_data/listofcells.txt', what="", sep="\n")
cells <- cells[cells != 'Bulk']
cells

 [1] "B"             "Cholangiocyte" "Endothelial"   "Hepatocytes"
 [5] "HSC"           "Mast"          "Myeloid"       "NK"
 [9] "Schwann"       "T"

In [3]:
celltype.markers <- read.table('/nfs/lab/tscc/welison/FNIH.Liver/Yang.Marker.Peaks/FNIH_Liver.celltype_specific_peaks.txt') 

dim(celltype.markers)
head(celltype.markers)

[1] 58632     2

  V1                       V2
1 chr1-1000018-1000318     Cholangiocyte|Endothelial|HSC
2 chr1-1000344-1000644     Cholangiocyte|HSC|Schwann
3 chr1-100037929-100038229 B|NK|T
4 chr1-100132868-100133168 NK|T
5 chr1-1001838-1002138     Cholangiocyte|HSC
6 chr1-100266031-100266331 Mast|NK|T

In [9]:
for (cell in cells) {
    filter(celltype.markers, !stringr::str_detect(V2, '\\|')) %>%
        filter(V2==cell) %>%
        mutate(chr=str_split(V1,'-',simplify=T)[,1],
               start=str_split(V1,'-',simplify=T)[,2],
               end=str_split(V1,'-',simplify=T)[,3]) %>%
        select(chr,start,end) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/241216_WE_',cell,'_Yang_specific_peaks.bed'),
                   col.names=F, row.names=F, quote=F, sep='\t')
    filter(celltype.markers, str_detect(V2,cell)) %>%
        mutate(chr=str_split(V1,'-',simplify=T)[,1],
               start=str_split(V1,'-',simplify=T)[,2],
               end=str_split(V1,'-',simplify=T)[,3]) %>%
        select(chr,start,end) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/241216_WE_',cell,'_Yang_marker_peaks.bed'),
                   col.names=F, row.names=F, quote=F, sep='\t')
}

In [10]:
celltype.markers <- read.table('/nfs/lab/tscc/welison/FNIH.Liver/Yang.Marker.Peaks/FNIH_Liver.cellsubtype_specific_peaks.txt') 

dim(celltype.markers)
head(celltype.markers)

[1] 62053     2

  V1
1 chr1-1000018-1000318
2 chr1-1000344-1000644
3 chr1-100187946-100188246
4 chr1-100292692-100292992
5 chr1-100351219-100351519
6 chr1-100351529-100351829
  V2
1 Activated.HSC|Cholangiocyte|Lymphatic.Endothelial|Mesenchymal|Quescent.HSC
2 Activated.HSC|Mesenchymal|Quescent.HSC
3 Hepatocytes.Stress
4 Lymphatic.Endothelial
5 Mast
6 Mast

In [24]:
cells <- celltype.markers %>%
    filter(!str_detect(V2, '\\|')) %>%
    select(V2) %>%
    unique() %>%
    unlist()

cells

                          V21                           V22
         "Hepatocytes.Stress"       "Lymphatic.Endothelial"
                          V23                           V24
                       "Mast"                           "T"
                          V25                           V26
              "Activated.HSC"                      "Plasma"
                          V27                           V28
                         "NK"                     "Kupffer"
                          V29                          V210
"Lipid.Associated.Macrophage"                "Quescent.HSC"
                         V211                          V212
                          "B"               "Cholangiocyte"
                         V213                          V214
                    "Schwann"                  "Macrophage"
                         V215                          V216
      "Hepatocytes.Senescent"      "Sinusoidal.Endothelial"
                         V217                          V218
   "Central.Vein.Endothelial"                 "Mesenchymal"
                         V219                          V220
       "Vascular.Endothelial"           "Hepatocytes.Zone1"
                         V221                          V222
          "Hepatocytes.Zone3"           "Hepatocytes.Zone2"

In [25]:
for (cell in cells) {
    filter(celltype.markers, !stringr::str_detect(V2, '\\|')) %>%
        filter(V2==cell) %>%
        mutate(chr=str_split(V1,'-',simplify=T)[,1],
               start=str_split(V1,'-',simplify=T)[,2],
               end=str_split(V1,'-',simplify=T)[,3]) %>%
        select(chr,start,end) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/241216_WE_',cell,'_Yang_specific_peaks_subtypes.bed'),
                   col.names=F, row.names=F, quote=F, sep='\t')
    filter(celltype.markers, str_detect(V2,cell)) %>%
        mutate(chr=str_split(V1,'-',simplify=T)[,1],
               start=str_split(V1,'-',simplify=T)[,2],
               end=str_split(V1,'-',simplify=T)[,3]) %>%
        select(chr,start,end) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/241216_WE_',cell,'_Yang_marker_peaks_subtypes.bed'),
                   col.names=F, row.names=F, quote=F, sep='\t')
}

In [26]:
celltype.markers <- read.table('/nfs/lab/tscc/welison/FNIH.Liver/Yang.Marker.Peaks/FNIH_Liver.Hepatocyte_specific_peaks.txt') 

dim(celltype.markers)
head(celltype.markers)

[1] 1010    2

  V1                       V2
1 chr1-101258017-101258317 Hepatocytes.Zone3
2 chr1-109198368-109198668 Hepatocytes.Senescent
3 chr1-111592955-111593255 Hepatocytes.Senescent
4 chr1-112700706-112701006 Hepatocytes.Senescent
5 chr1-112704716-112705016 Hepatocytes.Senescent
6 chr1-112705021-112705321 Hepatocytes.Senescent

In [27]:
cells <- celltype.markers %>%
    filter(!str_detect(V2, '\\|')) %>%
    select(V2) %>%
    unique() %>%
    unlist()

cells

                    V21                     V22                     V23
    "Hepatocytes.Zone3" "Hepatocytes.Senescent"    "Hepatocytes.Stress"
                    V24                     V25
    "Hepatocytes.Zone1"     "Hepatocytes.Zone2"

In [28]:
for (cell in cells) {
    filter(celltype.markers, !stringr::str_detect(V2, '\\|')) %>%
        filter(V2==cell) %>%
        mutate(chr=str_split(V1,'-',simplify=T)[,1],
               start=str_split(V1,'-',simplify=T)[,2],
               end=str_split(V1,'-',simplify=T)[,3]) %>%
        select(chr,start,end) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/241216_WE_',cell,'_Yang_specific_peaks_Hepatocytes.bed'),
                   col.names=F, row.names=F, quote=F, sep='\t')
    filter(celltype.markers, str_detect(V2,cell)) %>%
        mutate(chr=str_split(V1,'-',simplify=T)[,1],
               start=str_split(V1,'-',simplify=T)[,2],
               end=str_split(V1,'-',simplify=T)[,3]) %>%
        select(chr,start,end) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/241216_WE_',cell,'_Yang_marker_peaks_Hepatocytes.bed'),
                   col.names=F, row.names=F, quote=F, sep='\t')
}

In [29]:
celltype.markers <- read.table('/nfs/lab/tscc/welison/FNIH.Liver/Yang.Marker.Peaks/FNIH_Liver.HSC_specific_peaks.txt') 

dim(celltype.markers)
head(celltype.markers)

[1] 1022    2

  V1                       V2
1 chr1-10378486-10378786   Quescent.HSC
2 chr1-10530327-10530627   Quescent.HSC
3 chr1-111481676-111481976 Quescent.HSC
4 chr1-111515674-111515974 Quescent.HSC
5 chr1-111516097-111516397 Quescent.HSC
6 chr1-111535774-111536074 Quescent.HSC

In [30]:
cells <- celltype.markers %>%
    filter(!str_detect(V2, '\\|')) %>%
    select(V2) %>%
    unique() %>%
    unlist()

cells

            V21             V22             V23
 "Quescent.HSC"   "Mesenchymal" "Activated.HSC"

In [31]:
for (cell in cells) {
    filter(celltype.markers, !stringr::str_detect(V2, '\\|')) %>%
        filter(V2==cell) %>%
        mutate(chr=str_split(V1,'-',simplify=T)[,1],
               start=str_split(V1,'-',simplify=T)[,2],
               end=str_split(V1,'-',simplify=T)[,3]) %>%
        select(chr,start,end) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/241216_WE_',cell,'_Yang_specific_peaks_HSC.bed'),
                   col.names=F, row.names=F, quote=F, sep='\t')
    filter(celltype.markers, str_detect(V2,cell)) %>%
        mutate(chr=str_split(V1,'-',simplify=T)[,1],
               start=str_split(V1,'-',simplify=T)[,2],
               end=str_split(V1,'-',simplify=T)[,3]) %>%
        select(chr,start,end) %>%
        write.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/241216_WE_',cell,'_Yang_marker_peaks_HSC.bed'),
                   col.names=F, row.names=F, quote=F, sep='\t')
}